### ISSUE TITLE
Why a seperate execuitable? Why not an XMonad module?

### ISSUE THREAD

**Issue by james-darkfox** [jaor/xmobar#100]
As I see it, there is no true reason to why xmobar needs to be a seperate execuitable. But rather a module for XMonad.

For all the configuration, that could be in the XMonad config or in a seperate module in ~/.xmonad/lib/XMonad/Hooks/XMobar.hs which would import XMonad.Hooks.XMobar.Core or something.

It would be much cleaner to not have the extra IO of a seperate execuitable. You took the issue that XMonad doesn't have any panel of any such built in. You made a nice tool. Personally, I've been using dzen2 because you didn't have icon support back when I was building my config.

It would be really nice to see XMobar being a module for XMonad instead of an external execuitable. It's not built in, it's not a module so it can't even be added to xmonad-contrib which would increase the use of the pannel.

Sure, building an execuitable can be nice and used for other window managers; So, instead of just ditching the execuitable, it wouldn't hurt to use it's base to keep an execuitable for those users.

Is there any reason that you haven't made xmobar a module for XMonad? You've got all the features you need and a nice way to extend with the plugins. But no module for XMonad it's self?

**Comment by jaor** [comment]
This has been fixed for a while: xmobar can be compiled a la xmonad these days. Closing!
