### ISSUE TITLE
Text drawn 1px too low

### ISSUE THREAD

**Issue by cshapeshifter** [jaor/xmobar#201]
Hi,

I just started using xmobar. Problem is, that text seems to be placed too low. See this screenshot, showing two bars, one Top, one Bottom, both magnified for easy viewing:
![xmobar](https://cloud.githubusercontent.com/assets/3042135/4704679/fc9c6338-5873-11e4-8121-13339901c28b.png)
It's clear that the font is sitting 1px too low. The gap above the text is 5px, the one below is 3px. Both should be 4px, it seems. Icons on the other hand seem to be aligned perfectly.

Configuration doesn't matter. Even if I just run `xmobar -t "ASdf" -o` or `xmobar -t "ASdf" -b`, the font sits too low. It doesn't matter which font or font-size I use, or whether I use icons or not.

I'm on archlinux, using xmobar 0.21 from May, but people on irc.freenode.org#xmonad are reporting the same problem with xmobar 0.22. I don't have any special patched font libraries or fontconfig.

PS: Another user just noticed that the problem is even more obvious when using larger font sizes, e.g.
```
xmobar -t "ASdf" -b --font="-*-terminus-medium-r-normal-*-16-*-*-*-*-*-iso10646-*"
```
or
```
xmobar -t "ASdf" -b --font="xft:Dejavu Sans Mono:size=42"
```
![2014-10-20-183537_414x230_scrot](https://cloud.githubusercontent.com/assets/3042135/4704987/31758b40-5877-11e4-94d4-59134a73441c.png)

PPS: Seems like you already know about this: https://github.com/jaor/xmobar/pull/171 . Since it seems like the vertical alignment depends heavily on the client (font, fontconfig, etc.) and since you can't figure out a way to make it work consistently, I would suggest adding a textVerticalOffset option of some kind, so that people can easily adjust the vertical alignment themselves if the calculation is off.

**Comment by jaor** [comment]
closing, please reopen if there's still any problem.
