### ISSUE TITLE
Background color ignored.

### ISSUE THREAD

**Issue by johntyree** [jaor/xmobar#209]
When passing something like `<fc=red,yellow>0:IRC</fc>` in to the StdinReader, only the foreground color is used.
![2015-01-05_20 51 46 65](https://cloud.githubusercontent.com/assets/108972/5623630/8e38b816-951c-11e4-8a54-b2162546d67f.png)

I have verified that the input is indeed correct by piping it to a file instead. The last time I updated anything was this time last year (git log says ~Jan 2013) and it was working correctly then.

**Comment by jaor** [comment]
i understand this is happening with latest git?

**Comment by johntyree** [comment]
Yes. Bisect seems to suggest it's related to transparency / tint (a98ac8fba46b8858959cee6062a49c9121f07fe9). My background is black so I'm not sure yet.

**Comment by johntyree** [comment]
Setting `alpha = 255` in xmobarrc doesn't fix it. Looks like transparency only refers to parts of the bar that aren't displaying anything maybe?

**Comment by johntyree** [comment]
Well this is pretty suspicious...  https://github.com/jaor/xmobar/commit/a98ac8fba46b8858959cee6062a49c9121f07fe9#diff-f0a4f22929b0e9403dae9dae189eab56L160

**Comment by johntyree** [comment]
Yeah... I don't know enough about how the rendering is done to make any educated guesses here :(

I'll stick to 0.23 for now, which is the release just before the alpha/tint stuff was introduced and appears to handle it correctly.

**Comment by jaor** [comment]
yep, the transparency patch is the culprit: i'll work something out when
i find a second.  thanks for the report!

**Comment by jaor** [comment]
i've just pushed a patch that should make xmobar honour `fc` background
color specifications when alpha is set to 255 (no transparency, the
default).  when alpha is less than 255, i'm still ignoring the
background color, but for now let's say that that's how transparency
works :)

**Comment by johntyree** [comment]
Works for me! Thanks!

**Comment by amerlyq** [comment]
To be completely sure, font background with alpha < 255 is completely impossible due to Xft/Xrandr implementations, or temporarily impossible until someone will think it out and submit patch to xmobar itself? In primary issue #32 I haven't found final conclusion.

**Comment by RossComputerGuy** [comment]
I'm having this exact issue with my setup, I'm trying to have no background on the panel but have a background on the modules.
```
Config {
        font="DejaVuSansMono Nerd Font",
        bgColor="#3c4264",
        fgColor="#ffffff",
        alpha=0,
        overrideRedirect=False,
        border=NoBorder,
        borderColor="#000000",
        template="<fc=#ffffff,#3c4264>%memory% | %battery%</fc>}{<fc=#ffffff,#3c4264>%date%</fc>",
        commands=[
                Run Memory [
                        "--template", "M: <usedratio>%",
                        "--Low", "20",
                        "--High", "90",
                        "--low", "#46a15e",
                        "--normal", "#a1a046",
                        "--high", "#a14659"
                ] 2,
                Run Battery [
                        "--template", "B: <acstatus>",
                        "--Low", "20",
                        "--High", "80",
                        "--low", "#a14659",
                        "--normal", "white",
                        "--high", "#46a15e",
                        "--",
                        "-o", "<left>%",
                        "-O", "Charging",
                        "-i", "Charged"
                ] 2,
                Run Date "%D %r" "date" 1
        ]
}
```
