### ISSUE TITLE
Incorrect Handling of Color Thresholds in Network Monitor

### ISSUE THREAD

**Issue by egan** [jaor/xmobar#211]
I have been using the following line for show network transmission rates on xmobar:

```
                           , Run Network "eno1"
                           ["-t","Dn: <rx>kb/s <fc=#990000>|</fc> Up: <tx>kb/s","-L","0","-H","1000","-n","#00d900","-h","#e50000","-m","6","-c"," "] 10
```

Lately (I believe since xmobar 0.22.1-2), the numerals have been displayed red (#e50000) when well below the 1000kb/s threshold. I believe this may have something to do with the adaptive units (which I do not want), as numbers like '1' display as green and red at different times.

**Comment by jaor** [comment]
If you don't want adaptive units, does "-S", "Off" in the list of
arguments disable them and make color thresholds work again?

        , Run Network "eno1"
        ["-S", "Off", "-t","Dn: <rx>kb/s <fc=#990000>|</fc> Up: <tx>kb/s","-L","0","-H","1000","-n","#00d900","-h","#e50000","-m","6","-c"," "] 10

**Comment by egan** [comment]
It doesn't. I'm not sure that the issue is due to adaptive units but it was a theory based on the aliasing of numbers.

**Comment by jaor** [comment]
@egan, sorry for the delay... i just checked and the thing is that the
threshold is not in kb/s but in b/s, so if you change your -H to
1024000, it'd work as you expect.  at least it does for me.  we have
already open a documentation bug to add to all monitor descriptions
the unit used for their respective thresholds.

**Comment by egan** [comment]
That appears to be it, thanks.
