### ISSUE TITLE
Vertical alignment issues in 0.23

### ISSUE THREAD

**Issue by jpalus** [jaor/xmobar#221]
After switching to xmobar 0.23 vertical alignment was broken both for text and icons (even after applying icon alignment patch). According to documentation both text and icons should be centered by default but in version 0.23:
- text is moved up which is especially visible for text with background
- icon is moved up and is half visible (vanilla 0.23) or is moved down (after applying fix for #216)

Please compare screenshots
![xmobar-0 22 1](https://cloud.githubusercontent.com/assets/484155/6675320/e6ee850a-cc1f-11e4-9608-7c01ac04a753.png)
![xmobar-0 23](https://cloud.githubusercontent.com/assets/484155/6675321/e6f0e89a-cc1f-11e4-9eaf-21468c254b5b.png)

**Comment by jaor** [comment]
the misalignment in the fixed one is a missed battle: it happens for
some fonts, and if we change the off-by-one "error," then it's other
fonts that look misaligned (for instance, the reporter of issue #216 was
happy with the final icon alignment).  that's why we introduced the
configuration options `iconOffset` and `textOffset`: would that work as
a workaround for you?

**Comment by jaor** [comment]
@jpalus i've just pushed a patch that tries to fix the issue for you, without using configuration parameters, in the hope that your case is the more common.  does it work better for you?

**Comment by jpalus** [comment]
Thanks jaor, icon placement looks to be exactly the same as in 0.22, but text looks to be moved down only by 1px or so.
![xmobar-0 23 1](https://cloud.githubusercontent.com/assets/484155/6697186/3dd74ec2-ccef-11e4-9b83-6c0b835f7f61.png)
I can make it work by using textOffset but in that case documentation and maybe even icon placement should be updated and made consistent.

**Comment by jaor** [comment]
could you please share the relevant bits of your xmobar config? i cannot
reproduce the weird text placement you see...

**Comment by jpalus** [comment]
I suppose only following part is relevant:
```haskell
Config { font = "xft:Terminus"
       , bgColor = "#d2d2d0"
       , fgColor = "#000000"
       , position = TopW L 100 
```
Later to get green background, inline markup is used: \<fc=#ffffff,#657851\>

**Comment by jaor** [comment]
i think a problem here is that it's not possible to have the same width above and below the text because the default height of xmobar is (say) 20 and of the text (counting ascent and descent) is (say) 15.  that doesn't explain the disalignment you see, but perhaps trying something like `TopSize L 100 21` (and playing with the last value, which is the height) might help.

the thing is that i see text aligned in my system, so my guess is that there's something in the fonts definitions that is different.  do you have the same problem if you use any other font?

**Comment by jpalus** [comment]
Following your suggestion I've tried with:
- different font (Inconsolata)
- bigger font (22)
- bigger bar size (66)

and noticed the same behaviour as with Terminus but with bigger size something different became visible. It is not the font that is not centered correctly, it is the background actually that probably gives wrong impression.
![xmobar-big](https://cloud.githubusercontent.com/assets/484155/6717962/72fb5bb8-cdb0-11e4-9e8a-6cb6b54505ea.png)

**Comment by jaor** [comment]
oh, i see... i've tried to fix the background alignment with a new
patch, althought sometimes it gives me the impression of being
one-off... how does it look now for you?

**Comment by jpalus** [comment]
Thx a lot jaor for you patience. It looks much better now though there's still room for improvement :). This time I did some pixels counting in gimp. Few observations:
- I've managed to get perfectly aligned fonts/background with font size = 14 and bar height = 32, 3px of additional space were added for background (3px on top + 3px at the bottom), text was perfectly centered
- when I switched slightly to size = 13 height = 31 vertical alignment degradated significantly - text was not aligned correctly (11px to the top, 7px to the bottom of a bar), background was much better but this time odd number of pixels were added so it had 1px of difference in vertical alignment (I think always even number of pixels should be added for background)
- background seems to always have 3 additional pixels added horizontally on the right side comparing to the left one

**Comment by jaor** [comment]
nah, thanks to *you* for your thorough reports. i've tried to improve
things with yet another patch.  please give it a try if you still have a
bit of patience left :)

**Comment by jpalus** [comment]
Another step forward but it's still 1px from the target :)

Let's take previous example with font = 13 and bar height = 31

| What | Expected | Actual |
| -------- | --------------- | ---------- |
| Pixels from text to top | 9 | 10 |
| Pixels from text to bottom | 9 | 8 |
| Background height - text height | Even | Odd |
| Number of background pixels on the right and left side of text | Same | Different (11 left, 12 right) |

**Comment by jaor** [comment]
i've improved things, but there are still problems.  for the 13/31 combination things look fine (although sometimes not as you expect) for both terminus and inconsolata:

![inconsolata-13-31](https://cloud.githubusercontent.com/assets/80719/6744368/ffc315ba-cea8-11e4-9191-44d2625df88a.jpg)
![terminus-13-31](https://cloud.githubusercontent.com/assets/80719/6744370/0b049656-cea9-11e4-928b-d1baf4231124.jpg)

and using inconsolata-11 seems also fine:

![inconsolata-11-31](https://cloud.githubusercontent.com/assets/80719/6744381/2707ba22-cea9-11e4-86b9-57090fe2b41e.jpg)

but terminus-11 misbehaves:

![terminus-11-31](https://cloud.githubusercontent.com/assets/80719/6744388/3e3e0368-cea9-11e4-84af-9fa49fd217a7.jpg)

i don't know the reason... maybe the font for that size is synthesized and the font geometry changes?

**Comment by jpalus** [comment]
Sorry for not responding this long but I wanted to experiment myself and maybe provide a patch as a result. I failed for two reasons -- first of all my haskell skills are not any near to not only write a patch but even understand what is actually going on in simple code. Second documentation for X API is in my opinion truly horrible -- incomplete or if present confusing. I weep for people who are forced to use it. Nevertheless I've gathered some knowledge and came to few conclusions so I hope you have some more patience to get through all of this :)

Let me start with confession that it's the first time I work with fonts so some of my statements might more than obvious or just plainly wrong. I would appreciate correcting me where necessary.

As far as I understand font's height consists of an ascent (part above baseline, the "main" part) and descent (part below baseline):
![Font composition](http://www.pyglet.org/doc/programming_guide/font_metrics.png)
I suppose it is sufficient to vertically align ascent part alone. But here's where problems start to occur -- Xft API contains struct _XftFont_ which seems to contain what is needed _descent_ and _ascent_ fields. When searching for information on different but related struct _XGlyphInfo_ I came across [this post](http://permalink.gmane.org/gmane.comp.fonts.fontconfig/505) by Keith Packard. Leaving for a moment the fact that he's confused about his own API, it tells how to calculate ascent/descent from _XGlyphInfo_. I wrote simple C program to compare values reported by both methods (see [here](https://gist.github.com/jpalus/eaccf7f1a7d4ea9c9ec2)) and results are quite surprising:
```
> $ ./fontextents Inconsolata-10 Inconsolata-15 Inconsolata-28 Terminus-10 Termonsolas-15 Consolas-28 Monaco-10 Monaco-15 Monaco-28
Inconsolata-10: XftFont(ascent=11, descent=2) XGlyphInfo(ascent=9, descent=1
Inconsolata-15: XftFont(ascent=17, descent=4) XGlyphInfo(ascent=13, descent=2
Inconsolata-28: XftFont(ascent=32, descent=7) XGlyphInfo(ascent=24, descent=4
Terminus-10: XftFont(ascent=12, descent=2) XGlyphInfo(ascent=12, descent=2
Terminus-15: XftFont(ascent=16, descent=4) XGlyphInfo(ascent=16, descent=4
Terminus-28: XftFont(ascent=26, descent=6) XGlyphInfo(ascent=26, descent=6
Consolas-10: XftFont(ascent=10, descent=3) XGlyphInfo(ascent=10, descent=3
Consolas-15: XftFont(ascent=15, descent=5) XGlyphInfo(ascent=14, descent=4
Consolas-28: XftFont(ascent=27, descent=10) XGlyphInfo(ascent=27, descent=8
Monaco-10: XftFont(ascent=13, descent=3) XGlyphInfo(ascent=10, descent=2
Monaco-15: XftFont(ascent=20, descent=5) XGlyphInfo(ascent=15, descent=5
Monaco-28: XftFont(ascent=37, descent=9) XGlyphInfo(ascent=30, descent=7
```
To me results reported by XGlyphInfo seem to be closer to "real world" than XftFont, though ie for Terminus they are the same.

Looks like xmobar is using XftFont method within textExtents function so it might be one point of potential improvement.

Next I came up with my own algorithm for vertical alignment which might as well match current xmobar codebase, but anyway would like to share. Let's start with defining minimum window height having _ascent_ and _descent_ obtained by whatever method:
```c
int height = ascent + 2 * descent + 2 * C;
```
C is arbitrary constant number of pixels that should be added more so ie descent does not reach window border. In that case there are _descent + C_ number of pixels above ascent and same below.
Height of course might be overriden by user settings.

Once window height, ascent and descent are known let's get to vertically aligning ascent by defining its baseline. Baseline is defined as _y_ value for the first pixel of ascent starting from the bottom:
```c
int baseline = height - ((height - ascent) / 2) - 1
```
One note: it is crucial to make as little division operations as possible as in case of odd values pixels are being "lost". It is also crucial not to rely on values calculated by using division if not necessary, so for example to calculate rectangle around font it's better not to rely on baseline. Subtracting 1 at the end is necessary to calculate _y_ value of first pixel of ascent and not the one below ascent.

Above should give vertically aligned text within window (at least it's my best effort to do so :) ). Now let's focus on rectangle with background around font. Again its height and _y_ position need to be calculated. Let's start with height:
```c
int rect_height = ascent + (2 * descent) + 2 * D;
```
First border needs to cover ascent, second it needs to cover descent but to be symmetric we take two descent values and finish with arbitrary constant D of pixels which are added on each side. Multiplying both descent and D by 2 ensures odd number of pixels added to ascent. D might be dynamic as well, ie it could be percentage of space left:
```c
int D = (height - baseline - descent) / 2
```
_y_ position of rectangle depends directly on its height:
```c
int rect_y = (height - rect_height) / 2;
```

Please let me know what you think if you managed to reach this point.

**Comment by jaor** [comment]
@jpalus thanks a lot for the detailed analysis.  the discrepancies between the two libraries you discovered go a long way to dispel my perplexity with the results i was seeing! i haven't had time yet to revise my code along the lines you suggest, but i promise i will :)

**Comment by jaor** [comment]
@jpalus i've been experimenting a bit, and finally computed the baseline in a different way.  if we have height pixels available and the text is taking (ascent + descent), we can lower the baseline (height - (ascent + descent)/2) below the ascent, giving us:

       y =  ascent + (height - ascent - descent) / 2 - 1

for the actual y coordinate of the baseline (using a single division). this seems to be producing acceptable results, but there's the problem you detected with the computation of ascent/descent... we're using XGliphInfo for it, but at least for me not all faces seem to be reporting good results.

**Comment by jpalus** [comment]
@jaor just played a bit with latest xmobar version and indeed vertical alignment of text looks much better now. The reason why I did not take descent in my baseline calculation formula is because I've got like 3-5 chars in whole bar that actually use descent so most of the text "mass" composes out of ascent and hence thought to center ascent only.

However there are still two minor issues left with background box. If correct size of font and bar are given the distance from background to top and bottom border should be equal but I cannot achieve this. Looks like there's always 1px of difference which is quite visible as I prefer to have 2-3 px there. The other issue is with added space on the sides. On the left there is 1px less than on the right.

Let's hope though that issues with border can be easily fixed and we can finally close this ticket :)

**Comment by jaor** [comment]
@jpalus i've pushed a slight modification that seems to be working for me, ahem, most of the time.  the more i read the scanty xft doc bits and the more experiment with it, the less i understand how it's supposed to work :( so what seem to me the "right" expressions (similar to those you derived) never seem to do the right thing.  i guess my understanding is flawed, but so is the library's author's!!! :)

Anyway, please let me know how this one looks to you!

**Comment by jpalus** [comment]
@jaor Thanks I'm now fully satisfied with vertical alignment/vertical border size and almost there with horizontal border side :) While previously right side had 1px more, now left size has 2px more (Inconsolata-12 text "[5:web]" 10px on the left side, 8px on the right).

**Comment by jaor** [comment]
in the attached image, how many pixels do you consider margin to the right? 2 or 3 pixels?

![1](https://cloud.githubusercontent.com/assets/80719/7221769/76e8a93a-e6f9-11e4-9304-6f3953185daf.png)

(there's no way i can produce a 8 or 10 px margin: was that a typo? or perhaps you're counting also additional whitespace in the input text?)...

**Comment by jaor** [comment]
@jpalus did you see my latest question? or did i manage to finally exhaust your patience? not that i'd blame you for that!! :D

**Comment by jpalus** [comment]
@jaor sorry I completely forgot about your question, probably because alignment works fine now :) To count pixels I just zoom in image in gimp so I can count individual pixels shown on the ruler. See screenshot
![xmobar-px](https://cloud.githubusercontent.com/assets/484155/7669866/ca29342a-fc89-11e4-9b28-55b022a67b74.png)
Until now I've considered pixels 9-11 on the left and 65-66 to be a border but after spending some time with fonts in X I'm not so sure if that's really correct.

**Comment by jaor** [comment]
@jpalus yeah, i've been actually counting pixels 64-66 as right margin and considering that background as "correct".  however, even if we take that as our definition of "borders," your previous comment (10px to the left, 8 px to the right) seems to indicate that you still don't see things right, no? how do you manage to have those much wider borders?

**Comment by jpalus** [comment]
@jaor that's a screenshot of [5:web] with Inconsolata-12 configured as font and 10px on the left side/8px on the right
![xmobar-inconsolata-12-borders](https://cloud.githubusercontent.com/assets/484155/7689687/7e837938-fdae-11e4-94c5-ab7ac1381caf.png)
. There is one important note though - I've checked my xmonad configuration and selected workspace is wrapped with "<space>[" "]<space>" so that might give a bit more space to borders

**Comment by jaor** [comment]
@jpalus and what happens if you don't put there the spaces?  do you see the same as i do? what's in your bar just before the workspace? could it be a previous monitor is contributing to that margin?

**Comment by jpalus** [comment]
New screenshot with spaces removed and some more "context" of what is next to [5:web]. I have two screens though xmobar is visible only on the main one, the other is configured to be left from main screen. Without spaces I have 2px on the left and 0px on the right.
![xmobar-inconsolata-12](https://cloud.githubusercontent.com/assets/484155/7712522/0d176f74-fe72-11e4-8309-82d195bf9e01.png)

**Comment by jaor** [comment]
i see... as usual, i cannot quite reproduce what you see ;) well, to be
honest sometimes i can: it depends on the font family, and possibly some
other factor that scapes me.  for instance, i can reproduce the
misalignment with terminus, but not inconsolata.  anyway, i've pushed a
patch that makes terminus look splendid and inconsolata almost right:
how does it look for you now?

**Comment by jpalus** [comment]
Looks perfect now, thanks! I think it is the high time to close this issue :)

**Comment by jaor** [comment]
oh dear, i can barely belive it!!! :)  seriously, jan, rest assured your
help, thoroughness and patience are enormously appreciated.
