### ISSUE TITLE
bgcolor, fgcolor command line arguments doesn't work with hex codes.

### ISSUE THREAD

**Issue by artyommironov** [jaor/xmobar#222]
If you configure xmobar from command line then bgcolor and fgcolor arguments are useless, because they accepts color names, but these colors except white and black are totally awful for human eyes. In my case I want particular shade of gray for background color,

**Comment by jaor** [comment]
i'm not sure i understand: what color code have you tried? for instance:

    xmobar -B "#FFF8DC" -F "#0000cc"

works just fine for me. single quotes also work:

    xmobar -B '#FFF8DC' -F '#0000cc'

(as an aside, i'm surprised you find *all* named X11 colors useless,
there're [quite a few](http://en.wikipedia.org/wiki/X11_color_names)).

**Comment by kazufukurou** [comment]
Now I see it works when you run it from command line. But for some reason from haskell code it not works, the bar not show up

--Not works
myBar = "xmobar -d -c '[]' -B #aabbcc -F white -t '%StdinReader% }{ "
--Works
myBar = "xmobar -d -c '[]' -B pink -F white -t '%StdinReader% }{ "

main = xmonad =<< statusBar myBar myPP toggleStrutsKey myConfig

**Comment by jaor** [comment]
aren't you missing quotes? as in:

       myBar = "xmobar -d -c '[]' -B '#aabbcc' -F white -t '%StdinReader% }{ "

or maybe

       myBar = "xmobar -d -c '[]' -B \"#aabbcc\" -F white -t '%StdinReader% }{ "

**Comment by kazufukurou** [comment]
Neither variants works from code. Also it works without quotes from command line.

**Comment by jaor** [comment]
i'm not sure then what's going on with the haskell code and `statusBar`
in particular.  i guess it depends on what function it's using to invoke
xmobar... you could perhaps try to use a haskell function that
takes the argument list explicitly, like `proc` in `System.Process`

**Comment by munyari** [comment]
Hey @jaor. Have you thought about including the fact that it all the X11 colors are available in this documentation? http://projects.haskell.org/xmobar/

**Comment by jaor** [comment]
thanks for the heads up: i will in the next release!
