### ISSUE TITLE
xbm colors are inverted and/or bg color is ignored

### ISSUE THREAD

**Issue by cshapeshifter** [jaor/xmobar#228]
xbm icons in my setup are drawn incorrectly:
* Their background is drawn using fgColor or the specified fc fg color
* Their foreground is drawn using the fgColor and fc settings have no effect
* In an ```<fc=X,Y>``` setting, the Y is ignored, and X is used to draw the background of the icon

I made this example with ugly colors just to illustrate the problem:

![2015-04-17-152533_109x32_scrot](https://cloud.githubusercontent.com/assets/3042135/7202816/019f39e4-e516-11e4-8ed6-37cde127295f.png)

The icons are from here:
http://sourceforge.net/projects/stlarchicons/

The config:
```
Config { font = "-*-terminus-*-*-*-*-12-*-*-*-*-*-*-u"
  , bgColor = "#00ff00"
  , iconOffset = 6
  , fgColor = "#ff0000"
  , border = NoBorder
  , borderColor = "#000000"
  , position = Top
  , lowerOnStart = True
  , hideOnStart = False
  , persistent = True
  , commands = [ ]
  , sepChar = "%"
  , alignSep = "}{"
  , template = "1: <icon=/usr/share/icons/stlarch_icons/ac15.xbm/> 2: <fc=#ffffff><icon=/usr/share/icons/stlarch_icons/ac15.xbm/></fc> 3: <fc=#ffffff,#000000><icon=/usr/share/icons/stlarch_icons/ac15.xbm/></fc>"
  }
```

There is a clear discrepancy between what's been configured and what is displayed:
* icon 1 has fg and bg red, although it should have fg red and bg green
* icon 2 has fg red and bg white, although it should have fg white and bg green (fg from fc setting)
* icon 3 has fg red and bg white, although it should have fg white and bg black (fg/bg from fc setting)

I don't know what's going on, since I don't have this problem on another machine with identical settings. I'm not at the 2nd machine right now but I'll try to supply any differences tonight. Setup of this machine:

* Arch Linux with linux 4.0.0 (other than linux and systemd, no packages are from [testing] and I had this problem before switching to [testing])
* ghc 7.10.1
* xmobar 0.23.1 (built on April 15)
* xmonad 0.11.1
* Intel 5500 chipset with xf86-video-intel 2.99.917

EDIT: I confirmed that the problem does not occur on two other systems with a very similar setup. The other systems are still on Linux 3.19.3 and one has nvidia graphics, while the other has intel 4000 graphics, but both have ghc 7.10.1 and xmobar 0.23.1. I'm puzzled.

**Comment by cshapeshifter** [comment]
I don't know why, but the problem is gone! I updated a whole bunch of packages (including xmobar) so it's hard to tell what caused it. I'm closing this since nobody else seems to have experienced the problem.

**Comment by jaor** [comment]
thanks!

**Comment by chuym** [comment]
I'm actually experiencing this same problem. It seems to be related to the video card, I have the same one. I was running X with the generic drivers, then moved to the intel drivers and this issue started to happen.

If you're still around could you check if you have 3d acceleration?
````glxinfo | grep "OpenGL renderer"````

**Comment by cshapeshifter** [comment]
```
> glxinfo | grep "OpenGL renderer"
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2)
```
I'm using xf86-video-intel 1:2.99.917+478+gdf72bc5-3 and I haven't had any problems since closing this issue.

**Comment by chuym** [comment]
@cshapeshifter Thanks for chiming back after so long.

I have the same drivers, I recall the xbm icons looking completely fine, then after a system upgrade (upgraded from debian jessie to debian testing), they started looking bad.

At this point, I suspect the video drivers, some libraries or even the kernel (although that might be unlikely) because this issue happens with dzen2 as well.

Thank you, I'll keep looking for a solution.

**Comment by cshapeshifter** [comment]
If it helps, here's a list of possibly relevant packages that were upgraded at the time where the problem disappeared on my machine. If your system has the left-hand version of any of these packages, that package may be the culprit. There were other packages upgraded as well, too many to list all of them, but I guess these might have had an influence.

linux (4.2.1-1 -> 4.2.3-1)
xf86-video-intel (1:2.99.917+381+g5772556-1 -> 1:2.99.917+478+gdf72bc5-2)
xmobar (0.23.1-3 -> 0.23.1-4)

mesa (11.0.1-1 -> 11.0.3-1)
mesa-libgl (11.0.1-1 -> 11.0.3-1)
xcb-proto (1.11-1 -> 1.11-2)
xdg-utils (1.1.0.git20150323-1 -> 1.1.1-1)

haskell-utf8-string (1-2 -> 1-3)
haskell-x11 (1.6.1.2-4 -> 1.6.1.2-5)
haskell-x11-xft (0.3.1-14 -> 0.3.1-15)
