### ISSUE TITLE
Battery does not reach "charged" state

### ISSUE THREAD

**Issue by taketwo** [jaor/xmobar#231]
On my system the battery plugin properly reports "discharging" and "charging" states, however it never reaches "charged" state.

The decision whether AC is idle or not is made by comparing `watts` with zero (see [Batt.hs:163](https://github.com/jaor/xmobar/blob/master/src/Plugins/Monitors/Batt.hs#L163)). I set up the template to display watts with high precision, and in the steady state with AC connected the value is always -0.000001.

I wonder if we could have a certain threshold instead of testing equality with zero. This threshold should depend on the (undocumented) "scale" option though...

**Comment by jaor** [comment]
the scale option was mainly introduced as a workaround for a bug we had
back in the day, and these days shouldn't be needed, so i think it's not
worth the trouble to take it into account.  perhaps we could simply say
`idle = watts <= 0` covering cases such as yours.  what do you think?

**Comment by taketwo** [comment]
But this will mean that the `idle` flag will be set when discharging as well. Shouldn't we rather compare (perhaps absolute value of) `watts` with is a small constant?

**Comment by jaor** [comment]
sorry, you are right.  i guess the best is also adding a config parameter
controlling that small amount.

**Comment by taketwo** [comment]
Sounds good!

**Comment by bchallenor** [comment]
I have a similar issue with it never entering the idle state. Here's my config:

    Run Battery
    [ "-t", "Batt: <left><acstatus>"
    , "-L", "15", "-l", "red"
    , "--"
    , "-O", "+ (<timeleft>)"
    , "-i", ""
    , "-o", " (<timeleft>)"
    ]
    50

In other words, while charging I want the text to be e.g. `77+ (1:52)`, and when charged, for it to be simply `100`. Unfortunately I am seeing `100+ (-532:00)` when charged - i.e. "there are -532 hours remaining until the battery is charged!"

When my battery is charged, my system is in this state:

    $ cat /sys/class/power_supply/BAT0/charge_now 
    7570000
    $ cat /sys/class/power_supply/BAT0/charge_full
    7038000
    $ cat /sys/class/power_supply/BAT0/current_now
    1000
    $ cat /sys/class/power_supply/BAT0/status
    Full

I think the fact that `charge_now` exceeds `charge_full` explains the negative sign. Note `(7038000-7570000)/1000 = -532`.

So in my case, I guess there are a few possible solutions... We could take the max of "time remaining" and zero. We could threshold `current_now` against 1000. Or perhaps we could consider the status file, which in my case says "Full"?

**Comment by jaor** [comment]
i think the best way will be reading the status file, which can also
then tell us directly the value for `<acstatus>`.

**Comment by dermarens** [comment]
Same problem here:

+marens@nobby:/sys/class/power_supply/BAT0$ cat charge_now 
5600000
+marens@nobby:/sys/class/power_supply/BAT0$ cat charge_full
3600000
+marens@nobby:/sys/class/power_supply/BAT0$ cat current_now 
1000

So i have timeleft of -2000h when the battery is fully loaded :D

As soon as i unplug the laptop the charge_now drops below 3600000 though.

**Comment by jaor** [comment]
i've just pushed a patch that uses the status file to derive acstatus, and that tries to avoid negative remaining times.  please let me know how it works, @taketwo, @bchallenor and @dermarens, and my apologies for the long delay!

**Comment by dermarens** [comment]
Hey jaor,
i could already verify the fix on my machine. Now The remaining time is shown as 0:00h when the battery is fully charged. Thanks a lot for your work!

**Comment by mat8913** [comment]
The recent change made my battery always show fully charged when using "Battery" in the config file but "BatteryP" works fine. Probably because my laptop only has one battery, and by default `runBatt` assumes three. Non-existing batteries are taken to be `Idle` by default so in `readBatteries`,

    acst = head $ last [ [Discharging], [Idle, Idle] ]
         = head [Idle, Idle]
         = Idle

This patch fixes it for me:

    diff --git a/src/Plugins/Monitors/Batt.hs b/src/Plugins/Monitors/Batt.hs
    index fba45dd..cc16ec8 100644
    --- a/src/Plugins/Monitors/Batt.hs
    +++ b/src/Plugins/Monitors/Batt.hs
    @@ -147,7 +147,7 @@ haveAc f =
       where onError = const (return False) :: SomeException -> IO Bool
     
     readBattery :: Float -> Files -> IO Battery
    -readBattery _ NoFiles = return $ Battery 0 0 0 "Idle"
    +readBattery _ NoFiles = return $ Battery 0 0 0 "Unknown"
     readBattery sc files =
         do a <- grab $ fFull files
            b <- grab $ fNow files
    @@ -162,13 +162,16 @@ readBattery sc files =
         where grab f = handle onError $ withFile f ReadMode (fmap read . hGetLine)
               onError = const (return (-1)) :: SomeException -> IO Float
               grabs f = handle onError' $ withFile f ReadMode hGetLine
    -          onError' = const (return "Idle") :: SomeException -> IO String
    +          onError' = const (return "Unknown") :: SomeException -> IO String
     
     -- sortOn is only available starting at ghc 7.10
     sortOn :: Ord b => (a -> b) -> [a] -> [a]
     sortOn f =
       map snd . sortBy (comparing fst) . map (\x -> let y = f x in y `seq` (y, x))
     
    +mostCommonDef :: Eq a => a -> [a] -> a
    +mostCommonDef x xs = head $ last $ [x] : sortOn length (group xs)
    +
     readBatteries :: BattOpts -> [Files] -> IO Result
     readBatteries opts bfs =
         do bats <- mapM (readBattery (scale opts)) (take 3 bfs)
    @@ -183,7 +186,7 @@ readBatteries opts bfs =
                statuses :: [Status]
                statuses = map (fromMaybe Unknown . readMaybe)
                               (sort (map status bats))
    -           acst = head $ last $ sortOn length (group statuses)
    +           acst = mostCommonDef Unknown $ filter (Unknown/=) statuses
            return $ if isNaN left then NA else Result left watts time acst
     
     runBatt :: [String] -> Monitor String

**Comment by jaor** [comment]
Matthew, your patch looks good and i've applied it.  Maybe that also
solves the problem of @YoEight and @dsemi?  Would you mind to try guys?
Thanks!

**Comment by dsemi** [comment]
Yeah, it's working for me now.

**Comment by jaor** [comment]
okay, seems everybody is happy with this one now... closing, but, please, if i'm wrong and anybody is still having trouble, reopen it at will!
