### ISSUE TITLE
Weather stuck on <Waiting...>

### ISSUE THREAD

**Issue by sid-kap** [jaor/xmobar#234]
I'm running xmonad with xmobar on Ubuntu.
When I log in to my computer, the wifi takes a few seconds to connect.
Before my wifi connects, xmonad starts xmobar. Since the wifi is not yet connected, the weather plugin on xmobar displays `<Waiting...>`. Even after the wifi is connected, the display still says `<Waiting...>`. The only way that I can see the weather is by restarting xmobar after my internet connects.

**Comment by jaor** [comment]
have you tried to wait a bit? there's a timeout for retries in that
state, and the `<waiting>` should disappear after a minute or so (afk
right now, i cannot check the exact amount...)

**Comment by sid-kap** [comment]
Yep, I just tried it again. Even after 20 minutes, the `<waiting>` doesn't go away.

**Comment by jaor** [comment]
> Yep, I just tried it again. Even after 20 minutes, the <waiting> doesn't go away.

hmmm: what's your configuration? how often does the weather plugin check
for data? it's only after one refresh period that the display will be
updated (i.e., next time the monitor checks).  in my case, the period is
180000, so i have to wait 30 minutes until it's updated...  we could try
to throttle the check period in cases where no network is available, even
if that's a bit clumsy and inefficient, but it's not a trivial addition.

**Comment by mlopes** [comment]
Having the exact same issue, my installation is now about 1 week old, and still on waiting. Version 0.24 here.

**Comment by jaor** [comment]
On Fri, Dec 02 2016, Marco Lopes wrote:

> Having the exact same issue, my installation is now about 1 week old, and still on waiting. Version 0.24 here.

Please, upgrade to 0.24.3.  The URL that 0.24 used is no longer valid.

**Comment by djvs** [comment]
Upgraded to 24.4, still have this.

**Comment by jaor** [comment]
@djvs for how long does it say "Updating...", for ever? what's your weather station?

**Comment by djvs** [comment]
Forever, yep.  KNYC (though I tried a few).

**Comment by sahabi** [comment]
That happened to me too. The culprit was the the airport code (or station) I supplied in the .xmobarrc file didn't exist in the external resource. After I picked the correct code for my location the temperature appears nicely.
Catching this error by showing "station not found" instead of displaying waiting... would be nice.

**Comment by simzan** [comment]
I had the same issue. This is my solution:

In xmobarrc there are two entries you have to change:
1. One behind <Run Weather "KNYC">  and
2. one for the template at the end <| %KNYC% |>.

Then you have to kill xmobar by typing "killall xmobar" and press Mod+Q to restart it.
