### ISSUE TITLE
Unicode not supported in StdinReader despite with_utf8

### ISSUE THREAD

**Issue by wlritchi** [jaor/xmobar#235]
I am using xmobar with i3status using StdinReader. It produces lines that look like the following:

    (1 Mb/s 2.4 GHz 091%)</fc><fc=#586e75> | </fc>♪ 35%<fc=#586e75> | </fc>FULL 95.08% ()<fc=#586e75> | </fc>2015-06-08T00:23:07

Note the musical note (♪) character in the middle. xmobar is using the same font as urxvt (Fixed), which displays that character correctly. However, where xmobar should be displaying `♪`, it is instead displaying `"v`.

Edit: The same incorrect behaviour occurs if I put the character into the xmobar template string directly.

Version: 0.23.1
Compile flags: with_utf8 with_xft with_iwlib with_xpm
Installed from the [Arch Linux Package](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/xmobar).

**Comment by jaor** [comment]
urxvt synthetizes fonts that are not provided by the fontset (Fixed in
this case) on its own.  Do you see the note character in, say, xterm
with Fixed font?

**Comment by wlritchi** [comment]
The note character does appear correctly in xterm with the same font.

**Comment by jaor** [comment]
have you tried with other fonts? what's the actual "Fixed" font "real
name"? i cannot reproduce the issue with common fonts in my debian...

**Comment by wlritchi** [comment]
Figured out it was using a different encoding for the font (xft:fixed:style=semicondensed:size=7, but iso10646 in urxvt and something other than that in xmobar). Sorry for the erroneous report.
