### ISSUE TITLE
xmobar wrong position when overrideRedirect = False (OpenBox)

### ISSUE THREAD

**Issue by spodernet** [jaor/xmobar#236]
I'll attach a screenshot of the behaviour
http://i.imgur.com/Q64dN25.png

I'm using xmobar from the official repo
xmobarrc: http://pastebin.com/tR1t8g9W
Distro: Arch 64bit with OpenBox

I get this issue even with the sample configs provided here on github.
Have a nice day ;-)

**Comment by jaor** [comment]
this one should already be fixed.  please reopen as necessary otherwise.
