### ISSUE TITLE
BatteryP cannot retrieve data on battery

### ISSUE THREAD

**Issue by 0xfebytes** [jaor/xmobar#237]
[xmobarrc](http://pastebin.com/raw.php?i=n6phy6QL)
xmobar returns the following:
`xmobar: BAT1: runInteractiveProcess: runInteractiveProcess: exec: does not exist (No such file or directory)`

What's in /sys/class/power_supply

    > ls /sys/class/power_supply
    ACAD BAT1

xmobar version: 0.23.1

**Comment by skinner33** [comment]
Could you check which files are available inside the two directories (ACAD, BAT1)?

**Comment by 0xfebytes** [comment]
Here are the results:

    » ls -R ACAD                                                       [ Mon Jun 15 2015   14:46 ]
    ACAD:
    device  online  power  subsystem  type  uevent   
     
    ACAD/power:
    async                 runtime_suspended_time  wakeup_expire_count
    autosuspend_delay_ms  runtime_usage           wakeup_last_time_ms
    control               wakeup                  wakeup_max_time_ms
    runtime_active_kids   wakeup_abort_count             wakeup_prevent_sleep_time_ms
    runtime_active_time   wakeup_active           wakeup_total_time_ms
    runtime_enabled       wakeup_active_count
    runtime_status        wakeup_count

    » ls -R BAT1                                                                                                                                                                                             [ Mon Jun 15 2015 14:51 ]
    BAT1:
    alarm     capacity_level  charge_full_design  current_now  device        model_name  present         status     technology  uevent              voltage_now
    capacity  charge_full     charge_now          cycle_count  manufacturer  power           serial_number  subsystem  type        voltage_min_design
    
    BAT1/power:
    async  autosuspend_delay_ms  control  runtime_active_kids  runtime_active_time      runtime_enabled  runtime_status  runtime_suspended_time  runtime_usage

All of the files under BAT1 seem to be populating correctly (charge_now, capacity, status all have good information in them)

**Comment by skinner33** [comment]
Does the error message appear only after your system has returned from hibernate/suspend?
Or is this behavior always presented, i.e., even when you start xmobar from a terminal?

**Comment by 0xfebytes** [comment]
This behavior occurs when I start xmobar from the terminal.  I have not had a chance to experience this coming out of hibernate/suspend, as it has not yet worked normally.  I don't have a display manager set up, so I just startx from the terminal after login.

**Comment by skinner33** [comment]
Sorry for the late response.
I think you problem is not with BatteryP but with your template: the alias of BatteryP is %battery%. This is independent of the provided directory. If you would require multiple battery-monitors, you can use BatteryN to select an alias for the template.

**Comment by 0xfebytes** [comment]
Thank you for the help.  I misread the documentation on BatteryP.  I thought the alias was supposed to be the battery name as it is in /sys/class/power_supply.  After changing the alias to %battery% I am getting data.  This is good.  In the meantime I have been using cbatticon in trayer and it seems to have a bug when going from discharging to charging after sleep/hibernate.

**Comment by jaor** [comment]
since this one seems fixed, i'm closing it.
