### ISSUE TITLE
Volume args not parsed correctly

### ISSUE THREAD

**Issue by d125q** [jaor/xmobar#253]
The `Volume` plugin seems to be parsing `-O, -o, -C, -c` incorrectly.  It returns "unrecognized option."  I am running `xmobar` from [ArchHaskell](https://github.com/archhaskell/habs).

**Comment by jaor** [comment]
are you prefixing those options with `--`?

**Comment by d125q** [comment]
I am prefixing them with a single `-`.  Their long names (`--on`, `--off`, ...) do not work either.

**Comment by d125q** [comment]
Aha!  I got what you mean.  Sorry; indeed I was not prefixing them with `--`.
