### ISSUE TITLE
Weather plugin -- parse and exponse the "Weather:" line of the data

### ISSUE THREAD

**Issue by d125q** [jaor/xmobar#254]
Consider the following data (taken from current measurements at the "LIBP" station):

``` text
Bolzano, Italy (LIPB) 46-28N 011-20E 1461M
Jan 11, 2016 - 09:50 AM EST / 2016.01.11 1450 UTC
Wind: Variable at 2 MPH (2 KT):0
Visibility: less than 1 mile:0
Sky conditions: overcast
Weather: light rain; mist
Temperature: 42 F (6 C)
Dew Point: 42 F (6 C)
Relative Humidity: 100%
Pressure (altimeter): 29.26 in. Hg (0991 hPa)
ob: LIPB 111450Z VRB02KT 1500 -RA BR SCT001 OVC020 06/06 Q0991
cycle: 15
```

The `Weather:` line tells us what the current weather actually is like; however, the xmobar plugin does not expose it to the user.  Is there any reason why this is so?

**Comment by jaor** [comment]
there are lots of stations for which "Weather" is not available, and the
way the plugin is written it's a pain to account for optional fields,
but it wouldn't be that hard...

**Comment by d125q** [comment]
I believe that "Weather" is reported always, but if and only if [a specific weather condition is occurring](http://www.srh.noaa.gov/srh/dad/sfc/chapter4.pdf).

**Comment by jaor** [comment]
i've looked at a couple stations i use (LEBL and GEBL), and i've never
seen "Weather" in their reports, so i guess no specific weather
condition was ocurring.  in practical terms, that means that it's not
always reported...
