### ISSUE TITLE
Volume module not accepting arguments.

### ISSUE THREAD

**Issue by Quardah** [jaor/xmobar#256]
Hello

using the following in .xmobarrc gives me "unrecognized option `-C`"

	-- output volume :
	, Run Volume "default" "Master" [ "--template" , "Vol: <volume>% <status>"
                 , "-c"   , "darkred"
			     , "-C"   , "darkgreen"
			     ] 4

If i remove the "-C" part, the "-c" part is accepted but the color is unchanged.

Using "--offc" and "--onc" instead, xmobar outputs that BOTH options are unrecognized.

Maybe the doc (http://projects.haskell.org/xmobar/#volume-mixer-element-args-refreshrate) is out of date.

Thank you.

**Comment by jaor** [comment]
for monitor-specific switches, you need to use "--" as a separator:

       , Run Volume "default" "Master" [ "--template" , "Vol: <volume>% <status>"
                                         , "-c"   , "darkred"
                                         . "--", "-C"   , "darkgreen"
                                        ] 4

**Comment by Quardah** [comment]
Thank you for the fast reponse.

Your example is not working, i think you added a "." in there and meant to add "," instead (third line, first character).

using this code :

	, Run Volume "default" "Master" [ "--template" , "Vol: <volume>% <status>",
			     "--", "-c" , "darkred" ,
			     "--", "-C" , "darkgreen"
			     ] 4

The darkred color works but not the darkgreen.

using this code :

	, Run Volume "default" "Master" [ "--template" , "Vol: <volume>% <status>",
			     "-c" , "darkred" ,
			     "--", "-C" , "darkgreen"
			     ] 4

The darkgreen color works but not the darkred.

Can i make both work?

**Comment by jaor** [comment]
you need use only one "--"; after that, all the options are considered
monitor-specific ones.  so, this should work:

     "--", "-c", "darkred", "-C", "darkgreen"

does that help?

**Comment by Quardah** [comment]
Yes it works perfect many thanks for your assistance. I believed it was a bug but i simply didn't know the trick.

Thanks again.
