### ISSUE TITLE
Creating plugin should not require building from source

### ISSUE THREAD

**Issue by sid-kap** [jaor/xmobar#258]
Hi,

I just looked through the new plugin infrastructure, and it looks amazing! I'm glad that xmobar is finally making it easier to create new plugins.

However, I'm concerned about the plugin architecture. Why should a user have to build xmobar from source and modify `runnableTypes` in `Config.hs` in order to run a plugin?

I propose that we promote `.xmobarrc` to a real Haskell file, and allow users to define instances of `Exec` in that file. They can then reference those custom plugins in their config file. If we do this, then users will only need to restart xmobar when they update the plugins, rather than having to re-build xmobar. In addition, users will not need to download the source of xmobar in order to customize it.

In this proposal, `.xmobarrc` would be compiled and run similar to how XMonad's config file is run. 

Does this sound like a good idea?

**Comment by skinner33** [comment]
I think you misunderstood the plugin architecture: modifying `runnableTypes` is only required if you add a new plugin to xmobar. As long as it is included in the version of xmobar you build resp. your distribution provides, you can just add it in your configuration.

Regarding making .xmobarrc similar to xmonad's approach: I think that this is proposed in #108

**Comment by sid-kap** [comment]
Thanks for your reply!

As I understand it, it seems like in order to create a plugin, the user must 

1. Download the source of xmobar
2. Add a plugin to src/Plugins
3. Update `runnableTypes` in src/Config.hs
4. Rebuild xmobar

Did I misunderstand the plugin architecture?

**Comment by sid-kap** [comment]
I suppose we can close this issue, since this topic is already discussed in #108. Sorry for the noise!

**Comment by skinner33** [comment]
Yes, that is correct. On some level, having the source available is required for the compiler to check that the plugin adheres to the interfaces required for a plugin anyway.

While the scenario, I think, you shooting at, has a major advantage for a plugin developer, a common user, on the other hand, would need a 200Mb+ ghc for simple toolbar to run ;)
