### ISSUE TITLE
xft fonts with a hyphen in their name not loaded

### ISSUE THREAD

**Issue by real-milos** [jaor/xmobar#261]
I tried this with multiple fonts (for example `WebHostingHub\-Glyphs:style=Regular`), none of them worked. I tried not escaping, escaping and double escaping the hyphen, all to no avail.

How to confirm? Run `fc-list | grep \\\\-` to list all fonts containing a hyphen in their name and try to see if you can load any of them in xmobar.

**Comment by jaor** [comment]
moved to https://codeberg.org/jao/xmobar/issues/261
