### ISSUE TITLE
Force refresh using kill signals (or otherwise)

### ISSUE THREAD

**Issue by camilstaps** [jaor/xmobar#262]
For example, with i3status has the possibility to force-refresh the status bar with `kill -10 $(pidof i3status)`. Does xmobar have this functionality already somehow? If not, can it be added?

I now have a `Run Volume "default" "Master" [] 10` in my config, so when I change the volume it takes up to a second before xmobar updates this. I would like to be able to map the volume key to something like:

    amixer sset Master 1%+ && kill -10 `pidof xmobar`

To have the bar update directly. This would also mean that the RefreshRate in the config can be 0, so that it is only updated when needed.

Ideally, there would also be a way to specify that only the volume needs to be refreshed, but I guess that would be harder to build in.

**Comment by jaor** [comment]
in principle we have this:

  http://projects.haskell.org/xmobar/#signal-handling

and, if you use DBus, this:

  http://projects.haskell.org/xmobar/#the-dbus-interface

is none of them useful?

**Comment by camilstaps** [comment]
That will work, thanks.
