### ISSUE TITLE
Kbd plugin does not work on ubuntu 15.10

### ISSUE THREAD

**Issue by pasja** [jaor/xmobar#263]
Hello,

When i configure the Kbd plugin from the manual, namely: `Run Kbd [("us(dvorak)", "DV"), ("us", "US")]` and restart xmonad to read the new config, i see `Updating...` in the status bar.
In the `.xsession-errors` file i found the following error message:

`xmobar: kbd: runInteractiveProcess: runInteractiveProcess: exec: does not exist (No such file or directory)`

I have skimmed through the code, sadly my X and Haskell knowledge is not deep enough to discover the issue. I suspect that some foreign function call did not succeed. I have the `/usr/include/X11/XKBlib.h` file from `libx11-dev` package installed.

Xmonad and xmobar are from the ubuntu 15.10 repository.

**Comment by skinner33** [comment]
Hey,

I'll try to get around to test this on the weekend in a VM. Could you please provide your xmobarrc?

Thanks

**Comment by pasja** [comment]
Hello,

Thanks for the quick answer! 
I have attached my [xmobarrc.txt](https://github.com/jaor/xmobar/files/217311/xmobarrc.txt)

**Comment by skinner33** [comment]
Hey,

I just checked your config and the commands list ist closed there right after BatteryP. Thus kbd is not included as a command, which leads to the error message you see above.

Hope that helps :)

**Comment by pasja** [comment]
Hello, 

Sorry for the rookie mistake.
After correcting my configuration, the layout display is working properly.
