### ISSUE TITLE
Sane defaults for -L and -H in Batt.hs

### ISSUE THREAD

**Issue by d125q** [jaor/xmobar#265]
Looking at [how the thresholds are compared](https://github.com/jaor/xmobar/blob/196a7bcd8145aece2a2c6cae5b76402c69c4fac0/src/Plugins/Monitors/Batt.hs#L222), the current defaults of 
```haskell
lowThreshold = -12
highThreshold = -10
```
make no sense.  What would make sense is to have
```haskell
lowThreshold = 10
highThreshold = 12
```
instead.

**Comment by jaor** [comment]
indeed: should be fixed by e9ce98d, thanks!
