### ISSUE TITLE
Length limitation in template?

### ISSUE THREAD

**Issue by haasn** [jaor/xmobar#267]
I display the currently playing song in xmobar, which can get very long for some songs. Unfortunately, when that happens, xmobar seems to prefer the “right” half of the screen over the “left” half, and since the MPD info is in my right half it ends up blocking out everything else.

I would love the ability to specify a maximum length limit for my MPD template, so it would simply truncate the rest of the song when it gets too long.

**Comment by jaor** [comment]
you can already do that with either `-M` or `-W` in your template.
see http://projects.haskell.org/xmobar/#default-monitor-arguments

doesn't that work for you?

**Comment by haasn** [comment]
Ah, I missed that one! Works like a charm, thanks.
