### ISSUE TITLE
Is compilation on GHC 7.6 supported?

### ISSUE THREAD

**Issue by jpalus** [jaor/xmobar#269]
It appears new release requires newer GHC versions for few minor things:
* <$> assumed to be in scope in Environment.hs, Plugins/PipeReader.hs, Plugins/MarqueePipeReader.hs (no import of Control.Applicative ((<$>)))
* Plugins/Monitors/Batt.hs depends on missing sortOn in Data.List

Would it be possible to correct above or GHC 7.6 is considered unsupported?

**Comment by jaor** [comment]
importing Control.Applicative is trivial... does ghc 7.6's Data.List
have sortBy?

**Comment by jpalus** [comment]
Yes, please check:
https://hackage.haskell.org/package/base-4.6.0.0/docs/Data-List.html

Basically 7.6 shipped with base 4.6, 7.8 with base 4.7 and 7.10 ships with base 4.8. sortOn has annotation _Since: 4.8.0.0_ so looks like only 7.10 is supported atm.

**Comment by jaor** [comment]
could you please try whether 5e783dc (just committed) fixes the
problems? thanks!

**Comment by jpalus** [comment]
Works great. Thanks!

**Comment by jaor** [comment]
i've just released 0.24.1 with these changes. thanks!
