### ISSUE TITLE
Weather Plugin no longer works

### ISSUE THREAD

**Issue by jt512** [jaor/xmobar#270]
Apparently, the web page from which the Weather plugin obtains its data is no longer functioning, so the Weather plugin no longer works.

**Comment by octoploid** [comment]
The following patch works for me:
`
diff --git a/src/Plugins/Monitors/Weather.hs b/src/Plugins/Monitors/Weather.hs
index a25005f76c0b..5a9292d788c0 100644
--- a/src/Plugins/Monitors/Weather.hs
+++ b/src/Plugins/Monitors/Weather.hs
@@ -183,7 +183,7 @@ parseData =
        return [WI st ss y m d h w v sk tC tF dC dF rh p]
 
 defUrl :: String
-defUrl = "http://weather.noaa.gov/pub/data/observations/metar/decoded/"
+defUrl = "http://tgftp.nws.noaa.gov/data/observations/metar/decoded/"
 
 stationUrl :: String -> String
 stationUrl station = defUrl ++ station ++ ".TXT"

`

**Comment by jaor** [comment]
works for me too.  patch uploaded, thanks a lot!

**Comment by KungFuJesus** [comment]
I'm still getting "N/A" for my weather stations (KCVG & KLUK).

**Comment by jaor** [comment]
the files are there, e.g.:

http://tgftp.nws.noaa.gov/data/observations/metar/decoded/KCVG.TXT

was the plugin working for previous versions of xmobar?

**Comment by jaor** [comment]
adam, KCVG and KLUK work just fine for me... are you able to to open the
url above? what's your configuration?

**Comment by KungFuJesus** [comment]
The URLs work for me, xmobar is what displays n/a. I'm using .24.2 on Arch,
with a pretty basic config. On my phone but this is a screenshot of my
current config:

**Comment by jaor** [comment]
you didn't sent the screenshot, it seems.  fwiw, i still can see the two
stations fine here.

**Comment by jt512** [comment]
@KungFuJesus:

The current Arch package is not patched.  You'll need to apply the patch yourself for now.

**Comment by jl2035** [comment]
Any ideas why this doesn't work on Ubuntu? It just says "<Waiting...>" and I never saw any weather information.

Also I think I don't need this feature. Is it possible to disable weather completely?

**Comment by jaor** [comment]
On Thu, Apr 05 2018, jl2035 wrote:

> Any ideas why this doesn't work on Ubuntu? It just says "<Waiting...>"
> and I never saw any weather information.

What's xmobar's version in ubuntu? The previous weather URL got changed
a year ago or so, and it won't work if you're not on one of the latest
releases.

> Also I think I don't need this feature. Is it possible to disable
> weather completely?

Well, if you don't use it in your configuration, xmobar won't make any
attempt to use it, so it's as good as disabled.  That said, if you want
to compile xmobar with weather disabled, you can use the compile flag
`with_weather`: see the documentation here
https://github.com/jaor/xmobar#optional-features

**Comment by jl2035** [comment]
Hi @jaor 

> What's xmobar's version in ubuntu?

In the terminal output I pasted... it says the version is 0.23.1. Too old?

> Well, if you don't use it in your configuration, xmobar won't make any attempt to use it, so it's as good as disabled. That said, if you want to compile xmobar with weather disabled, you can use the compile flag `with_weather`: see the documentation here https://github.com/jaor/xmobar#optional-features

I don't understand this (feeling a bit stupid). I installed via apt-get. How do I "not use weather in my configuration"? And what do you mean by 'compile'. Do I need to get the source code, compile it and than somehow configure it up for my environment. I would probably fail somewhere on this journey. :(

**Comment by jaor** [comment]
On Thu, Apr 05 2018, jl2035 wrote:

> Hi @jaor
>
>     What's xmobar's version in ubuntu?
>    
> In the terminal output I pasted... it says the version is 0.23.1. Too old?

yes, way too old.  you'd need a newer version.

>     Well, if you don't use it in your configuration, xmobar won't make
>     any attempt to use it, so it's as good as disabled. That said, if
>     you want to compile xmobar with weather disabled, you can use the
>     compile flag with_weather: see the documentation here
>     https://github.com/jaor/xmobar#optional-features
>    
> I don't understand this (feeling a bit stupid). I installed via
> apt-get. How do I "not use weather in my configuration"? And what do
> you mean by 'compile'. Do I need to get the source code, compile it
> and than somehow configure it up for my environment. I would probably
> fail somewhere on this journey. :(

yes, that was only in case you were compiling xmobar yourself.  in that
case, one can compile xmobar without weather support.

what i meant is that, if you use a precompiled xmobar, you can configure
it so that it doesn't show (or try to show) weather at all, which is as
good as "not support it".

you can start xmobar providing a configuration file.  in that file, you
tell xmobar what to show.  here's an example:
https://github.com/jaor/xmobar/blob/master/samples/xmobar.config

HTH,
jao
-- 
A ship in port is safe; but that is not what ships are built
for. -Grace Hopper (1906-1992)
