### ISSUE TITLE
When is a monitor not available?

### ISSUE THREAD

**Issue by Markus00000** [jaor/xmobar#272]
> -x _string_ N/A string 
> - String to be used when the monitor is not available

I expected to see the N/A string for the respective monitors in cases such as:
- Battery is removed (instead battery charge is shown as 0)
- WiFi is disabled by hardware switch (instead link quality is shown as 0)
- Ethernet cable is disconnected (instead monitor disappears)

Is the N/A string not xmobar’s equivalent to i3’s `format_down`?

_xmobar 0.24_

**Comment by jaor** [comment]
there is no homogenous way of providing this info, each monitor decides what to consider "down".
