### ISSUE TITLE
Weather plugin URL obsolete

### ISSUE THREAD

**Issue by travis-swanston** [jaor/xmobar#274]
I haven't taken the time to look into this in depth, but it appears that the URL used by the weather plugin is now obsolete. For more information:

    http://www.nws.noaa.gov/om/notification/scn16-16wngccb.htm

**Comment by jaor** [comment]
we are already using http://tgftp.nws.noaa.gov/data/observations/metar/decoded/, which seems to be listed in the alternative links in the page you point above...

**Comment by travis-swanston** [comment]
Whoops. I don't know how I missed that. Thanks for responding, and my apologies for taking your time.

**Comment by jaor** [comment]
no problem! thanks.
