### ISSUE TITLE
Weather for KBWI stopped working.

### ISSUE THREAD

**Issue by JoePython1** [jaor/xmobar#275]
I currently use Ubuntu 14.04
My .xmobarrc looks like follows. KBWI information does not show anymore.

Config { font = "-*-Fixed-Bold-R-Normal-*-14-*-*-*-*-*-*-*"
, bgColor = "black"
, fgColor = "grey"
, position = Top
, lowerOnStart = True
, commands = [ Run Weather "KBWI" ["-t","<station>: <tempF>F","-L","18","-H","25","--normal","green","--high","red","--low","lightblue"] 36000
             , Run Network "eth0" ["-L","0","-H","32","--normal","green","--high","red"] 10
             , Run Network "eth1" ["-L","0","-H","32","--normal","green","--high","red"] 10
             , Run Cpu ["-L","3","-H","50","--normal","green","--high","red"] 10
             , Run Memory ["-t","Mem: <usedratio>%"] 10
             , Run Swap [ ] 10
             , Run Date "%a %b %_d %Y %H:%M:%S" "date" 10
             ]
, sepChar = "%"
, alignSep = "}{"
, template = "%cpu% | %memory% * %swap% | %eth1% }{ %KBWI% | <fc=#ee9a00>%date%</fc>"
}

**Comment by jaor** [comment]
what version of xmobar are you using? we fixed a problem with weather in 0.24.2.

**Comment by JoePython1** [comment]
xmobar 0.23.1
 (C) 2007 - 2010 Andrea Rossato 
 (C) 2010 - 2014 Jose A Ortega Ruiz
 <xmobar@projects.haskell.org>

**Comment by jaor** [comment]
the URL of the weather plugin has been updated.  please upgrade to
xmobar 0.24.2 and your problem will be solved :)

**Comment by jaor** [comment]
@JoePython1 i'm closing this bug, since i'm pretty sure we've solved it in 0.24.2, but please do reopen it if you encounter problems with that version.
