### ISSUE TITLE
Weather service discontinued

### ISSUE THREAD

**Issue by joehealy** [jaor/xmobar#279]
The weather service no longer works. This is because NOAA has discontinued the service [1,2]

Any ideas on replacement services.

[1] http://weather.noaa.gov/pub/data/observations/metar/decoded/YMML.TXT
[2] http://www.nws.noaa.gov/om/notification/scn16-16wngccb.htm

**Comment by jaor** [comment]
this is fixed in 0.24.3 (actually, it was fixed in 0.24.2).

**Comment by jaor** [comment]
@joehealy closing.  please reopen if things don't work for you in 0.24.3.

**Comment by joehealy** [comment]
Thanks for that - working nicely following upgrade
