### ISSUE TITLE
Character backgrounds not transparent when alpha is set

### ISSUE THREAD

**Issue by fleutot** [jaor/xmobar#280]
When setting the alpha of my xmobar, the background behind characters is solid black (default bg, visible workspaces bg, ...). Background with no character on top works as expected.

These [screenshots](http://i.imgur.com/SrwfngM.png) illustrate both with and without alpha.

My version of xmobar: 0.23.1
NVidia Quadro K2000 (nouveau driver)
 X.Org X Server 1.17.2
Ubuntu 15.10

Verified by "ongy" on IRC with 0.24.3, they saw the issue both on their gtx580 and on iGPU. Xorg 1.18.4 on the iGPU. Arch.

User "kmicu" on IRC could not see the issue, with modesetting driver / intel iGPU /
 xmobar 0.24.3|0.24.4 / NixOS / Xorg 1.18.3

Trying:

`xmobar -c '[]' --alpha=20 --template="foo"`

with no trayer and no compton still displays the issue.

**Comment by fleutot** [comment]
My font definition in .xmobarrc was:

    font = "-*-terminus-*-r-*-*-12-*-*-*-*-*-*-*"

After changing it to:

    font = "xft:terminus:size=9"

The transparency started to partly work!

What doesn't work yet is the differing background for active and visible workspaces. For these, the same background color is in use, instead of the ones I define in xmonad.hs, ppCurrent and ppVisible.

**Comment by fleutot** [comment]
From user "kmicu" on IRC:

> <kmicu> By playing with ‘xmobar --template="<fc=yellow,#ee9aee>foo</fc>   bar" --alpha=255’ 
> I see that background color is only visible when alpha = 255 and it’s not visible when it’s 254.

**Comment by jaor** [comment]
@fleutot sorry for the delay commenting here.  as you've discovered, transparency is only really supported for xft fonts.  i'll take a look at the issue as soon as i find a moment!

**Comment by methuselah-0** [comment]
Is it possible to get real transparency also or would that be a feature request? I'm using xcompmgr and xwinwrap for using an xscreensaver as background but the --alpha setting would render any background as set by feh instead of a running xscreensaver.

**Comment by jaor** [comment]
@methuselah-0 it's more of a feature request.  transparency support is very limited and implemented in an adhoc way.  originally, it was contribute code and my understanding of how it works is not good: i'd need to study it carefully (together with the relevant X11 lib docs) to implement the real thing.

**Comment by emptyflask** [comment]
Bumping this thread since I just ran into this too. Setting a background color on the CPU vbars works, as long as the global alpha value is 255. Any transparency will cause the backgrounds to be removed, even with xft fonts specified.

Screenshots:
[No transparency, working background](https://imgur.com/gAoMm5M)
[Transparency enabled, no background](https://imgur.com/zKTbSKD)

**Comment by jaor** [comment]
well, the cpu vbars are text, and their background is the background of a text label.  alpha affects text backgrounds and does away with them... if it's not respecting the alpha level when doing that (it's difficult for me to tell from the screenshots), then yes, it's a bug.  if what you want, on the other hand, is to keep the original background, an alternative is to use a set of icons for the vars: that's what i do for instance here:  https://gitlab.com/jaor/xmobar-config/-/blob/master/src/lib/Monitors.hs#L61 using simple icons like these: https://gitlab.com/jaor/xmobar-config/-/tree/master/icons.

**Comment by emptyflask** [comment]
Sorry, I should have cropped those images.
![image](https://user-images.githubusercontent.com/28287/118743376-dd361600-b817-11eb-91a3-9d422fcac3f4.png)
![image](https://user-images.githubusercontent.com/28287/118743707-7bc27700-b818-11eb-8194-06576ab727c6.png)

You're right, setting alpha does away with the backgrounds. I noticed those vbars are made using block characters, so that makes sense. I like the XPM icon workaround, thanks for the suggestion.

**Comment by emptyflask** [comment]
I modified the script a bit and got it running under NixOS:
https://gist.github.com/emptyflask/abd3cfb6261256b1dcfec2dd29386708

**Comment by jaor** [comment]
> I modified the script a bit and got it running under NixOS:
> https://gist.github.com/emptyflask/abd3cfb6261256b1dcfec2dd29386708

very nice! thanks for sharing.
