### ISSUE TITLE
Weather service no longer available.

### ISSUE THREAD

**Issue by tiuno** [jaor/xmobar#282]
According to the service provider, http://weather.noaa.gov, they no longer support the service used for the weather in xmobar. Is it possible to correct this inconvenience ?

**Comment by jaor** [comment]
this was fixed in 0.24.2.  what version of xmobar are yo using?

**Comment by tiuno** [comment]
Hello,

	I see, sorry for the inconvenience. I'm using debian's package which seems to be 0.22.1. I will update my xmobar distribution. Thanks for the quick reply.

Regards,


Colin G.

**Comment by JoePython1** [comment]
Weather plugin stopped working again:

xmobar -B white -a right -F blue -t '%LIPB%' -c '[Run Weather "LIPB" [] 36000]'
$ xmobar -V
Fields missing from config defaulted: additionalFonts,border,borderColor,textOffset,iconOffset,allDesktops,overrideRedirect,pickBroadest,hideOnStart,persistent,iconRoot,alpha
xmobar 0.24.2
 (C) 2007 - 2010 Andrea Rossato 
 (C) 2010 - 2014 Jose A Ortega Ruiz
 <xmobar@projects.haskell.org>

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the License for more details.

**Comment by jaor** [comment]
this is fixed in master, you need to recompile with with_counduits, because the new url is https.  please see #378
