### ISSUE TITLE
Battery plugin not showing both batteries

### ISSUE THREAD

**Issue by rig0rmortis** [jaor/xmobar#283]
I'm on a ThinkPad T460s (2 batteries), I'm running `xmobar` version `0.24.3-2` from the ArchLinux repositories. I've tried explicitly using `BatteryP` with `[BAT0, BAT1]` as an argument, and also just `Battery` but once my battery is fully charged I see my status as `Charged` and then it jumps down to `50%`, so it doesn't seem to be reading the second battery.

Note that if I charge my battery up to say 70%, it correctly displays this, and also correctly shows discharging information. The problem occurs only when my battery is fully charged and the power cable is pulled out. I'm not sure if hibernation might have something to do with this either...

Here's output from acpi:
```
Battery0: Full, 100%
Battery1: Discharging, 31%, 01:08:20 remaining
```

Below is the battery section from my `.xmobarrc` (note that I have also tried `Run Battery` without specifying the batteries explicitly) 
```
, Run BatteryP    ["BAT0", "BAT1"]
                       [ "--template", "Batt: <acstatus>"
                       , "--Low"       , "10"    -- units: %
                       , "--High"      , "60"    -- units: %
                       , "--" -- battery specific options
                           , "-o" , "<left>% (<timeleft>)"
                           , "-O" , "Charging <left>%"
                           , "-i" , "Charged"
                         ] 50
```

Have I just misconfigured my battery plugin or am I encountering a similar issue?

Thanks

**Comment by jaor** [comment]
what's the acpi output when the problem happens?

**Comment by rig0rmortis** [comment]
The acpi output above is while the problem happens

**Comment by rig0rmortis** [comment]
I charged it a bit from the above status, and ran `acpi` again and I do actually get `Unknown` for Battery 0

Output:
```
Battery 0: Unknown, 99%
Battery 1: Discharging, 64%, 02:03:16 remaining
```

Also output from when I plug ac back in:
```
Battery 0: Unknown, 99%
Battery 1: Charging, 63%, 00:18:08 until charged
```

`xmobar` currently shows `Batt: Charging 81%`

**Comment by jaor** [comment]
i guess the unknown status is confusing xmobar's monitor....

**Comment by rig0rmortis** [comment]
It seems like when `Battery 1` drained down to `0%`, and `Battery 0` kicked in it discharged to `99%` and that's when `Battery 0` changed from `Full` to `Unknown`

**Comment by rig0rmortis** [comment]
Still getting this issue, anything specific I should try?

**Comment by jaor** [comment]
well, i think it's a problem with the system reporting the battery as
unknown when it's empty. isn't that a bug reportable somewhere? we can
try to workaround it in xmobar, but that needs (somewhat ugly) code, so
a bit of time :)

**Comment by jaor** [comment]
@rig0rmortis so, i was re-reading the thread to try to understand the issue, and i think i actually don't :) so, in one of your messages you say that Bat0 is Unknown/99% and Bat1 is Charging 63%. and that then xmobar shows 81%, which is the average of 99 and 63.  but that's correct, isn't it? what would you expect? when there's more than one battery, what xmobar does is averaging over them...

**Comment by rig0rmortis** [comment]
Hey, sorry for the late response.

So the Unknown/99% happens sometimes, the main issue is as follows:

Plug in to AC, charge fully. Xmobar shows "Charged"
Unplug AC, Xmobar still shows "Charged"
Let battery discharge a while, `acpi` shows:
```
Battery0: Discharging, 93%,02:48:54 remaining
Battery1: Full, 100%
```
But xmobar still shows "Charged"

**Comment by jaor** [comment]
On Sat, Dec 17 2016, insert name here wrote:

> So the Unknown/99% happens sometimes, the main issue is as follows:
>
> Plug in to AC, charge fully. Xmobar shows "Charged"
> Unplug AC, Xmobar still shows "Charged"
> Let battery discharge a while, acpi shows:
>
> Battery0: Discharging, 93%,02:48:54 remaining
> Battery1: Full, 100%
>
> But xmobar still shows "Charged"

oh, then it's not a problem with the Unknown state?  i totally
misunderstood then... does this bogus Charged state long for ever or
does it eventually go back to normal? if the states of the batteries are
Discharging and Full there's really no reason why we shouldn't be
reporting things correctly...

**Comment by rig0rmortis** [comment]
It goes back to normal when the battery gets down to 50%.

I just changed my `xmobarrc` to the following:
```
"-o", "<left>", "-O", "<left>", "-i", "<left>" 
```
and now I'm correctly displaying my battery percentage as `87`. It seems like the issue is it doesn't detect a change from `charged` state to the `discharging` state... I wonder if it has anything to do with `acpi` suspend/resume?

**Comment by jaor** [comment]
On Sat, Dec 17 2016, insert name here wrote:

> It goes back to normal when the battery gets down to 50%.
>
> I just changed my xmobarrc to the following:
>
> "-o", "<left>", "-O", "<left>", "-i", "<left>" 

hmmm, so does that mean that this format always work or that it started
working just because you restarted xmobar?

> and now I'm correctly displaying my battery percentage as 87. It seems
> like the issue is it doesn't detect a change from charged state to the
> discharging state... I wonder if it has anything to do with acpi
> suspend/ resume?

i don't think so... xmobar is periodically reading the virtual files in
/sys/class/power_supply, which is the same data read by acpi, so if the
latter is correct, we should be correct too.  and if it was the xmobar
process getting in a bogus, non-refreshing state after wake-up, my
expectation is that that would affect many other monitors, not just
battery...

**Comment by rig0rmortis** [comment]
That format always works, I'm fairly certain this had nothing to do with restarting xmobar (I tried doing that before with different configurations)

Yeah that makes sense. I think this is probably an issue with acpi somehow and not xmobar. I appreciate the help! I'll try to dig in further to see what's going wrong. Going to close this now.

**Comment by ghormoon** [comment]
Hi, I have the same with thinkpad 470s, but I think it just misinterprets the states, as if I use BatteryN, they display fine. the problem is, that first only one battery drains, so with two BatteryN displays, I have one as "On", other on "Discharging", but if I use BatteryP, the total power is averaged, but the status is "On". maybe there's something like "if at least one battery "on", then "on", else "discharging"?
