### ISSUE TITLE
xmobar hides behind windows - again

### ISSUE THREAD

**Issue by TLINDEN** [jaor/xmobar#294]
Hi,

this is the same behavior as in issue #249 (but on all workspaces). It worked for me for a couple of years, but now I upgraded everything and it doesn't behave as expected anymore. Versions installed:

- FreeBSD 10.3
- ghc 7.10.2_1 (FreeBSD Ports)
- cabal 1.22.6.0 (FreeBSD Ports)
- xmonad 0.13 (using cabal install)
- xmobar 0.24.3 (using cabal install)

It doesnt matter to what values I set `lowerOnStart` and `overrideRedirect`.

[My xmonad.hs](https://gist.github.com/TLINDEN/5a692ffe422f6e3eb416d5d8f69d3abc)
[My .xmobarrc](https://gist.github.com/TLINDEN/2866d5504ae6140f88aa79568d2859cb)

**Comment by svenkeidel** [comment]
Yes, I can confirm this. Same xmonad and xmobar version, but on NixOS.

**Comment by svenkeidel** [comment]
@TLINDEN, I think it is an xmonad related issue. I added the `docks` command to my xmonad config like here https://github.com/womfoo/dotfiles/commit/6171c560dbe8dc5be03500ab7b6692a6294aee47 and now it works again.

**Comment by TLINDEN** [comment]
@svenkeidel, thanks a lot! Works again for me too.

**Comment by jaor** [comment]
yes, docks is new in recent xmonad, and should be the answer to this problem.  i'm closing the issue, but please feel free to reopen it if there's still any problem. thanks!

**Comment by vatrat** [comment]
Wow, I've had this issue forever and that fixed it

**Comment by evenlis** [comment]
@svenkeidel thx a ton! This issue started happening out of the blue, this fixed it
