### ISSUE TITLE
Dynamic images in XMobar

### ISSUE THREAD

**Issue by Haron-Prime** [jaor/xmobar#297]
Well, I've tried to use this code to display dynamic image
`
#!/usr/bin/env zsh
echo "<icon=/path/to/my/image.xpm/>"
exit 0
`
in **xmobarrc**
`
commands = [
                      ......
                      , Run Com "MyScript" [] "" 600
                      ......
                      ]
template = "%MyScript%"
`
The image displays normally  but it's not getting changed when original image changes. 
I'm taking this image from another program and converting it to xpm on the fly. 
Is it possible to get xmobar showing changed image innthe same time as changes applied?
Thx.

**Comment by nwf** [comment]
xmobar has an image cache internally to avoid reloading every redraw.  I ran into the same thing in #286 and was never able to get a good workaround.

**Comment by jaor** [comment]
yes, the image cache should take into account modification times, so i am marking this as a bug.

**Comment by jaor** [comment]
moved to https://codeberg.org/jao/xmobar/issues/297
