### ISSUE TITLE
Volume calculation seems inaccurate.

### ISSUE THREAD

**Issue by crocket** [jaor/xmobar#300]
According to alsamixer, -64.0dB is 0%, -16.0dB is 50%, and 0.0dB is 100%.
[Plugins.Monitors.Volume.percent](https://github.com/jaor/xmobar/blob/9c2a16fef60934290bb79d3bafc147ddea235a9f/src/Plugins/Monitors/Volume.hs#L69-L73) calculates the volume at 50% as `(-16 - (-64)) / (0 - (-64))=0.75`

The volume should be displayed as 50%, but it is displayed as 75%.
75% is very far from 50%.

**Comment by skinner33** [comment]
As dB is logarithm, this is definitely a bug. Although, one that can be fixed easily.

**Comment by jaor** [comment]
when i run this monitor, the figure reported by alsamixer for the volume
and the one i see in xmobar's `<volume>` value are always the same.  i
might be mistaken, but i'd say that the hi, lo, val values reported by
the mixer driver are not in dB: see line 125 of Volume.hs how the driver
is actually providing a *fourth* value in dBs, which is not used with
`percent`.

am i missing something?

**Comment by crocket** [comment]
Perhaps, the units depend on system configuration, but I'm not sure, yet.

**Comment by crocket** [comment]
I just compiled and executed

```
module Main where

import Sound.ALSA.Mixer
import qualified Sound.ALSA.Exception as AE
import Control.Monad (liftM2, mplus)
import Data.Traversable (sequenceA)

liftMaybe :: Maybe (IO (a,b)) -> IO (Maybe a, Maybe b)
liftMaybe = fmap (liftM2 (,) (fmap fst) (fmap snd)) . sequenceA

volumeControl :: Maybe Control -> Maybe Volume
volumeControl c = (playback . volume =<< c)
  `mplus` (capture . volume =<< c)
  `mplus` (common . volume =<< c)

switchControl :: Maybe Control -> Maybe Switch
switchControl c = (playback . switch =<< c)
  `mplus` (capture . switch =<< c)
  `mplus` (common . switch =<< c)

channel v r = AE.catch (getChannel FrontLeft v) (const $ return $ Just r)

getVal :: Maybe Volume -> IO (Maybe Integer)
getVal Nothing = return Nothing
getVal (Just v) = channel (value v) 0

getSw :: Maybe Switch -> IO (Maybe Bool)
getSw Nothing = return Nothing
getSw (Just s) = channel s False

getDB :: Maybe Volume -> IO (Maybe Integer)
getDB Nothing = return Nothing
getDB (Just v) = channel (dB v) 0

main :: IO ()
main = do
  withMixer "default" $ \mixer -> do
    control <- getControlByName mixer "Master"
    (lo, hi) <-liftMaybe $ getRange <$> volumeControl control
    val <- getVal $ volumeControl control
    db <- getDB $ volumeControl control
    sw <- getSw $ switchControl control
    print lo
    print hi
    print val
    print db
    print sw
```

This prints

```
*Main> main
Just 0
Just 64
Just 48
Just (-1600)
Just True
```

**Comment by jaor** [comment]
On Fri, Apr 28 2017, crocket wrote:

> main :: IO ()
> main = do
>   withMixer "default" $ \mixer -> do
>     control <- getControlByName mixer "Master"
>     (lo, hi) <-liftMaybe $ getRange <$> volumeControl control
>     val <- getVal $ volumeControl control
>     db <- getDB $ volumeControl control
>     sw <- getSw $ switchControl control
>     print lo
>     print hi
>     print val
>     print db
>     print sw
>
> This prints
>
> *Main> main
> Just 0
> Just 64
> Just 48

so, those numbers are not dBs for sure.  what is alsamixer saying in
this case for volume?

**Comment by crocket** [comment]
> what is alsamixer saying in this case for volume?

50%.

I just searched the internet. It seems alsamixer uses human volume mapping.

**Comment by jaor** [comment]
On Fri, Apr 28 2017, crocket wrote:

>     what is alsamixer saying in this case for volume?
>    
> 50%.
>
> I just searched the internet. It seems alsamixer uses human volume mapping.

i don't know what that is, but i cannot reproduce what you see.  in my
system (debian unstable), when alsamixer says 50%, i see xmobar
reporting 50 as its value, so we both compute the same thing.

what version of libasound2-dev have you installed? mine is 1.1.3.

**Comment by crocket** [comment]
On my gentoo system, `media-libs/alsa-lib-1.1.2` owns `/usr/lib64/libasound.so.2.0.0`

**Comment by crocket** [comment]
@jaor Does `amixer get Master` say 50%, too?

**Comment by jaor** [comment]
On Fri, Apr 28 2017, crocket wrote:

> @jaor Does amixer get Master say 50%, too?

yes... i am using pulseaudio, maybe it is interferring somehow?

**Comment by crocket** [comment]
After moving from archlinux to gentoo, I don't have pulseaudio, so I can't check it. But, pulseaudio could very well be interfering with alsa.

**Comment by crocket** [comment]
I was perusing alsa-utils codebase.

`amixer.c` has

```C
/* FIXME: normalize to int32 space to be compatible with other types */
#define MAP_VOL_RES	(INT32_MAX / 100)

static int get_mapped_volume_range(snd_mixer_elem_t *elem,
				   long *pmin, long *pmax)
{
	*pmin = 0;
	*pmax = MAP_VOL_RES;
	return 0;
}

static int get_playback_mapped_volume(snd_mixer_elem_t *elem,
				      snd_mixer_selem_channel_id_t c,
				      long *value)
{
	*value = (rint)(get_normalized_playback_volume(elem, c) * MAP_VOL_RES);
	return 0;
}
```

The definition of `get_normalized_playback_volume` in `volume_mapping.c`

```C
double get_normalized_playback_volume(snd_mixer_elem_t *elem,
				      snd_mixer_selem_channel_id_t channel)
{
	return get_normalized_volume(elem, channel, PLAYBACK);
}

static double get_normalized_volume(snd_mixer_elem_t *elem,
				    snd_mixer_selem_channel_id_t channel,
				    enum ctl_dir ctl_dir)
{
	long min, max, value;
	double normalized, min_norm;
	int err;

	err = get_dB_range[ctl_dir](elem, &min, &max);
	if (err < 0 || min >= max) {
		err = get_raw_range[ctl_dir](elem, &min, &max);
		if (err < 0 || min == max)
			return 0;

		err = get_raw[ctl_dir](elem, channel, &value);
		if (err < 0)
			return 0;

		return (value - min) / (double)(max - min);
	}

	err = get_dB[ctl_dir](elem, channel, &value);
	if (err < 0)
		return 0;

	if (use_linear_dB_scale(min, max))
		return (value - min) / (double)(max - min);

	normalized = exp10((value - max) / 6000.0);
	if (min != SND_CTL_TLV_DB_GAIN_MUTE) {
		min_norm = exp10((min - max) / 6000.0);
		normalized = (normalized - min_norm) / (1 - min_norm);
	}

	return normalized;
}


```

**Comment by jaor** [comment]
> static double get_normalized_volume(snd_mixer_elem_t *elem,
>                                     snd_mixer_selem_channel_id_t channel,
>                                     enum ctl_dir ctl_dir)
> {
>         long min, max, value;
>         double normalized, min_norm;
>         int err;
>
>         err = get_dB_range[ctl_dir](elem, &min, &max);
>         if (err < 0 || min >= max) {
>                 err = get_raw_range[ctl_dir](elem, &min, &max);
>                 if (err < 0 || min == max)
>                         return 0;
>
>                 err = get_raw[ctl_dir](elem, channel, &value);
>                 if (err < 0)
>                         return 0;
>
>                 return (value - min) / (double)(max - min);
>         }
>
>         err = get_dB[ctl_dir](elem, channel, &value);
>         if (err < 0)
>                 return 0;
>
>         if (use_linear_dB_scale(min, max))
>                 return (value - min) / (double)(max - min);

and how is use_linear_dB_scale defined? seems it could be the cause of
the difference between our observations...

**Comment by crocket** [comment]
```
#define MAX_LINEAR_DB_SCALE	24

static inline bool use_linear_dB_scale(long dBmin, long dBmax)
{
	return dBmax - dBmin <= MAX_LINEAR_DB_SCALE * 100;
}
```

**Comment by crocket** [comment]
`include/control.h` from alsa-lib

```
/** Mute state */
#define SND_CTL_TLV_DB_GAIN_MUTE	-9999999
```

```
if (use_linear_dB_scale(min, max))
	return (value - min) / (double)(max - min);

normalized = exp10((value - max) / 6000.0);
if (min != SND_CTL_TLV_DB_GAIN_MUTE) {
	min_norm = exp10((min - max) / 6000.0);
	normalized = (normalized - min_norm) / (1 - min_norm);
}

return normalized;
```

**Comment by jaor** [comment]
hmmm, blindly translating that code to haskell as:

```haskell
percent :: Integer -> Integer -> Integer -> Float
percent v' lo' hi' =
  if hi' - lo' < 2400
  then
    (v - lo) / (hi - lo)
  else
    (norm v - minNorm) / (1.0 - minNorm)
  where v = fromIntegral v'
        lo = fromIntegral lo'
        hi = fromIntegral hi'
        norm x = 10 ** ((x - hi) / 6000.0)
        minNorm = norm lo
```

is not giving the expected results either....

**Comment by jaor** [comment]
i think the problem with the direct translation might be that in the C
version min/max are in Dbs, while we're obtaining them in some sort of
linear scale... but then the linear formula should work, so it's not
quite it...

**Comment by crocket** [comment]
I think it's good to give users `-M` option for normalized volume. That way, pulseaudio users are happy, and alsa users are happy, too.

**Comment by jaor** [comment]
yes.  except that these computations don't seem to work... the alsa lib
has a getRangeDb function, with which it looks like things should work,
but it's throwing an error when i use it.

**Comment by crocket** [comment]
I'm sorry that I don't have much further time to dedicate to this issue. I am genuinely running low on money and time, and I have social pressures coming from outside that I can't ignore anymore.

I can't help with this issue at least for a while. But, I'd appreciate your efforts.

At this point, I can say that we seem to be close to the solution.

**Comment by crocket** [comment]
Although I no longer have time to delve deep into codebases, I tested `getRangeDb` on my system.

```
main :: IO ()
main = do
  withMixer "default" $ \mixer -> do
    control <- getControlByName mixer "Master"
    (lo, hi) <-liftMaybe $ getRangeDb <$> volumeControl control
    print (lo, hi)
```

```
λ> main
(Just (-6400),Just 0)
```

It works. And, it doesn't work on your system for some reason. Perhaps, is it pulseaudio?

**Comment by skinner33** [comment]
The issue is definitely coming from difference between alsa and pulseaudio. I have two systems (both arch), one with pulseaudio and one alsa, and I see both behaviors. One the pa one, amixer reports the same percentage independent of the -M switch. On the alsa systen, there is a difference when -M is used.

I can also confirm that on pa the dB are constantly 0, and that getRangeDb throws an exception. Which is not surprising as the output of amixer does not include them.

I think the best course of action would be, as @crocket suggested, to add a flag for the plugin. Maybe I have time tomorrow to figure out how to do the computation.

**Comment by jaor** [comment]
moved to https://codeberg.org/jao/xmobar/issues/300
