### ISSUE TITLE
Feature request: relative width, absolute height

### ISSUE THREAD

**Issue by lo48576** [jaor/xmobar#301]
I used xmobar with trayer, and I currently use `position = Static { ..., width = 2048, height = 20 }` (because `2560 (display width) * 80% = 2048`) and `trayer-srg ... --widthtype percent --width 20 --height 20`.
But this config is not good if I change display size, because xmobar doesn't change its width automatically (even if restarted it).

I want to use `position = TopW L 80` for xmobar width, but then I can't controll xmobar height.

I'm happy if xmobar has "relative (percentage) width and absolute (pixel) height" config.

**Comment by jaor** [comment]
yes, i see how that can be useful.

**Comment by jaor** [comment]
@lo48576 hmm, but wait, isn't `TopSize L 80 20` what you are asking for?

**Comment by lo48576** [comment]
Oh... yes, it is exactly what I wanted!
I'm sorry for overlooking... 😖 Thank you.
