### ISSUE TITLE
rxvbar, txvbar do not display properly

### ISSUE THREAD

**Issue by enescala** [jaor/xmobar#303]
Network interface template arguments "rxvbar" and "txvbar" is not displaying vertical bars in xmobar version 0.24.4. It displays something similar to "rxbar" and "txbar" arguments instead.

**Comment by b0o** [comment]
I'm having the same issue.

**Comment by jaor** [comment]
do you remember when this started happening? was it with 0.24.4?

**Comment by b0o** [comment]
@jaor I'm using the version distributed through the official Arch repository. I believe the problem began after upgrading from 0.24.4-2 to 0.24.4-3, but I am not entirely sure because I didn't notice it until I recently restarted Xmonad/Xmobar.

**Comment by jaor** [comment]
okay, i think i've fixed the issue in current master: is it possible for
any of you to check whether the fix works for you? thanks!

**Comment by enescala** [comment]
Can confirm, the fix works. Thank you!

**Comment by jaor** [comment]
Thanks a lot for the confirmation, and for the report! I've released 0.24.5 with this fix.
