### ISSUE TITLE
Mpris plugin documentation: PlayerName should not necessarily be lowercase

### ISSUE THREAD

**Issue by b0o** [jaor/xmobar#306]
The [documentation](http://projects.haskell.org/xmobar/#mpris1-playername-args-refreshrate) for the Mpris{1,2} plugins state that the PlayerName argument should be lowercase. I assumed this was correct and spent a while trying to figure out why the Mpris2 plugin wasn't working with [ColinDuquesnoy/MellowPlayer](/ColinDuquesnoy/MellowPlayer). 

As soon as I changed my configuration from referencing "mellowplayer" to "MellowPlayer", everything worked as expected.

I'd suggest the documentation be updated to avoid this confusion.

**Comment by jaor** [comment]
thanks for the heads up.  i've updated the documentation, removing the
advice to lowercase the name.
