### ISSUE TITLE
Different vertical offset for each font

### ISSUE THREAD

**Issue by madnight** [jaor/xmobar#311]
With polybar i can define fonts with an vertical offset per font like so:
```
[bar/example]
; font-N = <fontconfig pattern>;<vertical offset>
font-0 = "Tamsyn:pixelsize=12;0"
font-1 = "Roboto:size=11:weight=bold;2"
font-2 = "Noto Sans:size=11;1"
```
https://github.com/jaagr/polybar/wiki/Fonts

This is very usfull if you want to use icons from multiple fonts and align them properly.

In xmobar i can define multiple fonts:
```
Config { font = "-misc-fixed-*-*-*-*-10-*-*-*-*-*-*-*"
       , additionalFonts = [ "xft:FontAwesome:pixelsize=14" , 
"SourceCodePro+Powerline+Awesome Regular:pixelsize=10"]
```
and use them like so `template = "<fn=1></fn> %temp% `,  but i cant define an vert offset per font, there's only global offset settings available:
```
textOffset = 1
iconOffset = 1
```

**Comment by jaor** [comment]
sounds like a useful feature that shouldn't be too hard to implement... i'll try to get to it one of these days, unless someone else beats me! :) thanks for the suggestion.

**Comment by jaor** [comment]
@madnight i finally implemented this feature, using a separate list of offsets called `textOffsets`... please let me now if it doesn't work for you, and thanks a lot for your suggestion and your patience!

**Comment by madnight** [comment]
Thank you! Since this took a while, I switched to polybar in the meantime, because I really wanted that feature. However, now I consider a switch back to xmobar, when I find so time to convert my polybar config to xmobar config. :+1:
