### ISSUE TITLE
StdinReader not handling expected action fields

### ISSUE THREAD

**Issue by cprussin** [jaor/xmobar#314]
So, when I run the following, I would expect to get an xmobar that has a character 'a' that can be clicked and will cause xdotool to enter an 'b':

```bash
$ while true; do echo '<action=`xdotool key b`>a</action>'; sleep 1; done |
    xmobar -c '[ Run StdinReader ]' -t '%StdinReader%' --font "xft:DejaVu Sans Mono-10"
```

However, when I run this, I get the following xmobar.  Nothing is clickable:

![screenshot2](https://user-images.githubusercontent.com/297575/29738598-602af680-89db-11e7-82aa-95c64bb31900.png)

Note that I have discovered some characters I can put in place of 'a' that will generate the expected result... for instance, this line does have expected behavior:

```bash
$ while true; do echo '<action=`xdotool key b`>─</action>'; sleep 1; done |
    xmobar -c '[ Run StdinReader ]' -t '%StdinReader%' --font "xft:DejaVu Sans Mono-10"
```

(note that that's the unicode box-drawing dash)

My version info:

```
$ xmobar --version
xmobar 0.24.5
 (C) 2007 - 2010 Andrea Rossato 
 (C) 2010 - 2017 Jose A Ortega Ruiz
 <xmobar@projects.haskell.org>

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the License for more details.
```

**Comment by TatriX** [comment]
You should use
``` 
, Run UnsafeStdinReader
...
, template = "%UnsafeStdinReader%
```

**Comment by cprussin** [comment]
Ah thank you @TatriX , I must have missed that in the manuals.  Sorry for the noise!
