### ISSUE TITLE
Segmentation faults

### ISSUE THREAD

**Issue by dschrempf** [jaor/xmobar#316]
Hello,

since the update to the latest version, I get seemingly random segmentation faults. I use
`xmonad 0.13` and `xmobar 0.24.5` on
`Linux 4.12.13-1-ARCH #1 SMP PREEMPT Fri Sep 15 06:36:43 UTC 2017 x86_64 GNU/Linux`.

The journal reports:

    Sep 20 12:17:32 schwarzbaer kernel: xmobar[2023]: segfault at 0 ip 00007f79979ec064 sp 00007fff65245bc8 error 4 in libHSbase-4.10.0.0-ghc8.2.1.so[7f7997388000+91a000]
    Sep 20 12:17:32 schwarzbaer systemd[1]: Created slice system-systemd\x2dcoredump.slice.
    Sep 20 12:17:32 schwarzbaer systemd[1]: Started Process Core Dump (PID 21608/UID 0).
    Sep 20 12:17:33 schwarzbaer systemd-coredump[21609]: Process 2023 (xmobar) of user 1000 dumped core.

                                                         Stack trace of thread 2023:
                                                         #0  0x00007f79979ec064 base_GHCziForeign_charIsRepresentable3_info (libHSbase-4.10.0.0-ghc8.2.1.so)

Please let me know how I can provide further debugging information and if you need to see my configuration.

Maybe of interest:
I am using a laptop with docking station and repeatedly dock/undock the system according to need. Maybe the changes in screen resolution are related to the issue?

**Comment by habbbe** [comment]
I can confirm the segfaults on my machine. However, I'm not using any docking station or changing resolution.
System:
`Linux 4.12.13-1-ARCH #1 SMP PREEMPT Fri Sep 15 06:36:43 UTC 2017 x86_64 GNU/Linux`
`xmonad 0.13-7`
`xmobar 0.24.5-5`

The log says:
```
Process 8245 (xmobar) of user 1000 dumped core.
             Stack trace of thread 8245:
                  #0  0x00007fa1d8bf1d02 n/a (libHSrts-ghc8.2.1.so)
                  #1  0x00007fa1d8bf0ffd n/a (libHSrts-ghc8.2.1.so)
                  #2  0x00007fa1d8c0686d n/a (libHSrts-ghc8.2.1.so)
                  #3  0x00007fa1d8c0cfea n/a (libHSrts-ghc8.2.1.so)
                  #4  0x00007fa1d8bfeabd n/a (libHSrts-ghc8.2.1.so)
                  #5  0x00007fa1d8bff62e scheduleWaitThread (libHSrts-ghc8.2.1.so)
                  #6  0x00007fa1d8c0249e hs_main (libHSrts-ghc8.2.1.so)
                  #7  0x0000000000578d61 n/a (xmobar)
                  #8  0x00007fa1d7d82f6a __libc_start_main (libc.so.6)
                  #9  0x000000000042b60a n/a (xmobar)
```

and also:
```
Process 15227 (xmobar) of user 1000 dumped core.                                
             Stack trace of thread 17306:
                  #0  0x0000000000539fac n/a (xmobar)
```

**Comment by Emantor** [comment]
Related to #310

**Comment by Maeda1** [comment]
Hi !

It doesn't seems to be related to #310.
For me the crashes now occurs when mouse clicking on xmobar.
`[  248.231970] xmobar[3304]: segfault at 0 ip 00007f996f46ed19 sp 00007fff7d040158 error 4 in libHSbase-4.10.0.0-ghc8.2.1.so[7f996ed3b000+91a000]
[  872.848686] xmobar[9015]: segfault at 0 ip 00007fec012c6d19 sp 00007ffd584a4178 error 4 in libHSbase-4.10.0.0-ghc8.2.1.so[7fec00b93000+91a000]`

Let me know if you need more logs (and where to take them).

**Comment by jonascj** [comment]
Same here, xmobar seemingly segfaults at random (haven't narrowed down when); bar started by XMonad Contrib's DynamicBars.
Kernel: 4.13.11-1-ARCH
xmobar: 0.24.5-6
XMonad: 0.13-9
Log: xmobar[17246]: segfault at 2c00008 ip 0000000000546a04 sp 00007fff5ceae668 error 4 in xmobar[400000+18b000]

Also, let me know if I can provide more logs or anything.

**Comment by incertia** [comment]
there's a good chance updating ghc to upstream will solve the issue (see the following [ticket](https://ghc.haskell.org/trac/ghc/ticket/13707))

**Comment by doyougnu** [comment]
Same behavior confirmed here:

```
                -`                 
                  .o+`                 doyougnu@7thChamber
                 `ooo/                 OS: Arch Linux 
                `+oooo:                Kernel: x86_64 Linux 4.11.2-1-ARCH
               `+oooooo:               Uptime: 1d 3h 57m
               -+oooooo+:              Packages: 1546
             `/:-:++oooo+:             Shell: zsh 5.4.2
            `/++++/+++++++:            Resolution: 1440x900
           `/++++++++++++++:           DE: MATE 1.18.2
          `/+++ooooooooooooo/`         WM: XMonad
         ./ooosssso++osssssso+`        GTK Theme: 'VimixDark-Laptop-Ruby' [GTK2/3]
        .oossssso-````/ossssss+`       Icon Theme: Paper
       -osssssso.      :ssssssso.      Font: Sans 10
      :osssssss/        osssso+++.     CPU: Intel Core i5-5250U @ 4x 2.7GHz [44.0°C]
     /ossssssss/        +ssssooo/-     GPU: intel
   `/ossssso+/:-        -:/+osssso+-   RAM: 2617MiB / 3858MiB
  `+sso+:-`                 `.-/+oso: 
 `++:.                           `-/+/
 .`                                 `/

```

**Comment by metaswirl** [comment]
I am experiencing the same issue. A recent post on the archlinux bug tracker seems to indicate that using the option "--enable-debug-info=1" fixes the issue.

**Comment by jad-issa** [comment]
As @Maeda1 indicated, the issue seems to come up when clicking on xmobar. In fact, I have first noticed that sometimes, though not at all times, when I receive a notification on firefox and I click on it (possibly clicking on xmobar too) it will crash with a core dump. After testing Maeda1's proposition, I can confirm that clicking on xmobar multiple times does make it crash. Unfortunately, there does not seem to be a pattern as to when exactly the click will result in failure. PS: I also run Archlinux.

**Comment by Legogris** [comment]
I have this too. 
Syslog1:
```
systemd-coredump[3225]: Process 2567 (xmobar) of user 1000 dumped core.
                                             Stack trace of thread 2567:
                                             #0  0x00000000011c15b0 n/a (n/a)
```
```
systemd-coredump[3159]: Process 15711 (xmobar) of user 1000 dumped core.

                                             Stack trace of thread 15711:
                                             #0  0x00007f2eae5232b8 n/a (libHSrts-ghc8.4.3.so)
                                             #1  0x00007f2eae522b3c n/a (libHSrts-ghc8.4.3.so)
                                             #2  0x00007f2eae5393a4 n/a (libHSrts-ghc8.4.3.so)
                                             #3  0x00007f2eae53fc2b n/a (libHSrts-ghc8.4.3.so)
                                             #4  0x00007f2eae52800d n/a (libHSrts-ghc8.4.3.so)
                                             #5  0x00007f2eae528d0a scheduleWaitThread (libHSrts-ghc8.4.3.so)
                                             #6  0x00007f2eae5368dc hs_main (libHSrts-ghc8.4.3.so)
                                             #7  0x000000000058ad5f n/a (xmobar)
                                             #8  0x00007f2eadc1b06b __libc_start_main (libc.so.6)
                                             #9  0x000000000043001e n/a (xmobar)
```

`xmonad-0.13.20180419-3`

`xmobar-0.26-66`

It's been like this for quite some releases though, can't say specifically when it started but months ago.

**Comment by dpzmick** [comment]
Same issue here, xmobar on arch. No clicking involved

**Comment by dschrempf** [comment]
Hi, please see #354, and we keep our fingers crossed :)!
