### ISSUE TITLE
Scrolling Messages

### ISSUE THREAD

**Issue by Gab0** [jaor/xmobar#320]
I could not find an implementation of this, so I wrote.
It prints a sequence of messages in order to get a side-scrolling effect on XMobar, intended to use with `Run CommandReader`
There is also a script there that gathers tweets to compound the message.
Is it useful to anyone?
https://github.com/Gab0/newsfilter

**Comment by BadDecisionsAlex** [comment]
Xmobar.Plugins.MarqueeReader might be up your alley?

**Comment by Gab0** [comment]
Seems the thing to go, dunno how I didn't reach it when I searched...

But nowadays my implementation has evolved to the point of being able to have a link attached to one of the scrolling messages, so we can click it (it uses xmobar `action`for this) and open on the browser.

Do you know if this is possible easily on MarqueePipeReader?

**Comment by BadDecisionsAlex** [comment]
> Seems the thing to go, dunno how I didn't reach it when I searched...
> 
> But nowadays my implementation has evolved to the point of being able to have a link attached to one of the scrolling messages, so we can click it (it uses xmobar `action`for this) and open on the browser.
> 
> Do you know if this is possible easily on MarqueePipeReader?

Yeah I had it working through URxvt without using actions (using perl scripts). You could add the action tag to accomplish the same effect though. Any of the usual formatting tags work in the Marquee.

**Comment by jaor** [comment]
this one seems to be resolved.  closing.  please feel free to re-open otherwise.
