### ISSUE TITLE
Config options for window class, role, and title

### ISSUE THREAD

**Issue by schoettl** [jaor/xmobar#323]
Many programs have command line or configuration options to set the window class name or a window title. Can this also be added to xmobar?

Or is there another way to detect a specific instance of xmobar and move it to a specific workspace in xmonad? In my case I need a control panel (xmobar) on a specific workspace in addition to the standard xmobar top bar...

**Comment by jaor** [comment]
i've just pushed a commit that lets specify WM_CLASS and WM_NAME for
xmobar instances via either the configuration file (wmClass, wmName) or
CLI flags (-w, -n).  does that do the trick?

**Comment by schoettl** [comment]
Yes that works great! Thank you!
