### ISSUE TITLE
Battery <leftbar> size

### ISSUE THREAD

**Issue by Radvendii** [jaor/xmobar#324]
Can we get the <leftbar> version of battery to have a larger battery bar depending on the capacity of the battery? If I have two batteries, one of which is bigger than the other, it doesn't make sense for them to be the same width.

**Comment by Radvendii** [comment]
So after poking around the source code for a while, it seems like I should be able to specify "-w","20" (for example) in the args to change the size of the battery bar, but this raises an error for some reason.

**Comment by jaor** [comment]
> So after poking around the source code for a while, it seems like I
> should be able to specify "-w","20" (for example) in the args to

The argument to specify bar lengths is "-W", not "-w".  documentation
for shared monitor arguments is here:

https://archives.haskell.org/projects.haskell.org/xmobar/#default-monitor-arguments

and for battery-specific ones (although you shouldn't need any of them
for this, i think) is here:

https://archives.haskell.org/projects.haskell.org/xmobar/#default-monitor-arguments

**Comment by Radvendii** [comment]
Yup. I just figured this out and forgot to update the issue. Thanks!
