### ISSUE TITLE
[solved] [question] how does one render a string when a monitor is not displaying?

### ISSUE THREAD

**Issue by vinnyA3** [jaor/xmobar#325]
Question:  How can I render a *Not Playing* string when using the Mpris monitor isn't running?

The docs say that I can use the `-x` flag but that doesn't seem to do anything.

Thanks !

**Comment by jaor** [comment]
that is a bug in the MPris monitor.  i've pushed a commit that should
have fixed it: please let me know if it's working now for you.

**Comment by vinnyA3** [comment]
It works like a charm, awesome!  I wish I knew enough Haskell to figure that out for you.  I hope to contribute in the near future if I can.  Cheers!

**Comment by jaor** [comment]
On Fri, Dec 22 2017, Vinny wrote:

> It works like a charm, awesome! I wish I knew enough Haskell to figure
> that out for you. I hope to contribute in the near future if I
> can. Cheers!

you are already contributing! looking forward to that first pull request :)
