### ISSUE TITLE
Mbox.hs option for prefix/suffix that is displayed only when mail is present

### ISSUE THREAD

**Issue by dovej** [jaor/xmobar#327]
It'd be very useful to have an option for prefixes and suffixes that appear only when there is any mail present. This way, the mail widget in the xmobar could completely disappear when there's nothing to see, but still display some template text to label the mail count when it **is** present.

**Comment by jaor** [comment]
On Thu, Jan 11 2018, Justin Dove wrote:

> It'd be very useful to have an option for prefixes and suffixes that
> appear only when there is any mail present. This way, the mail widget
> in the xmobar could completely disappear when there's nothing to see,
> but still display some template text to label the mail count when it
> is present.

i am not sure i am following what you say here, but, if i am, that's precisely

>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
>

-- 
God is real, unless declared integer.

**Comment by jaor** [comment]
On Thu, Jan 11 2018, Justin Dove wrote:

> It'd be very useful to have an option for prefixes and suffixes that
> appear only when there is any mail present. This way, the mail widget
> in the xmobar could completely disappear when there's nothing to see,
> but still display some template text to label the mail count when it
> is present.

sorry, hit send by accident.  i was saying, i think that's precisely
what the "-p" and "-s" options do: they're a prefix and suffix that is
only displayed when there is no email.  in addition, the name of the
mbox acts as a per-mailbox prefix that is only displayed when there is
email?

**Comment by dovej** [comment]
It's totally possible I'm not RTFMing hard enough, but I tried a few things and didn't seem to find what I was looking for.

To clarify, I'm looking to print some characters only when there is mail present. So for example, if I have no mail I don't want anything to print at all, and then if I do have 3 emails I'd want "!: 3 " to print, or something like that. Note the space after the "3". Is this possible already?

**Comment by jaor** [comment]
On Mon, Jan 15 2018, Justin Dove wrote:

> It's totally possible I'm not RTFMing hard enough, but I tried a few things and didn't seem to find what I was looking for.
>
> To clarify, I'm looking to print some characters only when there is mail present. So for example, if I have no mail I don't want anything to print at all, and then if I do have 3 emails I'd want "!: 3 " to print, or
> something like that. Note the space after the "3". Is this possible already?

in the inbox file configuration:

   [("!: ", "inbox", "darkseagreen4"), ...]

and in the options:

   ["-s", " "]

if you have multiple inbox files and want the same prefix for all, you
can also use simply

   ["-p", "!: ", "-s", " "]

and the empty string in the individual file configurations.


      Run MBox [("!: ", "inbox", "darkseagreen4")] ["-s", " ", "-d", "~/var/mail"]

**Comment by dovej** [comment]
Just tried that. I have no mail and I see "!:  ". I'd like to see nothing at all.

Maybe a version issue? I'm running 0.24.3-2+b1 from Debian Stretch. Although maybe I'm still just miscommunicating.

**Comment by dovej** [comment]
To be clear, I'm also running the -u option.

**Comment by dovej** [comment]
It seems to me that the behavior right now is that the prefixes and suffixes always display, and then the mail count only displays if there's something to show. The desired behavior is for nothing to display unless there is mail, and then display both the count and any prefix/suffix.

**Comment by jaor** [comment]
i don't know why you see that. the prefixes don't display for at all for
me.  can you drop the "-u"? can you share your full configuration?

**Comment by dovej** [comment]
Cracked it. Sorry. This is just a duplicate of #326. I forgot I had that "FOLDER INTERNAL DATA" message in the mbox, which -u was suppressing for me. As soon as I cleared that message the prefix and suffix disappear.
