### ISSUE TITLE
CommandReader's program isn't cleaned up on exit 

### ISSUE THREAD

**Issue by mkoskar** [jaor/xmobar#328]
Using `CommandReader` plugin it seems that when `xmobar` exits the command keeps running re-parented under pid1. I think these background commands should be cleaned up / terminated on exit. As a workaround I wrap xmobar in a simple script:

```
#!/bin/bash

cleanup() { trap : TERM; kill 0; }
trap cleanup EXIT

xmobar
```

**Comment by jaor** [comment]
moved to https://codeberg.org/jao/xmobar/issues/328
