### ISSUE TITLE
Non-standard battery name

### ISSUE THREAD

**Issue by brittAnderson** [jaor/xmobar#336]
I am using a gpd pocket running linux. This has a non-standard battery name "max17xx". When I add this in Batt.hs and recompile the battery plugin works fine.

Question: is this the solution for these odd use cases? Just edit the source yourself and recompile? Or is it worth a pull request? In which case you end up with a long list of possibly odd battery names and paths permanently grafted into your source.

**Comment by jaor** [comment]
> I am using a gpd pocket running linux. This has a non-standard battery
> name "max17xx". When I add this in Batt.hs and recompile the battery
> plugin works fine.

That's what `BatteryP` is for: doesn't something like

      Run BatteryP ["max17xx"] [...] 100

work for you?
(https://github.com/jaor/xmobar#batteryp-dirs-args-refreshrate)

**Comment by brittAnderson** [comment]
Yes it does. Thanks, and apologies for the noise.

As an aside this system does not have power_now (only voltage_now) so <timeleft> doesn't work. At least I think that is the problem, but seeing <left>% is good enough for me.

**Comment by jaor** [comment]
> As an aside this system does not have power_now (only voltage_now) so
> doesn't work. At least I think that is the problem

yes, sounds like it.  we need either power_now or current_now.

**Comment by jaor** [comment]
moved to https://codeberg.org/jao/xmobar/issues/336
