### ISSUE TITLE
Battery named "BAT" not detected

### ISSUE THREAD

**Issue by dandelionmane** [jaor/xmobar#338]
My laptop has a battery named "BAT" as opposed to "BAT0". Xmobar didn't auto detect it, so I've needed to use BatteryP "BAT" to get things to work. "BAT" seems like a reasonable enough battery name that xmobar should support it by default.

**Comment by jaor** [comment]
i've just pushed a patch that should add BAT to the list.  please reopen
if it doesn't work for you. thanks!
