### ISSUE TITLE
Add option to Com command to specify failure message

### ISSUE THREAD

**Issue by b0o** [jaor/xmobar#342]
Currently, if an external command specified with `Com` exits with non-zero code, xmobar outputs `Could not execute command ...` in its place.

It would be very useful to have a configuration option to set the failure message per command. 

In my case, I would like to set the failure message of certain commands to be an empty string, because I do not necessarily care if they fail. Because this feature isn't available in Xmobar, I need to use a wrapper script to ensure that the command always exits with code 0.

The relevant section of the source code is [here](https://github.com/jaor/xmobar/blob/581806974db7dc2a182f16e72e2233a90cda5b5f/src/Commands.hs#L75).

This feature would essentially be equivalent to the `--nastring` option for monitors, which isn't available for `Com` commands, as far as I can tell.

**Comment by jaor** [comment]
I've pushed cbde794, that implements this feature via a new monitor, `ComX`, which takes an additional parameter for the error string.  Sorry for the long wait!
