### ISSUE TITLE
Syntax error with Volume module

### ISSUE THREAD

**Issue by owlas** [jaor/xmobar#344]
The following minimum config example causes a syntax error:
```
Config { position = TopW L 100
       , commands = [ Run CoreTemp ["-t", "<core0>C"] 10
       	 	    , Run Volume "default" "Master" 10
		    ]
       , template = "%coretemp%                "
       }
```
Error is:
```
unexpected "t"
expecting space or "Run"
CallStack (from HasCallStack):
  error, called at src/Main.hs:91:19 in main:Main
```

However, if I comment out the `Run Volume` line it compiles fine. It looks like there is some unbalanced brackets. Could this be a result of parsing in the volume module?

**Comment by jaor** [comment]
Hi Olivier,

The error message is misleading. The problem is that you're xmobar is
not compiled with support for alsa.  For that, one needs to configure
with the flag `with_alsa` (or `all_extensions`) and the development
files for the C library libasound be installed in your system.

**Comment by owlas** [comment]
@jaor thanks. I'll try this today
