### ISSUE TITLE
Module XMonad.Hooks.ManageDocks does not export docks

### ISSUE THREAD

**Issue by jl2035** [jaor/xmobar#349]
Hi, I installed xmonad on a Ubuntu Mate 16.04.4 LTS and I've followed the official [documentation](https://wiki.haskell.org/Xmonad/Config_archive/John_Goerzen's_Configuration). I'm very new to this :(

For some reason my xmobar is hiding behind windows. I've followed this issue: https://github.com/jaor/xmobar/issues/294 and tried to change my configuration accordingly.

```
+import XMonad.Hooks.ManageDocks   (ToggleStruts(..),avoidStruts,docks,manageDocks)
....
-  xmonad $ defaultConfig
+  xmonad $ docks defaultConfig
```

But now I have a white window error saying:
```
Error detected while loading xmonad configuration file: /home/user/.xmonad/xmonad.hs

xmonad.hs:7:65
    Module â\200\230XMonad.Hooks.ManageDocksâ\200\231 does not export ã\200\230docksâ\200\231

Please check the file for errors
```
I don't understand the meaning of this error message. What does it mean "does not export something"?

It's strange that just adding the import line actually fixes my initial problem with xmobar hiden behind other windows, but I get "does not export docks" error on every session start and that really sucks.

**Comment by ggreif** [comment]
see @jaor 's comment in the referenced issue:

> yes, `docks` is new in recent xmonad, and should be the answer to this problem. i'm closing the issue, but please feel free to reopen it if there's still any problem. thanks!

Is your installed `xmonad` the of right version?

**Comment by jl2035** [comment]
My version is 0.12

**Comment by ggreif** [comment]
@jl2035 then you seem to be out of luck: http://hackage.haskell.org/package/xmonad-contrib-0.12/docs/doc-index-D.html does not list the `docks` function. http://hackage.haskell.org/package/xmonad-contrib-0.13/docs/doc-index-D.html does. Upgrade to 0.13 or try to frob the `docks` function from 0.13 and add it locally.

**Comment by jl2035** [comment]
I've executed "apt-get upgrade", but sadly it looks like 0.12 is the highest version in Ubuntu. Is there some other way to upgrade?

**Comment by ggreif** [comment]
I guess you can build yourself with `stack` or `cabal`. I don't use `apt-get` myself.

**Comment by jl2035** [comment]
If I build it myself, can I then just replace the binary under /usr/bin/xmonad? Would that break my system, fail some kind of integrity check?

**Comment by jl2035** [comment]
I actually did that successfully. I've built xmonad 0.13 with cabal and copied the binary from .cabal/bin/xmonad to /usr/bin/xmonad. Executing "xmonad --version" shouts version 0.13. 

Sadly I'm still getting two white windows with the same error:

`Error detected while loading xmonad configuration file: /home/user/.xmonad/xmonad.hs`

`xmonad.hs:3:65`
`    Module â\200\230XMonad.Hooks.ManageDocksâ\200\231 does not export ã\200\230docksâ\200\231`

`Please check the file for errors`
