### ISSUE TITLE
Build breaks with hinotify-0.3.10

### ISSUE THREAD

**Issue by Xitian9** [jaor/xmobar#350]
hinotify-0.3.10 now uses RawFilePath instead of FilePath. Either the cabal file should put a version cap on hinotify, or the code should be updated.

**Comment by markwright** [comment]
I think this is a duplicate of #348 .

**Comment by Xitian9** [comment]
Indeed, it does seem to be. The easiest solution is to just add a version cap, though obviously the code will have to be updated eventually. Would it be preferred to change the code now, at the cost of a much more restrictive version floor for hinotify?

**Comment by markwright** [comment]
I propose changing the code to fix the build with hinotify 0.3.10 and earlier versions of hinotify.
