### ISSUE TITLE
hinotify 0.3.10 breaks the build because it violates the PVP

### ISSUE THREAD

**Issue by peti** [jaor/xmobar#356]
FYI: https://github.com/kolmodin/hinotify/issues/29

**Comment by peti** [comment]
Now that `hinotify-0.3.10` is deprecated, can you please edit the Cabal file for `xmobar` on Hackage to allow building with http://hackage.haskell.org/package/hinotify-0.4?

**Comment by jaor** [comment]
done

**Comment by peti** [comment]
Will you release an update?

**Comment by jaor** [comment]
https://hackage.haskell.org/package/xmobar-0.28

**Comment by peti** [comment]
Thank you.
