### ISSUE TITLE
Can't use xft font.

### ISSUE THREAD

**Issue by dorobouNeko** [jaor/xmobar#362]
Hi.

I have been trying to use terminus font but can't. It gives me this warning.
`Warning: Xmobar must be built with the with_xft flag to support font xft:Terminus:pixelsize=14:antialias=false. Falling back on default.`

I installed it first with default features with:
```
git clone git://github.com/jaor/xmobar
cabal install
```
but then realized i needed the other features
so i even did
```
cabal clean
cabal install --flags="all_extensions"
```
but still get that warning when i run `xmobar &`

I am not sure what i am doing wrong. I'll leave my .xmobarrc if there is something wrong with it.
[xmobarrc.txt](https://github.com/jaor/xmobar/files/2372947/xmobarrc.txt)

**Comment by jaor** [comment]
hmm, try 

    cabal install -fall_extensions

and also, make sure you have libXft-dev installed in your system.

**Comment by jaor** [comment]
On Wed, Sep 12 2018, dorobouNeko wrote:

> yes i have done both.

and is `fc-list` showing Terminus in your system? I don't see xft for
terminus in mine, even though I have the font installed...

**Comment by dorobouNeko** [comment]
yes, it shows. i have been using that font for everything monospace, browser, urxvt, etc.

**Comment by jaor** [comment]
does it work without the "antialias=false" bit? if you don't want antialiasing, you can also try to specify it as a regular font, not as xft, using the name reported by xlsfonts...

**Comment by dorobouNeko** [comment]
Nope. same error. is there any verbose mode or more info to debug?

**Comment by jaor** [comment]
no, there's no verbose mode. you get an error that no xft support is
available when you use "terminus-12", sans xft: as the name?  that's
really unexpected.  does this happen with other fonts too, or is limited
to terminus?

**Comment by dorobouNeko** [comment]
I tried with Helvetica and same error.
```
Fields missing from config defaulted: wmClass,wmName,textOffsets
Warning: Xmobar must be built with the with_xft flag to support font xft:Helvetica. Falling back on default.
```

**Comment by dorobouNeko** [comment]
Tried with font = "lucidasans-8" and that works. Only xft fonts do not work.

**Comment by jaor** [comment]
So it seems for some reason your xmobar is not compiled with xft support
for some reason.  I guess you've got installed the libxft-dev package?
(that's how it's called in debian/ubuntu), i.e., there's a
/usr/include/X11/Xft/Xft.h in your system?

I don't think it'll make any difference, but you can try:

        cabal install -fall_extensions -fwith_xft

an see if that helps.

**Comment by dorobouNeko** [comment]
this is so bizarre. i tried 
```
cabal clean
cabal --verbose install -fall_extensions -fwith_xft
```
to see if there were any errors or something i was missing and now it works.
I didn't change anything, only difference i can think of is the way the flags are written, i.e -fflag instead of --flags="flags" or that i tried specifically with_xft.
But then again i am sure i tried --flags="with_xft" just in case and it didn't complain or anything when building.
I am really perplexed and confused.

**Comment by dorobouNeko** [comment]
Maybe the flags weren't being changed one way or another. I am not an expert using cabal.

**Comment by jaor** [comment]
i don't really know what might be going on.  for me, and i think most
other users, `cabal install -fall_extensions` always works, without
anything else to do...

**Comment by mtolly** [comment]
FWIW, I encountered the same glitch installing with Stack. After cloning the repo I did this:

```
stack install
# builds and installs with no XFT
# now I edit stack.yaml to add
# | flags:
# |   xmobar:
# |     all_extensions: true
stack install
# builds and installs: still no XFT
rm -rf .stack-work
stack install
# builds and installs: now has XFT
```

So it seems both tools have issues doing the correct rebuilding when flags are changed.

**Comment by jaor** [comment]
moved to https://codeberg.org/jao/xmobar/issues/362
