### ISSUE TITLE
Battery plugin colors should affect bar and vbar

### ISSUE THREAD

**Issue by Legogris** [jaor/xmobar#363]
It would be great if the colors specified with `-l`, `-m`, `-h` and `-p` would affect the `bar` value.

Alternatively, if we would get a way to solve this with different templates depending on if thresholds are reached or not.

I basically just want a simple bar that turns red to make me aware that it's time to plug in :)

**Comment by jaor** [comment]
Just checked again, and, as far as i can tell, `<leftvbar>` and `<leftvar>` are already honoring the `--low` and `--high` thresholds (with ranges 0-100), so i'm closing this issue.  Please feel free to reopen it if it's not working for you!
