### ISSUE TITLE
Config parser and type are inconsistent for wmClass & wmName

### ISSUE THREAD

**Issue by Procrat** [jaor/xmobar#368]
While the parser for the config file [expects](https://github.com/jaor/xmobar/blob/a2365de/src/Parsers.hs#L237) `wmclass` and `windowName`, the type expects `wmClass` and `wmName`.

If I try to provide `wmClass` and `wmName` in my config file, the parser will bail out with:
```
configuration file contains errors at:
"Config" (line 26, column 5):
unexpected 'w'
expecting space, "iconRoot", "persistent", "lowerOnStart", "pickBroadest", "overrideRedirect", "allDesktops", "hideOnStart", "alpha", "borderWidth", "borderColor", "border", "iconOffset", "textOffsets", "textOffset", "position", "fgColor", "bgColor", "windowName", "wmclass", "additionalFonts" or end of input
CallStack (from HasCallStack):
  error, called at src/Main.hs:93:19 in main:Main
```
If I try to provide `wmclass` and `windowName` which the parser _does_ allow, it will complain with "Fields missing from config defaulted: wmClass,wmName".

**Comment by jaor** [comment]
Thanks for the report, should be fixed in master!

**Comment by Procrat** [comment]
Thank you!

Could it be that this only fixes the `wmclass` -> `wmClass` issue but not the `windowName` -> `wmName` issue?

**Comment by jaor** [comment]
oops, indeed.  wmName was broken too: should work fine now!

**Comment by Procrat** [comment]
Awesome! Thank you!
