### ISSUE TITLE
xmobar Permission Denied (executeFile)

### ISSUE THREAD

**Issue by BadDecisionsAlex** [jaor/xmobar#371]
Sooo any time I try to launch xmobar I get a somewhat nondescript error `xmobar: /home/myusername: executeFile: permission denied (Permission denied)`.

I have tracked the culprit to a failure reading `~/.xmobarrc`. When I delete this file xmobar can launch. I have also tried adding full open permissions to the file but it still fails to execute.

Hopefully someone can shed some light on what might be causing this.
Even knowing what file was trying to be accessed would be a huge help.

additional info:

`ghc-8.6.2` (I was able to run things fine with `ghc-7.10.3` in the past)
config is at `~/.xmobarrc` (I have tried removing all commands and the error persists, so I don't think the failure occurs as a result of any particular command I'm trying to run)
I have installed xmonad, and cabal as a **user, not as root**; but this did not cause issues with older ghc builds.
I am installing with cabal (i've tried with and w/o extensions and with both `cabal install xmobar` and `cabal new-install xmobar`)

```
Config  { windowName        = "xmobar"
        , wmclass           = "xmobar"
        , font              = "xft:ProggyCleanTT:size=24"
        , additionalFonts   = [ "xft:ProggyCleanTT" ]
        , bgColor           = "#181818"
        , fgColor           = "#767B6F"
        , borderColor       = "#C1DDFF"
        , borderWidth       = 3
        , border            = BottomB
        , alpha             = 255
        , textOffset        = -1
        , iconOffset        = -1
        , lowerOnStart      = True
        , pickBroadest      = False
        , persistent        = False
        , hideOnStart       = False
        , iconRoot          = "."
        , allDesktops       = True
        , overrideRedirect  = True
        , sepChar           = "%"
        , alignSep          = "}{"
        , template = " %StdinReader% }{ %KAUS% | %day% | %time% "
        , position = Static { xpos = 0, ypos = 0, width = 1920, height = 42 }
        , commands = [ Run StdinReader
                     , Run Date "%I:%M:%S" "time" 10
                     , Run Date "%a %b %_d %Y" "day" 30
                     , Run Weather "KAUS" [ "-t", "ATX: <tempC>C"
                                         , "-L", "18", "-H", "25"
                                         , "--normal", "green"
                                         , "--high", "red"
                                         , "--low", "lightblue"
                                         ] 36000
                     ]
        }
```

**Comment by jaor** [comment]
the only reason xmobar would try to execute something would be if your
config file looked not like a config (had some syntax error), because
then it's going to try to compile it as a haskell file.  for that, it
tries to use ghc, but the error should be more self-explanatory.  so
it's not really clear to me that that is what's happening.

how do you try to start xmobar? what happens if you remove your config
file altogether?

you might also try `xmobar -v` (verbose mode), in case there's a bit
more info there.

**Comment by BadDecisionsAlex** [comment]
Hey thanks for following up I have been doing some more digging.
I just discovered that you can write your config as an actual haskell file. (~/.xmobar/xmobar.hs)
I am just trying to find some good examples to work off of. There are little issues (not sure how to format my Run commands). It seems happy to load a config file from here. (I just need to get my config "converted")

After running with `xmobar -v` and `xmobar -r` I discovered that is searching for my config at `~/.hs` lol. Which doesn't make a whole lot of sense. Even when I explicitly try `xmobar ~/.xmobarrc` it attempts to read `~/.hs`

**Comment by jaor** [comment]
On Fri, Dec 07 2018, Alex Ameen wrote:

> Hey thanks for following up I have been doing some more digging.
> I just discovered that you can write your config as an actual haskell file. (~/.xmobar/xmobar.hs)
> I am just trying to find some good examples to work off of.

There's a simple example here:
https://github.com/jaor/xmobar/blob/master/examples/xmobar.hs

and a more complicated one is my own config:

https://gitlab.com/jaor/xmobar-config/tree/master/src

(which actually has two xmobars, Top and Bottom and uses a lib)

> After running with xmobar -v and xmobar -r I discovered that is
> searching for my config at ~/.hs lol. Which doesn't make a whole lot
> of sense. Even when I explicitly try xmobar ~/.xmobarrc it attempts to
> read ~/.hs

Oh, that looks like a bug on my side, I'll take a look...

**Comment by BadDecisionsAlex** [comment]
Thank you! I had actually just forgotten a few of the default options. Once I plugged those in it fired up.
It still does not explain the ~/.hs issue. Hopefully I helped point something out :)

In any case thank you so much for the help and for all your hard work on the project. I have been a user for years and love it!

**Comment by jaor** [comment]
On Fri, Dec 07 2018, Alex Ameen wrote:

> Thank you! I had actually just forgotten a few of the default
> options. Once I plugged those in it fired up.  It still does not
> explain the ~/.hs issue. Hopefully I helped point something out :)

You did.  That behaviour is indeed a bug, and it should be fixed with my
last commit to master.  Now, we only attempt to compile .hs, .hsc or
.lhs files, so that if there's an error in a regular configuration file
such as .xmobarrc xmobar won't try to do any silly thing as above, just
tell you there's a parsing error.  Please let me know if that doesn't
yet work!

> In any case thank you so much for the help and for all your hard work
> on the project. I have been a user for years and love it!

Thanks to you for using it and patiently suffering my beta quality
releases :)

**Comment by BadDecisionsAlex** [comment]
Don't sweat it. This actually worked out, I had always wanted to move my bar config into my xmonad settings. This little bug led me down the path to making those changes. 
Again thanks for all your work.
