### ISSUE TITLE
Volume Options Unrecognized

### ISSUE THREAD

**Issue by BadDecisionsAlex** [jaor/xmobar#374]
Hey it seems that the extra volume options are not being parsed properly, but the common monitor options are. 
For instance
[ “-c”, “white”, “-C”, “black” ] as well as
[ “—onc”, “white”, “—offc”, “black” ]

I tried digging in the source a bit too trace the issue, buuut theres a lot to go through. I imagine you might be able to spot it way faster than me.

**Comment by jaor** [comment]
On Thu, Dec 13 2018, Alex Ameen wrote:

> Hey it seems that the extra volume options are not being parsed properly, but the common monitor options are.
> For instance
> [ “-c”, “white”, “-C”, “black” ] as well as
> [ “—onc”, “white”, “—offc”, “black” ]

are you using "--" to mark the start of the extra options?

         [ <common options>, "--", “-c”, “white”, “-C”, “black”]

**Comment by BadDecisionsAlex** [comment]
🙊
That was it. Sorry

**Comment by jaor** [comment]
no problem, now everyone encountering the same problem will google its
way to this thread :)
