### ISSUE TITLE
Command Line Flags Ignored (29.4)

### ISSUE THREAD

**Issue by yourealwaysbe** [jaor/xmobar#375]
This is with both the xmobar and the xmobar-git package on Arch Linux.  Version 0.29.4 in both cases.  For xmobar-git it is commit c05854f93a24ca7bdd0d73a532435f1901b05792.
Running

    xmobar -B white

with no .xmobarrc yields a bar with a black background.  Creating the following .xmobarrc
```
Config {
    bgColor = "white"
}
```
and running

    xmobar

gets the expected white background.
This looks related to #370 and commit bad2dbf52d16f00d630636f2137eac16f736b138, but the issue seems to remain.

**Comment by jaor** [comment]
flags are ignored only when there is no .xmobarrc, right?

**Comment by yourealwaysbe** [comment]
Yes, you are right -- i just tested it.  I hadn't spotted that behaviour.

**Comment by jaor** [comment]
i think i've fixed it in the master branch.  please feel free to reopen
the issue if i haven't!  thanks for the report.
