### ISSUE TITLE
Alsa plugin errors after suspend

### ISSUE THREAD

**Issue by marksauter** [jaor/xmobar#376]
The Alsa plugin produces an error after my computer suspends.
The error is displayed in the status bar: `error: ExceptionInLinkedThread ThreadId 24 fd:11: hGetChar: end of file`

Here's the Alsa portion of my config:
```
, Run Alsa "default" "Master"
	[ "--template", "Vol: <volume>% <status>"
	, "--Low",			"33"			-- units: %
	, "--High",		"66"			-- units: %
	, "--low",			"darkred"
	, "--normal",		"darkorange"
	, "--high",			"darkgreen"
	]
```

While I don't know what's causing the issue, I was wondering if there is a way to clear the error from the status bar?

**Comment by gagbo** [comment]
I confirm that I have the same bug, with a similar config :
```haskell
            -- volume indicator
            , Run Alsa "default" "Master"
                 [ "-f", "▮", "-b", "▯"
                 , "-t", "<fc=#899299>Vol:</fc> <status><fc=#899299><volume>% <volumebar></fc>"
                 , "--"
                 , "-C", "#C0E550", "-c", "#E55C50"]
```

and a similar error : `error: ExceptionInLinkedThread ThreadId 14 fd:15 hGetChar: end of file`

**Comment by jaor** [comment]
yes, the bug is very easy to reproduce. @DanielSchuessler implemented the Alsa monitor, so i would need his help here (I still use the Volume monitor, both for input and output volumes).

**Comment by gagbo** [comment]
I do use systemctl suspend. You can test it too I guess :

1) open a terminal, run `alsactl monitor` and check that it works by playing with volumes
2) open another terminal, and `systemctl suspend` (no privileges necessary)
3) when I wake up from suspend the alsactl monitor job got terminated in the first terminal

**Comment by DanielSchuessler** [comment]
The `alsactl monitor` keeps working for me after waking up, but I guess I can reproduce by terminating `alsactl` manually.

**Comment by jaor** [comment]
I've just pushed @DanielSchuessler's fix for this problem... please, @gagbo, @marksauter let us know if it is working for you. Thanks!

**Comment by gagbo** [comment]
I'll try to test it in a VM soon, I moved back to polybar after this (mostly because hs took a lot of space and I did nothing else with it yet)

**Comment by Lelio-Brun** [comment]
Hello, at least I can confirm that the fix works for me, I had the same problem.
Thanks!
