### ISSUE TITLE
Weather plugin URL obsolete again

### ISSUE THREAD

**Issue by KungFuJesus** [jaor/xmobar#378]
It appears that NOAA has deprecated the http URL in favor of an SSL one.  The URL is otherwise exactly the same, but without following the redirect to https, gets an empty body that says the following:
`<head><body> This object may be found <a HREF="https://tgftp.nws.noaa.gov/data/observations/metar/decoded/<STATION_NAME>.TXT">here</a> </body>`

**Comment by jaor** [comment]
thanks for the heads-up.  i've pushed a patch updating the url, but,
unfortunately that means for now that the plugin will only work if
compiled with the flag with_conduit (which is not set by
all_extensions), because simpleHTTP doesn't support HTTPS.
