### ISSUE TITLE
template and commands ignored when passed from command line

### ISSUE THREAD

**Issue by franalbani** [jaor/xmobar#386]
I used this to send notifications:
`$ (echo something; sleep 1) | xmobar --template '}%StdinReader%{' --commands '[Run StdinReader]'`

It worked fine for many years, but after reinstalling my Arch Linux, it stopped working.

It just shows this: Linux * Sun Apr 7 2019 06:06:50
(a default template, I guess)

```
$ xmobar --version | head -n 1
xmobar 0.29.4
```
I noticed that this problem is **not** specific to `StdinReader`; I tried many other commands/templates.

BTW, it is working fine with a config file.

**Comment by jaor** [comment]
Please try with 0.29.5, there's a bug fix related with command line
flags.

https://github.com/jaor/xmobar/releases/tag/0.29.5

**Comment by franalbani** [comment]
> Please try with 0.29.5, there's a bug fix related with command line flags. https://github.com/jaor/xmobar/releases/tag/0.29.5

Solved. :)
