### ISSUE TITLE
pickBroadest set to false keeps xmobar hidden on smallest screen but adds space for it on the broadest

### ISSUE THREAD

**Issue by mschaaf** [jaor/xmobar#387]
I want to keep xmobar on the first screen or better said on the internal laptop screen after I used for a while pickBroadest=True. After setting it to False it seems it still try to place it on the broader screen at least the behavior is what I would call a bug.
With only the first monitor (1920x1080) xmobar is placed like expected and not hidden on this monitor. If I connect now a second monitor (3840x2160) xmobar is seems gone from the first monitor because an existing window is now filling also xmobar space and the space is now visible on the second monitor but without xmobar itself.

After closing all the windows on the first monitor it shows that xmobar lays behind the window on its expected position.

I see two issues here:
1. xmobar is hidden after connecting a second monitor
2. the place for xmobar is created on the second monitor without xmobar

WM: xmonad 0.15

config:
```
        , allDesktops = True
        , pickBroadest = False
        , overrideRedirect = True
        , bgColor = "#444155"
        , fgColor = "#b8b8b8"
        , alpha = 255
        , position = TopW L 100
        , lowerOnStart = True
```

* installed xmobar version 0.29.5 via cabal

**Comment by jaor** [comment]
moved to https://codeberg.org/jao/xmobar/issues/387
