### ISSUE TITLE
Disable padding in CPU autoipat

### ISSUE THREAD

**Issue by clarkema** [jaor/xmobar#388]
I'm trying to configure xmobar on a machine with 14 cores / 28 threads, and I'd like to see some kind of CPU monitor.

Total CPU usage isn't a particularly useful metric in this case, because a single-threaded process might be bottle-necked, using all of its one CPU thread, but the total usage will still only show around 5%.

Instead, I've generated a series of xpm icons and am trying to make a little flamegraph using autoipat -- below is a sample with some artificial load.

![cpumon](https://user-images.githubusercontent.com/4311/56870942-e2e11900-6a0e-11e9-9192-547b15292e70.png)

Is there any way to remove the padding between the individual icons to make the overall effect closer to a single unified flamegraph rather than independent bars?

**Comment by jaor** [comment]
Hi Mike,

I think there's no direct way currently, but sounds like a feature we
could add via an additional configuration flag for the monitor...

**Comment by jaor** [comment]
Hi @clarkema.  At long last, i was taking a look at this, to see
what's feasible.  If you're still interested (sorry for the big delay,
btw), would you please share your concrete configuration to make the
above graph happen? Just to make sure that i fully understand the
problem.

**Comment by clarkema** [comment]
@jaor Thanks for taking a look!

My configuration is:

```
-- cpu activity monitor
, Run MultiCpu [ "--template" , "Cpu: <total><autoipat>"
    , "--Low"      , "50"         -- units: %
    , "--High"     , "85"         -- units: %
    , "--low"      , "darkgreen"
    , "--normal"   , "darkorange"
    , "--high"     , "darkred"
    , "--"
    , "--fallback-icon-pattern" , "<icon=/home/clarkema/xpm/foo_%%.xpm/>" ]
    10
```

I used this Perl to create a series of XPM icons of a suitable size:

```perl
#! /usr/bin/env perl

use warnings;
use strict;

use local::lib;
use Image::Xpm;
use POSIX;

my $width = 2;
my $height = 25;
my $pixels_per = $height / 8;

for ( my $file_num = 0; $file_num <= 8; $file_num++ ) {
    my $i = Image::Xpm->new(-file => "foo_$file_num.xpm", -width => $width, -height => $height);

    my $h = $file_num * $pixels_per;

    for ( my $x = 0; $x < $width; $x++ ) {
        for ( my $y = 0; $y < $height; $y++ ) {
            $i->xy($x, $y, "black");
        }
    }
    for ( my $x = 0; $x < $width; $x++ ) {
        for ( my $y = $height; $y >= ($height - $h); $y-- ) {
            $i->xy($x, $y, "red");
        }
    }

    $i->save;
}
```

**Comment by jaor** [comment]
Excellent, thanks for the info. I'll try on my side and see what i can
do. I like the idea of a continuous representation.

**Comment by jaor** [comment]
hi again, @clarkema, and sorry for the huge delay.  i've finally
pushed an implementation of this feature.  it's just a new flag,
`--contiguous-icons`, that one can pass in the additional arguments of
the monitor:

        , "--"
        , "--fallback-icon-pattern" , "<icon=/home/clarkema/xpm/foo_%%.xpm/>"
        , "--contiguous-icons"]

i think this fixes this issue: please let me know if it works for you
if you have a chance to try it out.  thanks!

**Comment by jaor** [comment]
has been working for me well during the last month. closing!
