### ISSUE TITLE
DateZone stuck displaying "Updating..."

### ISSUE THREAD

**Issue by dino-** [jaor/xmobar#393]
Built v0.29.5 from source on Hackage via stack unpack. stack init chose resolver lts-13.27, I included `with_datezone` and my config (that hasn't changed in years) contains:

    , Run DateZone "<fc=lightblue>%H:%M Z</fc>" "" "GMT" "utc" 10

Also tried `UTC`, same outcome, `%utc%` displays `Updating...`

    , Run DateZone "<fc=lightblue>%H:%M Z</fc>" "" "UTC" "utc" 10

Confirmed these files do exist in `/usr/share/zoneinfo` on my Arch system, and this worked the last time I built xmobar (probably a year or more ago).

Any ideas?

**Comment by dino-** [comment]
Also just built against a git clone of master here to see if this was fixed between Hackage release and now. Same behavior.

**Comment by jaor** [comment]
We haven't changed anything in this module in a vey long time, so i am
not sure why it would fail now.  I'm assuming you're compiling with the
`with_datezone` or `all_extensions` flag and you have locales installed
in your system.  Does specifying one help?

   , Run DateZone "<fc=lightblue>%H:%M Z</fc>" "en_US" "GMT" "utc" 10

or removing the `<fc=>` spec? (just to see if that's the problem for
some reason).

**Comment by dino-** [comment]
My build command, in the git cloned xmobar dir:

    stack install --flag xmobar:with_datezone --flag xmobar:with_xft --flag xmobar:with_xpm

Confirmed that I have `/usr/share/locale/en_US`. Tried all 4 of these:

    , Run DateZone "<fc=lightblue>%H:%M Z</fc>" "" "GMT" "utc" 10
    , Run DateZone "<fc=lightblue>%H:%M Z</fc>" "en_US" "GMT" "utc" 10
    , Run DateZone "%H:%M Z" "en_US" "GMT" "utc" 10
    , Run DateZone "%H:%M Z" "" "GMT" "utc" 10

No luck. It's a mystery, maybe something has changed with Arch that's causing it. I don't have a lot of time right now, but eventually I will get down in the source code, debug and report back. Thank you!

**Comment by dino-** [comment]
I tracked this down to a failure in the package `timezone-olson`. Specifically, this library can't read some (but not all) zoneinfo files on my Arch Linux system, including GMT and UTC. This issue is not with xmobar and I am closing it now.

Interestingly, these same zoneinfo files are readable with the `zdump` utility. I also observed that the `/usr/share/zoneinfo/GMT` files are different between an Arch Linux system and a Ubuntu system with the same version of tzdata installed.

Not sure what's happening, whether it's the zoneinfo files are corrupt on one of these distros or this is something that needs to be fixed in `timezone-olson`, but I'll keep investigating.

**Comment by jaor** [comment]
thanks for the update!

**Comment by tonymorris** [comment]
Any known workaround for this?

**Comment by dino-** [comment]
> Any known workaround for this?

@tonymorris 

Yes! I was just looking into it again over the past few days. I found that the library where the problem is, [timezone-olson](https://github.com/ygale/timezone-olson), has a working fix but has yet to be released to Hackage. A workaround for the moment is to build xmobar against their github commit by adding to xmobar's existing `stack.yaml` `extra-deps` stanza:

    extra-deps:
    - iwlib-0.1.0
    - libmpd-0.9.0.10
    - git: https://github.com/ygale/timezone-olson
      commit: 4ff152bd4f5e1949ec31834b87a5b19aff8a04b0

Also, for the curious, here's a [link](https://github.com/ygale/timezone-olson/commit/4ff152bd4f5e1949ec31834b87a5b19aff8a04b0) to the commit that fixes the problem.

**Comment by tonymorris** [comment]
Yes thanks, I found the same solution and can confirm that it works.
