### ISSUE TITLE
using `stack ghc` instead of `ghc` for on-demand plugin compilation

### ISSUE THREAD

**Issue by maxthomas** [jaor/xmobar#397]
According to [this section of the README](https://github.com/jaor/xmobar#using-a-plugin):

> When xmobar runs with the full path to that Haskell file as its argument (or if you put it in ~/.config/xmobar/xmobar.hs), and with the xmobar library installed, the Haskell code will be compiled as needed, and the new executable spawned for you.

using a working `xmobar` binary:

```shell
[max@ll3] ~/.xmonad/xmobar (master) ⚡
❯ xmobar $XDG_CONFIG_HOME/xmobar/clean.hs
xmobar: ghc: runProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

i'm guessing i need `ghc` on my path? i happen to be using stack exclusively.

also tried this, same error:

```
[max@ll3] ~/.xmonad/xmobar (master) ⚡
❯ alias ghc='stack ghc' && xmobar $XDG_CONFIG_HOME/xmobar/clean.hs                                                                               ⏎
xmobar: ghc: runProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

two questions:
1. is this due to GHC not being on the `$PATH` or something else?
1. is there any way to substitute `stack ghc` in here? what sort of effort would be required to do this if not?

**Comment by maxthomas** [comment]
this seems to work OK if i do the process out of band:

```sh
[max@ll3] ~/.xmonad/xmobar-mm (initial-wip) ⚡
❯ stack ghc -- app/xmobar.hs
[1 of 1] Compiling Main             ( app/xmobar.hs, app/xmobar.o )
Linking app/xmobar ...
[max@ll3] ~/.xmonad/xmobar-mm (initial-wip) ⚡
❯ xmobar ./app/xmobar.hs
```
which works and shows my plugin

**Comment by jaor** [comment]
the standard way is to have a "build" executable script in the same
directory as xmobar.hs, and then xmobar should use it to re-compile
itself, instead of calling plain ghc.  something along the lines of:

```shell
#!/bin/sh
exec stack ghc -- \
  --make xmobar.hs \
  -i \
  -ilib \
  -fforce-recomp \
  -main-is main \
  -v0 \
  -o "$1"
```

(i'm copying this from a build script for xmonad, have no access to my
usual computer right now, so i might be getting some detail wrong)

**Comment by maxthomas** [comment]
ahhh okay, i'll look into this. thanks for the reply, much appreciated!
