### ISSUE TITLE
ghc 8.8.1 support

### ISSUE THREAD

**Issue by peti** [jaor/xmobar#413]
Is there any particular reason why xmobar constrains `base` to `>=4.9.1.0 && <4.13`? This choice prevents user of `ghc-8.8.1` from building the package, but when I just ignore the upper bound then the build succeeds just fine.

**Comment by jaor** [comment]
On Thu, Dec 05 2019, Peter Simons wrote:

> Is there any particular reason why xmobar constrains base to >=4.9.1.0
> && <4.13? This choice prevents user of ghc-8.8.1 from building the

the current master has `<4.14`, so it should compile fine with ghc
8.8.x, i think.  i'll make a new release soon.

**Comment by peti** [comment]
Will you make a new release?

**Comment by jaor** [comment]
0.32 was released a few days ago, should include the above if i didn't misunderstand...
