### ISSUE TITLE
[Advice needed] Battery Monitor plugin for FreeBSD

### ISSUE THREAD

**Issue by dbalan** [jaor/xmobar#415]
The `Battery` plugin doesn't work on FreeBSD. The plugin parses `sysfs` entries to get data which doesn't exist on FreeBSD. 

So a working `Battery` plugin on FreeBSD would have to query `sysctl` entries to work:

```
hw.acpi.battery.units: 1
hw.acpi.battery.state: 1
hw.acpi.battery.rate: 24076
hw.acpi.battery.time: 186
hw.acpi.battery.life: 90
```
If one were to add support for FreeBSD battery monitor, should this be a seperate plugin `FreeBSDBattery` or is there a way to integrate with current Battery plugin?

**Comment by jaor** [comment]
there's no pre-defined way to integrate new batteries to the current
plugin, other than the fact that there's probably lots of code that can
be shared.  ideally, we would have just one plugin that would detect
automatically where it has to look for the info, but if that gets hairy
or makes the code more difficult to maintain or understand, there's
nothing wrong in a separate FreeBSDBattery (which could then be a
compilation option, i guess)...

**Comment by dbalan** [comment]
Thanks @jaor I'll check if I can integrate the code into the current module if not I'll create a new one.
