### ISSUE TITLE
Battery shows "-0, 0% / 0:00" for  "rk-bat" pinebook pro

### ISSUE THREAD

**Issue by btrepp** [jaor/xmobar#424]
Seems my arm device might not have what's needed for xmobar to display battery info.

```
 cat /etc/debian_version 
9.9
```
```
 uname -a
Linux Debian-Desktop 4.4.210 #1 SMP Tue Jan 14 22:28:43 EST 2020 aarch64 GNU/Linux
```
```
Config { font = "-misc-fixed-*-*-*-*-10-*-*-*-*-*-*-*"
       , borderColor = "black"
       , border = TopB
       , bgColor = "black"
       , fgColor = "grey"
       , position = Top
       , lowerOnStart = True
       , commands = [ Run Weather "YPPH" ["-t","<station>: <tempC>C","-L","18","-H","25","--normal","green","--high","red","--low","lightblue"] 36000
                    , Run Wireless "wlan0" [ "-t", "<essid>" ] 10
                    , Run MultiCpu ["-L","3","-H","50","--normal","green","--high","red"] 10
                    , Run Memory ["-t","Mem: <usedratio>%"] 10
                    , Run Swap [] 10
		    , Run BatteryP ["rk-bat"] [ "-L","10","-H","100","--low","red","--high","green"] 10
                    , Run Com "uname" ["-s","-r"] "" 36000
    		    , Run Date "%a %b %_d %Y %H:%M:%S" "date" 10
	            , Run StdinReader
                    ]
       , sepChar = "%"
       , alignSep = "}{"
       , template = "%StdinReader% | %multicpu% | %memory% | %swap% | %wlan0wi% - %battery%}{<fc=#ee9a00>%date%</fc>| %YPPH% | %uname%"
       }
```

```
ls -laH /sys/class/power_supply/      
total 0
drwxr-xr-x  2 root root 0 Jan 23 18:04 .
drwxr-xr-x 80 root root 0 Jan 23 17:26 ..
lrwxrwxrwx  1 root root 0 Jan 23 17:26 dc-charger -> ../../devices/platform/dc-charger/power_supply/dc-charger
lrwxrwxrwx  1 root root 0 Jan 23 17:59 rk-bat -> ../../devices/platform/ff3d0000.i2c/i2c-4/4-0062/power_supply/rk-bat
lrwxrwxrwx  1 root root 0 Jan 23 17:26 universal_usb -> ../../devices/platform/usb-charger/power_supply/universal_usb
```
This makes me think rk-bat is the closest to the what we need for battery

```
 ls -laH /sys/class/power_supply/rk-bat
total 0
drwxr-xr-x 3 root root    0 Jan 23 18:02 .
drwxr-xr-x 3 root root    0 Jan 23 17:26 ..
-r--r--r-- 1 root root 4096 Jan 23 17:33 capacity
-r--r--r-- 1 root root 4096 Jan 23 17:33 charge_counter
-r--r--r-- 1 root root 4096 Jan 23 17:33 charge_full
-r--r--r-- 1 root root 4096 Jan 23 17:33 current_now
lrwxrwxrwx 1 root root    0 Jan 23 17:33 device -> ../../../4-0062
-r--r--r-- 1 root root 4096 Jan 23 17:33 health
drwxr-xr-x 2 root root    0 Jan 23 17:33 power
-r--r--r-- 1 root root 4096 Jan 23 17:33 present
-r--r--r-- 1 root root 4096 Jan 23 17:33 status
lrwxrwxrwx 1 root root    0 Jan 23 17:26 subsystem -> ../../../../../../../class/power_supply
-r--r--r-- 1 root root 4096 Jan 23 17:33 technology
-r--r--r-- 1 root root 4096 Jan 23 17:33 temp
-r--r--r-- 1 root root 4096 Jan 23 17:33 time_to_empty_now
-r--r--r-- 1 root root 4096 Jan 23 17:33 type
-rw-r--r-- 1 root root 4096 Jan 23 17:26 uevent
-r--r--r-- 1 root root 4096 Jan 23 17:33 voltage_now
```

I take it from this that some files required are missing?. 
What is required for the xmobar battery plugin?

**Comment by slotThe** [comment]
Glancing over the code, xmobar seems to look for either `charge_now` or `energy_now` for the current battery status, neither of which seem to be present for you.  Which of these files indicates the current status in your case? `present`?

**Comment by paulfertser** [comment]
@btrepp , please show ''grep . /sys/class/power_supply/*/uevent'' . And link to the battery driver source for your platform please.

**Comment by aragaer** [comment]
I'm having the same issue on debian. Here's the grep result:
```
/sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_NAME=cw2015-battery
/sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_CAPACITY=44
/sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_STATUS=Discharging
/sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_PRESENT=1
/sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_VOLTAGE_NOW=3703000
/sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_TIME_TO_EMPTY_NOW=239
/sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_TECHNOLOGY=Li-ion
/sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_CHARGE_COUNTER=0
/sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_CHARGE_FULL=9800000
/sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_CHARGE_FULL_DESIGN=9800000
/sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_CURRENT_NOW=1082510
/sys/class/power_supply/dc-charger/uevent:POWER_SUPPLY_NAME=dc-charger
/sys/class/power_supply/dc-charger/uevent:POWER_SUPPLY_ONLINE=0
/sys/class/power_supply/tcpm-source-psy-4-0022/uevent:POWER_SUPPLY_NAME=tcpm-source-psy-4-0022
/sys/class/power_supply/tcpm-source-psy-4-0022/uevent:POWER_SUPPLY_USB_TYPE=[C] PD PD_PPS
/sys/class/power_supply/tcpm-source-psy-4-0022/uevent:POWER_SUPPLY_ONLINE=0
/sys/class/power_supply/tcpm-source-psy-4-0022/uevent:POWER_SUPPLY_VOLTAGE_MIN=0
/sys/class/power_supply/tcpm-source-psy-4-0022/uevent:POWER_SUPPLY_VOLTAGE_MAX=0
/sys/class/power_supply/tcpm-source-psy-4-0022/uevent:POWER_SUPPLY_VOLTAGE_NOW=0
/sys/class/power_supply/tcpm-source-psy-4-0022/uevent:POWER_SUPPLY_CURRENT_MAX=0
/sys/class/power_supply/tcpm-source-psy-4-0022/uevent:POWER_SUPPLY_CURRENT_NOW=0
```
I don't really know where to find the source of the driver though but it's likely that the current status is either `current_now` or `voltage_now`. There is also `time_to_empty_now`

**Comment by paulfertser** [comment]
Hi,

On Thu, Jun 17, 2021 at 07:34:54AM -0700, Ilya Konovalov wrote:
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_NAME=cw2015-battery
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_CAPACITY=44
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_STATUS=Discharging
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_PRESENT=1
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_VOLTAGE_NOW=3703000
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_TIME_TO_EMPTY_NOW=239
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_TECHNOLOGY=Li-ion
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_CHARGE_COUNTER=0
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_CHARGE_FULL=9800000
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_CHARGE_FULL_DESIGN=9800000
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_CURRENT_NOW=1082510

Now this is useful info!

Please also give your BatteryP parameters from the config. Do you have
["cw2015-battery"] as the first argument?

Offtopic question: do you by any chance know if Pinebook Pro can be
shipped to Russia officially?

-- 
Be free, use free (http://www.gnu.org/philosophy/free-sw.html) software!
***@***.***

**Comment by jaor** [comment]
> I'm having the same issue on debian. Here's the grep result:

what's the contents of the directory
/sys/class/power_supply/cw2015-battery/? i take it you're configuring
the monitor with `BatteryP ["cw2015-battery"] [...]`?

> I don't really know where to find the source of the driver though but
> it's likely that the current status is either current_now or
> voltage_now. There is also time_to_empty_now

you can see all the files the monitor reads here:

   https://github.com/jaor/xmobar/blob/master/src/Xmobar/Plugins/Monitors/Batt.hs#L193

we read either charge_now or energy_now, either power_now or
current_now, voltage_now and status.

**Comment by aragaer** [comment]
> what's the contents of the directory /sys/class/power_supply/cw2015-battery/? i take it you're configuring the monitor with `BatteryP ["cw2015-battery"] [...]`?

I'm using `Run BatteryN ["cw2015-battery"] ["-t", "<left>% <timeleft>"] 60 "battery"` actually.
```

$ ls -1 /sys/class/power_supply/cw2015-battery/
capacity
charge_counter
charge_full
charge_full_design
current_now
device
hwmon4
power
present
status
subsystem
technology
time_to_empty_now
type
uevent
voltage_now
wakeup8
```

> Offtopic question: do you by any chance know if Pinebook Pro can be shipped to Russia officially?
I am not sure about official shipment, I've used a 3rd party shipping service myself.

**Comment by paulfertser** [comment]
Hello,

On Thu, Jun 17, 2021 at 07:34:54AM -0700, Ilya Konovalov wrote:
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_NAME=cw2015-battery
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_CAPACITY=44
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_STATUS=Discharging
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_PRESENT=1
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_VOLTAGE_NOW=3703000
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_TIME_TO_EMPTY_NOW=239
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_TECHNOLOGY=Li-ion
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_CHARGE_COUNTER=0
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_CHARGE_FULL=9800000
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_CHARGE_FULL_DESIGN=9800000
> /sys/class/power_supply/cw2015-battery/uevent:POWER_SUPPLY_CURRENT_NOW=1082510

OK, so it's pretty clear this battery driver version doesn't report
the values expected to calculate estimations of discharge and charge
times. This is going to be fixed with

https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=bf3841073bf34

Of course, you can implement same idea (calculating charge_now from
capacity and charge_full) in the battery monitor itself but I'm not
sure if that's useful provided the kernel should be reporting sane
values in the first place. I guess Jao will comment if such a patch
would be nice to have or not.

**Comment by paulfertser** [comment]
On Fri, Jun 18, 2021 at 03:12:01PM +0300, Paul Fertser wrote:
> Of course, you can implement same idea (calculating charge_now from
> capacity and charge_full)

I noticed it's not actually the same, and sent a question to the patch
author: https://patchwork.kernel.org/comment/24260443/ . Feel free to
contribute your input.

**Comment by aragaer** [comment]
Can we use the "capacity" and "time_to_empty_now" directly instead? Looks like these are battery charge percentage and time to empty in minutes.

**Comment by jaor** [comment]
On Wed, Jul 21 2021, Ilya Konovalov wrote:

> Can we use the "capacity" and "time_to_empty_now" directly instead?
> Looks like these are battery charge percentage and time to empty in
> minutes.

we could, but the current code really wants those values to be computed
from power consumption, so we should probably introduce a new
alternative monitor that used that information (together with the rest
of other available parameters) rather than trying to generalize the
current one (which is already too convoluted) to also accommodate this
case.

(in my system time_to_empty_now doesn't exist, and i don't know if
capacity is present for all kernels, so unfortunately we cannot either
just use those files always).

summarizing: doable, but not trivial :)

**Comment by paulfertser** [comment]
> summarizing: doable, but not trivial :)

My offer is still valid:

"
My userspace is Xmobar and I'm ready to fix it for Pinebook Pro users
if you remove reporting of the fake data.
"

**Comment by jaor** [comment]
On Thu, Jul 22 2021, Paul Fertser wrote:

>> summarizing: doable, but not trivial :)
>
> My offer is still valid:
>
> "
> My userspace is Xmobar and I'm ready to fix it for Pinebook Pro users
> if you remove reporting of the fake data.
> "

sorry, i lack context here (or forgot it): could you please remind me
what does "removing reporting of the fake data" exactly mean?

**Comment by paulfertser** [comment]
> >> summarizing: doable, but not trivial :)
> >
> > My offer is still valid:
> >
> > "
> > My userspace is Xmobar and I'm ready to fix it for Pinebook Pro users
> > if you remove reporting of the fake data.
> > "
> 
> sorry, i lack context here (or forgot it): could you please remind me
> what does "removing reporting of the fake data" exactly mean?

Sure, that was a quote from my mail to the kernel driver maintainer
who said fake (and misleading!) data should be present in
power_supply/ to make some battery widgets happy and I insisted it's
up to the userspace to behave in a sane way, and that I'm willing to
do this for the userspace I like and care about. The full discussion
is visible on the Patchwork; I would like to highlight the fact no
real users participated.

**Comment by jaor** [comment]
On Thu, Jul 22 2021, Paul Fertser wrote:

> Sure, that was a quote from my mail to the kernel driver maintainer
> who said fake (and misleading!) data should be present in
> power_supply/ to make some battery widgets happy and I insisted it's
> up to the userspace to behave in a sane way, and that I'm willing to
> do this for the userspace I like and care about.

Ah, thanks for the clarification: i was under the impression that that
"you" in your quote was xmobar and was wondering where it was producing
fake data.  

FWIW, i also fail to understand how reporting fake or misleading data
can help in any way; quite the contrary.

**Comment by jaor** [comment]
moved to https://codeberg.org/jao/xmobar/issues/424
