### ISSUE TITLE
[Advise needed] Coloring output from external commands

### ISSUE THREAD

**Issue by roper79** [jaor/xmobar#425]
Imagine the following external command:
`Run Com "noOfMails.sh" [] "mails" 120`
that returns (with echo) the number of new e-mails in the inbox. I would like to have the output red if the number >0. 

External commands do not support the thresholds & terminal escape codes are not interpreted.

Thanks a lot for help!

**Comment by jaor** [comment]
On Sat, Jan 25 2020, Robert Pergl wrote:

> Imagine the following external command: Run Com "noOfMails.sh" []
> "mails" 120 that returns (with echo) the number of new e-mails in the
> inbox. I would like to have the output red if the number >0.
>
> External commands do not support the thresholds & terminal escape
> codes are not interpreted.

You can make them output something like `<fc=red>3</fc>`, instead of
just `3`.  I'm afk and cannot check right now, but i  think that should
work.

**Comment by roper79** [comment]
Thank you very much @jaor  for your prompt answer, this solves the issue perfectly!
