### ISSUE TITLE
xmobar parse error when "Run Wireless" is used

### ISSUE THREAD

**Issue by bitounu** [jaor/xmobar#426]
I made very simple configuration file for xmobar:
```
Config { font = "-*-Fixed-Bold-R-Normal-*-26-*-*-*-*-*-*-*"
       , bgColor = "black"
       , fgColor = "grey"
       , position = TopW L 90
       , lowerOnStart = True
       , commands = [
                    Run Wireless "wlan0" [] 10
                    ]
       , sepChar = "%"
       , alignSep = "**"
       , template = " * %wlan0wi% * "
       }
```
When I try to run xmobar I get:
Invalid configuration file: "Config" (line 9, column 10):
unexpected "s"
expecting space or "Run"
(No compilation attempted: only .hs, .hsc or .lhs files are compiled)

Line 9 is: 
, sepChar = "%"

xmobar was compiled from source this way:
```
git clone git://github.com/jaor/xmobar
cd xmobar
sudo cabal install -fall_extensions
```
I have iwlib installed:
`dpkg -l | grep -i iwlib`
ii  libghc-iwlib-dev                                            0.1.0-3+b2                           amd64
`ldconfig -p | grep -i libiw`
libiw.so.30 (libc6,x86-64) => /lib/x86_64-linux-gnu/libiw.so.30
libiw.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libiw.so

When I change "Wireless" to "Network" or "DynNetwork" configuration file is parsed. Looks like xmobar do not understand "Wireless" statement.

**Comment by jaor** [comment]
hmm. that error only happens when there's no support for the given
monitor at compile time.  are you sure there is no other xmobar in your
path?

you can also try givin it some parameters, say `["-t" , "<essid>
<quality>"]`, maybe we have a bug with the empty list somewhere...

**Comment by PolymathArtisan** [comment]
You need to recompile xmobar with the `with_iwlib`flag. [The documentation says](https://xmobar.org/#wireless-interface-args-refreshrate) that this is required for use of the Wireless plugin.

**Comment by TWB0109** [comment]
> You need to recompile xmobar with the `with_iwlib` flag. [The documentation says](https://xmobar.org/#wireless-interface-args-refreshrate) that this is required for use of the Wireless plugin.

Not the OP, but it doesn't seem to work. Here's my xmobar-git (AUR) PKGBUILD build() function:
```
build() {
  cd ${pkgname}
  runhaskell setup configure -O \
    --enable-shared \
    --prefix=/usr \
    --enable-executable-dynamic \
    --disable-library-vanilla \
    --flags="with_utf8 with_xft with_iwlib with_xpm with_inotify with_dbus with_mpris"
  runhaskell setup build
}
```
Have also tried with ```--flags="all_extensions"``` and it doesn't work either

**Comment by oogeek** [comment]
> You need to recompile xmobar with the `with_iwlib` flag. [The documentation says](https://xmobar.org/#wireless-interface-args-refreshrate) that this is required for use of the Wireless plugin.

Yes. I have encountered the same issue and with this flag set, the issue is resolved.
