### ISSUE TITLE
It's possible show low battery warning with notify-send only when below a certain percentage and NOT charging?

### ISSUE THREAD

**Issue by ltsdw** [jaor/xmobar#430]
Like:

`"-a", "notify-send -u critical 'Low battery!'", "-A", "15"`

And let's say that current battery percentage is 5%, it will notify until get 16%. I already tried **-t** option of notify-send, but it will only set a timeout to the current message, another one will spawn after timeout.

So, it's possible stop the messages if connected to charger?

**Comment by jaor** [comment]
On Tue, Feb 25 2020, ltsdw wrote:

> Like:
>
> "-a", "notify-send -u critical 'Low battery!'", "-A", "15"

i use a very similar setting, and the notifications stop the moment the
battery starts charging again (i implemented this feature with that
requirement in mind).  maybe for some reason in your system the charging
status is not recognised?

**Comment by ltsdw** [comment]
I don't know, but it's possible, how that is checked?
For example, the **-O** option detect when I connect charger, `acpi -V` also shows when I have charger connected.

**Comment by jaor** [comment]
On Tue, Feb 25 2020, ltsdw wrote:

> I don't know, but it's possible, how that is checked?

you can use `<acstatus>` and `<watts>` in your monitor template and see
if that's reporting a correct status and a positive watts value when
plugged.

**Comment by ltsdw** [comment]
So... `<acstatus>` is reporting the correct status (with "On" while connected to charger, that's the **-O** of xmobarrc), and `<watts>` report the value `-0` while on charger. I think it's ok.

**Comment by jaor** [comment]
On Tue, Feb 25 2020, ltsdw wrote:

> So... <acstatus> is reporting the correct status (with "On" while
> connected to charger

i took a look at the code, and we have:

       unless ac (maybeAlert opts left)

where ac is a boolean, and is the same variable that decides to print
"On", and maybeAlert is the function displaying the warning.  so i don't
really see how ac can be False and status On...  what OS are you using?

**Comment by ltsdw** [comment]
> what OS are you using?

OS: Arch Linux x86_64

**Comment by jaor** [comment]
On Tue, Feb 25 2020, ltsdw wrote:

>     what OS are you using?
>    
> OS: Arch Linux x86_64

then i'm afraid i've ran out of ideas.  afaict, it's impossible that
you're seeing "On" and, at the same time, an increasing number of
notifications (i typically have a bunch of them when i plug in,
accumulated during whatever period the battery has been below the
threshold, but they stop appeared as soon as the ac is on).

maybe some exception is wreaking havoc, but i don't see how.  we get the
information on the AC status from the file

  /sys/class/power_supply/AC/online 

does that file exist for you and contain 1 when the AC is on?

**Comment by ltsdw** [comment]
> does that file exist for you and contain 1 when the AC is on?

Actually the path is a bit different, /sys/class/power_supply/ACAD/online, and yes, it gives me a 1 when charging.

**Comment by jaor** [comment]
On Tue, Feb 25 2020, ltsdw wrote:

>     does that file exist for you and contain 1 when the AC is on?
>    
> Actually the path is a bit different, /sys/class/power_supply/ACAD/online, and yes, it gives me a 1 when
> charging.

then try to configure onlineFile in your monitor, with the option (after
"--") "-f":

       "-f", "ACAD/online"

does that help?  (even though i would have thought that if you're seeing
"On" you must already be using that)

**Comment by ltsdw** [comment]
> then try to configure onlineFile in your monitor, with the option (after
> "--") "-f":
> 
>        "-f", "ACAD/online"
> 
> does that help?  (even though i would have thought that if you're seeing
> 
> "On" you must already be using that)

There it is! I did tried "-f" before, but I've misread the docmantation and used `"-f", "/sys/class/power_supply"`. Solved :)

**Comment by jaor** [comment]
thanks for your patience.  i'll take a further look, because when we
don't find the online file we should be reporting "N/A" instead of
"On".  at least it's working for you now.
