### ISSUE TITLE
High CPU throttling of xmobar

### ISSUE THREAD

**Issue by psibi** [jaor/xmobar#438]
Versions:
* xmobar version: 0.33
* Linux kernel: 5.3.0

The high CPU throttling starts after  some minutes of starting the system (I can hear my CPU fans after some time). I can confirm by using `htop` that it is actually `xmobar` which is having high CPU usage. I disable various flags like weather, utf8 but even then the high CPU usage occurred. Let me know if more information is needed.

**Comment by jaor** [comment]
well, your config, and os, perhaps?

for xmobar, a minimal one that reproduces the behaviour, removing as
many monitors as possible, would help.  also your window manager, its
version...

**Comment by psibi** [comment]
This is my xmobar config:
```
Config { font = "xft:Ubuntu Mono:size=12:bold:antialias=true"
       , bgColor = "black"
       , fgColor = "grey"
       , position = TopW L 100
       , lowerOnStart = False
       , hideOnStart = False
       , overrideRedirect = True
       , allDesktops = True
       , commands = [
                      Run Cpu ["-L","3","-H","50","--normal","green","--high","red"] 10
                    , Run Memory ["-t","Mem: <usedratio>%"] 10
                    , Run Swap [] 10
                    , Run Battery ["-t","<left>","-L","30","-H","70","--low", "red","--normal","yellow","--high","green"] 10
                    , Run Date "%a %b %_d %l:%M" "date" 10
                    , Run StdinReader
                    ]
       , sepChar = "%"
       , alignSep = "}{"
       , template = "%StdinReader% }{ | %cpu% | %memory% * %swap% * %battery% | <fc=#ee9a00>%date%</fc>"
       }
```
OS is ubuntu although I'm managing my xmobar dependency via nix. Using xmonad `0.15` (again the `xmonad` is being managed via nix. There is only a single monitor. I tried to get an strace log while the CPU was in full throttle mode:
https://gist.github.com/psibi/f522b5d0b4647fbdf5e724b13df58294

Let me know if you need anything more.

**Comment by psibi** [comment]
Also, I'm planning to spend more time debugging this the coming weekend. So, let me know if you have any suspicious code paths. I will try to start from there. Thanks!

**Comment by jaor** [comment]
> This is my xmobar config:
>
> Config { font = "xft:Ubuntu Mono:size=12:bold:antialias=true"
>        , bgColor = "black"
>        , fgColor = "grey"
>        , position = TopW L 100
>        , lowerOnStart = False
>        , hideOnStart = False
>        , overrideRedirect = True
>        , allDesktops = True
>        , commands = [
>                       Run Cpu ["-L","3","-H","50","--normal","green","--high","red"] 10
>                     , Run Memory ["-t","Mem: <usedratio>%"] 10
>                     , Run Swap [] 10
>                     , Run Battery ["-t","<left>","-L","30","-H","70","--low", "red","--normal","yellow","--high","green"] 10
>                     , Run Date "%a %b %_d %l:%M" "date" 10
>                     , Run StdinReader
>                     ]
>        , sepChar = "%"
>        , alignSep = "}{"
>        , template = "%StdinReader% }{ | %cpu% | %memory% * %swap% * %battery% | <fc=#ee9a00>%date%</fc>"
>        }
>
> OS is ubuntu although I'm managing my xmobar dependency via nix. Using xmonad 0.15 (again the xmonad is being
> managed via nix. There is only a single monitor.

hmm, which one? in the config above you show 6?

**Comment by psibi** [comment]
I guess I'm missing something here. Is there any specific field in the
configuration which tells that there are six monitors being used?

**Comment by jaor** [comment]
On Mon, Apr 20 2020, Sibi Prabakaran wrote:

> I guess I'm missing something here. Is there any specific field in the
> configuration which tells that there are six monitors being used?

in `commands` and in

    , template = "%StdinReader% }{ | %cpu% | %memory% * %swap% * %battery% |

you're using Stdinreader, cpu, memory, swap, battery, date, all of them
in `commands`.  the idea would be to start with a minimal commands list
(and corresponding template), and add them one by one until the bad
behaviour is reproduced.

btw, what ghc version are you using? and are you compiling using stack
or cabal?

**Comment by psibi** [comment]
Thanks, I will try to reproduce by adding one by one.

> btw, what ghc version are you using? and are you compiling using stack
or cabal?
I'm using 8.6. I'm using `nix-build` which in turn seems to use Cabal.

> you're using Stdinreader, cpu, memory, swap, battery, date, all of them
in `commands`
I'm guess I'm still not understanding this properly. Can't a single screen use all those commands ? I re-read the xmobar documentation and I don't see anything specifically where it's mentioned that having 6 command would mean having 6 monitors. Probably I'm understanding something wrong here ?

**Comment by psibi** [comment]
@jaor Okay, I think I have a fairly minimum configuration for reproducing it. This one didn't show any problems:
```
Config { font = "xft:Ubuntu Mono:size=12:bold:antialias=true"
       , bgColor = "black"
       , fgColor = "grey"
       , position = TopW L 100
       , lowerOnStart = False
       , hideOnStart = False
       , overrideRedirect = True
       , allDesktops = True
       , commands = [
                    Run Date "%a %b %_d %l:%M" "date" 10
                    ]
       , sepChar = "%"
       , alignSep = "}{"
       , template = "<fc=#ee9a00>%date%</fc>"
       }
```

But modifying it to add `StdinReader` started showing the issue:
```
Config { font = "xft:Ubuntu Mono:size=12:bold:antialias=true"
       , bgColor = "black"
       , fgColor = "grey"
       , position = TopW L 100
       , lowerOnStart = False
       , hideOnStart = False
       , overrideRedirect = True
       , allDesktops = True
       , commands = [
                     Run StdinReader
                    , Run Date "%a %b %_d %l:%M" "date" 10
                    ]
       , sepChar = "%"
       , alignSep = "}{"
       , template = "%StdinReader% | <fc=#ee9a00>%date%</fc>"
       }
```

**Comment by jaor** [comment]
thanks... so seems to be something in StdinReader, possibly in the way
xmonad launches it.  i don't use xmonad myself these days, but could you
share that part of your config?

**Comment by psibi** [comment]
@jaor This is the full xmonad configuration: https://github.com/psibi/dotfiles/blob/1252ee48ab94e33b495615b443e63782ebd592c2/xmonad/xmonad.hs#L1

But I think this is only the relevant part of the xmobar configuration there:
```
main :: IO ()
main = do
  xmproc <- spawnPipe "xmobar"
  xmonad $
    withUrgencyHook
      NoUrgencyHook
      def
        { 
         logHook =
            dynamicLogWithPP
              xmobarPP
                { ppOutput = hPutStrLn xmproc
                , ppTitle = xmobarColor "green" "" . shorten 50
                , ppUrgent = xmobarColor "yellow" "red" . xmobarStrip
                }
```

**Comment by jaor** [comment]
hmm, i don't see anything specially strange... have you tried without
the urgency hook?

**Comment by psibi** [comment]
No, not yet. I will debug this further the coming weekend. Thanks for your help so far!

**Comment by psibi** [comment]
The issue was solved by me by adding the following environment variable:
```
export LOCALE_ARCHIVE="/usr/lib/locale/locale-archive"
```
Also, we have patched xmobar to disallow such busy looping happening in future: https://github.com/jaor/xmobar/pull/439
