### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by iksbat** [jaor/xmobar#447]
When looking at the current documentation there are many things that are not explained in detail. In fact I had to use a lot of trial & error to understand the specific syntax. One example:

> ``<action=`command` button=12345>`` will execute given command when clicked with specified buttons. If not specified, button is equal to 1 (left mouse button). Using old syntax (without backticks surrounding command) will result in button attribute being ignored.

It does not tell you
1. what the syntax for the buttons is in detail: am I allowed to specify multiple? 
2. What restrictions are there for the command? Can you escape? how?

Basically, it is *definition by example*. And examples are a good thing, but in my eyes they do need a formal definition. So I suggest to refactor the whole documentation. Moreover adding a manual page for the configuration would be a nice thing to make it easier for users to find the version specific options.

**Comment by slotThe** [comment]
I will note that writing a manpage for xmobar has been on my TODO list for quite some time.  However, in a man page it's obviously best to only discuss the settings that one can actually set through the CLI of the program.

As for updates to the actual documentation, I would agree that that's very necessary in some parts.  I can imagine these kinds of contributions would be most welcome!

**Comment by iksbat** [comment]
> I will note that writing a manpage for xmobar has been on my TODO list for quite some time. However, in a man page it's obviously best to only discuss the settings that one can actually set through the CLI of the program.

That is correct and wrong at the same time. But before elaborating this, I have to confess: I have no idea about man files, its sections, format, and that stuff. I just type `man topic` to get information about a topic.

What is correct is that `man xmobar` should only be talking about the CLI. I agree. But: other programs like for example `zathura`, do not only provide one man page. `zathura` has a man page for the cli (`man zathura`) and one only for the configuration (`man zathurarc`). In my eyes, this is the best approach.

> As for updates to the actual documentation, I would agree that that's very necessary in some parts. I can imagine these kinds of contributions would be most welcome!

I can imagine to _help_ to update the current documentation and maybe also to create another man for the config file. But I am afraid that I cannot do this alone, because my flow would constantly raise questions whose answer I cannot give myself. If there is some place to get those answered or somebody willing to be a contact person for that, I am sure I can slowly go through it (my time is limited, nevertheless I want to invest a few hours a month into contributions)

**Comment by jaor** [comment]
On Tue, May 19 2020, iksbat wrote:

>     I will note that writing a manpage for xmobar has been on my TODO
>     list for quite some time. However, in a man page it's obviously
>     best to only discuss the settings that one can actually set
>     through the CLI of the program.
>    
> That is correct and wrong at the same time. But before elaborating
> this, I have to confess: I have no idea about man files, its sections,
> format, and that stuff. I just type man topic to get information about
> a topic.
>
> What is correct is that man xmobar should only be talking about the
> CLI. I agree. But: other programs like for example zathura, do not
> only provide one man page. zathura has a man page for the cli (man
> zathura) and one only for the configuration (man zathurarc). In my
> eyes, this is the best approach.

if man pages is what we want, i agree.  although i'm thinking it might
be a better idea to have a format that we can publish easily, for
instance, at xmobar.org (that's a domain with a server behind under my
control).  perhaps we can use pandoc to generate both man and html from
a single source format? (i'm very comfortable with org mode, but of
course markdown or other text-based ones, if preferred, are okay too).

>     As for updates to the actual documentation, I would agree that
>     that's very necessary in some parts. I can imagine these kinds of
>     contributions would be most welcome!
>    

> I can imagine to help to update the current documentation and maybe
> also to create another man for the config file. But I am afraid that I
> cannot do this alone, because my flow would constantly raise questions
> whose answer I cannot give myself. If there is some place to get those
> answered or somebody willing to be a contact person for that, I am
> sure I can slowly go through it (my time is limited, nevertheless I
> want to invest a few hours a month into contributions)

i'll very gladly review and comment, if you send them, for instance, as
PRs here (and be very grateful for them :) right now, i'm afraid the
ultimate reference is the code, but i can help looking at it.  and i'm
sure other contributors will chime in every know and then and help too.

what do you think?

**Comment by iksbat** [comment]
> if man pages is what we want, i agree.  although i'm thinking it might
> be a better idea to have a format that we can publish easily, for
> instance, at xmobar.org (that's a domain with a server behind under my
> control).  perhaps we can use pandoc to generate both man and html from
> a single source format? (i'm very comfortable with org mode, but of
> course markdown or other text-based ones, if preferred, are okay too).

I do not know "org mode" tbh O:) But yeah, I would definitly not want to have some uncontrolled redundancy here. And as I just discovered, this is possible with `ronn` and even better, with `pandoc` (maybe you knew that already, but hey, I did not).

> i'll very gladly review and comment, if you send them, for instance, as PRs here (and be very 
> grateful for them :) right now, i'm afraid the
> ultimate reference is the code, but i can help looking at it.  and i'm
> sure other contributors will chime in every know and then and help too.

The only thing I am trying to avoid is reading code that I did not write :D 

> what do you think?

Sounds good (Y)

**Comment by jaor** [comment]
we rewrote our docs in org, and have been reorganizing and hopefully improving them for a while, so i am closing this issue.  we can of course open new ones for the new docs! :)
