### ISSUE TITLE
Com (command) plugin not working with .hs compiled config

### ISSUE THREAD

**Issue by samuelhnrq** [jaor/xmobar#449]
The com plugin stops working when it needs to compile the .hs config file first.

I've compiled this from source (cabal install on local clone) because I wanted to use the .hs style configuration file and arch's distribution of xmobar doesn't register the library along the binary (xmobar doesn't show up on ghc-pkg like xmonad, can't `import`). 

But when I call the cabal installed binary even tough it compiles and launches my config file as it should, that somehow breaks the Com plugin... It still works if I just call the compiled configuration manually. Pretty sure this has nothing to do with it but I'm using dynamically compiled libraries and binaries ([see here](https://wiki.archlinux.org/index.php/Haskell#Problems_with_linking))

Running GHC 8.10.1 and all the latest things of the arch repo.

![2020-05-28-222819_1919x444_scrot](https://user-images.githubusercontent.com/1809521/83214280-93ea4380-a13a-11ea-9443-ece2e2d4379d.png)

That 'updating' part on the rightmost edge was a simple `Com uname`. Stays like that forever, tried to tweak the timing parameter to see if it helped, it didn't. My config files are in [my repo](https://github.com/samuelhnrq/dotfiles/blob/master/xmobar/.config/xmobar/xmobar.hs).

**Comment by samuelhnrq** [comment]
Been trying to look into this issue by myself, my only suspicion is process spawning shenanigans might be causing the issue, but only got dead ends so far.

Tried tracing process call creation (strace) to see if it had anything to do with the fact the config is a sub-process itself trying to spawn another sub-process (xmobar -> compiled config -> uname) but both tracing seems mostly identical (directly calling the compiled config vs. xmobar binary). [trace_broken.txt](https://github.com/jaor/xmobar/files/4705080/trace_broken.txt) vs [trace_workin.txt](https://github.com/jaor/xmobar/files/4705081/trace_workin.txt) (`strace -q -e process`)

Also tried to GHCI debug the Com plugin but I obviously found nothing, again simply calling the compiled executable work.

Also tried to fiddle with the 'main' code which does the compiling and running to use `System.Process` instead of `System.Posix.Process`, again, nothing. I bet `System.Process` is simply a platform-independent proxy that calls `System.Posix.Process` anyway.

Might try doing the same for the Com plugin but just of desperation.

**Comment by jaor** [comment]
this is very peculiar... i haven't tried more than you already did
(thanks for that, btw!), but i can neither reproduce the issue nor come
up with a reason of why this would happen!

**Comment by samuelhnrq** [comment]
> 
> this is very peculiar... i haven't tried more than you already did
> (thanks for that, btw!), but i can neither reproduce the issue nor come
> up with a reason of why this would happen! 
> 

Wait thats actually interesting to know, so even using an .hs file configuration the com plugin works as expected? Whats your environment?

**Comment by btwiusegentoo** [comment]
I have same issue. maybe same issue as #465 ?
I think it's not Arch specific or anything. I have same issue on NixOS.

**Comment by samuelhnrq** [comment]
Been even able to reproduce on a clean musl void Linux install it's definitely not related to arch Linux

**Comment by jaor** [comment]
sorry i'm taking so long to get back to you guys.  i couldn't reproduce
the problem back in the day, but possibly i was doing something
different.

it's a surprising problem, i cannot imagine where the difference is
between both use cases.

**Comment by btwiusegentoo** [comment]
OK, FWIW, I managed someway to work now. this is my full xmobar.hs.
```
import           Xmobar

config :: Config
config = defaultConfig {
        font = "xft:Monoid Nerd Font:pixelsize=14:antialias=true:hinting=false"
       , additionalFonts = []
       , borderColor = "#2b2a3e"
       , border = TopB
       , alpha = 255
       , bgColor = "#34324a"
       , fgColor = "#A6ACCD"
       , position = TopSize L 100 20
       , textOffset = -1
       , iconOffset = -1
       , lowerOnStart = True
       , pickBroadest = False
       , persistent = False
       , hideOnStart = False
       , iconRoot = "."
       , allDesktops = True
       , overrideRedirect = True
       , commands = [ Run $ Cpu ["-L","3","-H","50",
                               "--normal","green","--high","red"] 10
                    , Run $ Memory ["-t","Mem: <usedratio>%"] 10
                    , Run $ Swap [] 10
                    , Run $ Date "%a %b %_d %Y %H:%M:%S" "date" 10
                    , Run $ Com "uname" [ "-s" , "-r" ] "" 36000
                    , Run StdinReader
                    ]
       , sepChar = "%"
       , alignSep = "}{"
       , template = "%StdinReader% | %cpu% | %memory% * %swap% }\
                    \{ <fc=#f78c6c>%date%</fc> | %uname%"
       }

main :: IO()
main = do
    xmobar config
```

usually I run from xmonad with this command from do block.
<code> xmproc <- spawnPipe "xmobar -r ~/.xmonad/xmobar.hs"</code>

and, worked for me changing to this command.
<code> xmproc <- spawnPipe "xmobar ~/.xmonad/xmobar.hs</code>
I removed recompile flag and it worked.
I use home-manager to manage dotfiles and I run <code>home-manager switch</code> everytime I modified every config. so I have writed (in nix language on my home.nix) to detect file changes first, if X is running, auto run xmobar with `--recomplie` flag and `&` , then `disown`, `killall xmobar` and restart xmonad(it will run my xmobar. with command above now without --recompile flag this time.)
and I don't have problem using this way. but I think people that don't use home-manager maybe will want to include recompile flag?

**Comment by jaor** [comment]
moved to https://codeberg.org/jao/xmobar/issues/449
