### ISSUE TITLE
Surprising use of defaults and catch in `runVolumeWith`

### ISSUE THREAD

**Issue by wygulmage** [jaor/xmobar#454]
There are a couple of spots in `XMobar.Plugins.Monitors.Volume.runVolumeWith` where error handling seems to be done inconsistently. This may make be the correct behavior, but I can't figure out why. If it is correct, it would be good to add some documentation.

It centers on the helper function `channel'`:
```haskell
channel' :: PerChannel a -> a -> IO (Maybe a)
channel' v r = AE.catch 
    (getChannel FrontLeft v) 
    (const $ return $ Just r)
```
When the channel errors out, it returns `Just` the default value `r`, but when the channel does not exist, it returns `Nothing`.

`channel'` is used only in the helpers `getDB`, `getVal`, and `getSw`, which are in turn used only in the helper `readMixer`.
`readMixer` handles errors by returning `(Nothing, Nothing, Nothing, Nothing, Nothing)`.

```haskell
readMixer = AE.catch 
    (withMixer mixerName $ \mixer -> do
               control <- getControlByName mixer controlName
               (lo, hi) <- liftMaybe $ getRange <$> volumeControl control
               val <- getVal $ volumeControl control
               db <- getDB $ volumeControl control
               sw <- getSw $ switchControl control
               return (fmap toInteger lo, fmap toInteger hi, val, db, sw))
    (const $ return (Nothing, Nothing, Nothing, Nothing, Nothing))
```

The defaults of `getDB`, `getVal`, and `getSw` are only used when one of those functions throws an IO error after `getControlByName mixer controlName` and `liftMaybe $ getRange <$> volumeControl` succeed. Why is the default used in that rare case but not when the channel does not exist?

Three alternative behaviors for `channel'` make sense to me:
1. Return `Nothing` on an error, just like `readMixer` (for this you just get rid of the defaults):
```haskell
channel' :: PerChannel a -> IO (Maybe a)
channel' v = AE.catch 
    (getChannel FrontLeft v) 
    (const (return Nothing))
```
2. Use the default to unwrap the `Maybe`:
```haskell
channel' :: PerChannel a -> a -> IO a
channel' v r = AE.catch
    (fmap (fromMaybe r) (getChannel FrontLeft v))
    (const (return (Just r)))
```
3. Use the default value when the channel doesn't exist and return Nothing on an error (reverse of current behavior):
```haskell
channel' :: PerChannel a -> a -> IO (Maybe a)
channel' v r = AE.catch
    (fmap (fromMaybe r) (getChannel FrontLeft v))
    (const (return Nothing))
```

All three alternatives pass the test suite and seem to work on my system (probably because I'm not hitting the error or nonexistent channel cases). I'd be happy to do further testing or submit a pull request with the correct behavior once I know what it's supposed to be!

**Comment by slotThe** [comment]
I can't comment on how it's "supposed to be", but option 1 seems like the most sensible solution to me.

**Comment by jaor** [comment]
i agree 1 looks like the best solution.  thanks a lot @wygulmage for
the detailed investigation, and my apologies for the overdue response!
if you feel like sending a PR, i'll be happy to review/merge (in a
shorter time frame!), or i can just make the change myself if you prefer.

**Comment by wygulmage** [comment]
No worries, it's clearly low priority, just popped out at me. I'll open a PR as soon as I test the changes.

**Comment by wygulmage** [comment]
Opened PR #481 to fix this.
