### ISSUE TITLE
Output of commands run with "Run $ Com" not working

### ISSUE THREAD

**Issue by ManuelVs** [jaor/xmobar#465]
Hello,

When I create a command in xmobar.hs like the following:

```
config :: Config
config = defaultConfig {
  ...
  commands = [
    ...
    Run $ Com "uname" ["-s","-r"] "" 36000
  ],
  template = "%uname%"
}

main :: IO ()
main = xmobar config
```

It always outputs `Updating...` when I launch it as `xmobar` via CLI and `xmonad.hs`.

If I run the output compiled program (`~/.config/xmobar/xmobar`) it works as expected in both ways. I use a custom `build` file, which is basically the [default configuration](https://github.com/jaor/xmobar/blob/d1ba32888b402f3841847541ded9cc4349ae2f66/src/Xmobar/App/Compile.hs#L163) plus `-dynamic` so it works out-of-the-box in ArchLinux.

```
ghc --make xmobar.hs \
    -i \
    -ilib \
    -fforce-recomp \
    -main-is main \
    -v0 \
    -threaded \
    -rtsopts -with-rtsopts -V0 \
    -dynamic \
    -o $1
```

Is there anything that I am missing or this is a bug?

**Comment by ManuelVs** [comment]
I have read the `xmobar` code to see how the compiled binary is executed. I [found this line](https://github.com/jaor/xmobar/blob/6faa17e39d7bf77df9aa199db09d52a600984271/src/Xmobar/App/Main.hs#L84) which is executed a bit after calling the custom `build` file. I have tried to imitate that behavior with the following snippet:

```
import System.Posix.Process

main :: IO ()
main = do
  runProcess "./xmobar" False [] Nothing
```
I compile it with `ghc --make execute.hs -dynamic` and run it manually as `./execute`. As a result, the `uname` command works as expected. If I execute that file in `xmonad.hs` it works as well.

It is weird that when my custom binary is executed by `xmobar` doesn't work but when I execute it directly works.

**Comment by samuelhnrq** [comment]
Duplicated of #449 ?

**Comment by ManuelVs** [comment]
Yes, it is. I will close this since the other one is older and has more comments
