### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by supermario9590** [jaor/xmobar#467]
I have just made a fresh install of xmobar and I can't start it. Whenever I try to start it, I get this error:
`xmobar: error while loading shared libraries: libHSrandom-1.1-AA3zCuOgsVZCzsZYE3CMpY-ghc8.10.1.so: cannot open shared object file: No such file or directory`
I am doing this on Arch Linux with the official package.

**Comment by slotThe** [comment]
Is this still an issue?  Looks like something that would be fixed by recompiling (which will probably be done by the package maintainer(s)).

**Comment by zygimantus** [comment]
I have a similar issue with libHShttp-conduit-2.3.7.3-3SfnF9k4BzQBvTaVoSBhCA-ghc8.10.2.so

**Comment by supermario9590** [comment]
I fixed this by reinstalling all my haskell libs
