### ISSUE TITLE
Xmobar some battery widget variable shows error.

### ISSUE THREAD

**Issue by apoorv569** [jaor/xmobar#469]
I have my `Xmobar` battery widget setup like this
```
            -- Battery Monitor
       , Run Battery
         ["-t","<leftvbar>"
         ,"-L","10"
         ,"-H","75"
         ,"-h","green"
         ,"-m","yell"
         ,"-l","red"
         ] 10
```
and in the end in template I have `%battery%`, the `leftbar`, `leftvbar`and `timeleft` works, but if I change it to `left`, `leftipat`, `watts` or `acstatus` it shows error on the bar saying `error: Prelude.read: no parse`

**Comment by slotThe** [comment]
You need to separate the monitor-specific flags from the general monitor flags, otherwise `-m` has another meaning.  This is documented (though perhaps a little bit hidden) in [1].

So 
```
       , Run Battery
         ["-t","<leftvbar>"
         ,"-L","10"
         ,"-H","75"
         ,"--"
         ,"-h","green"
         ,"-m","yell"
         ,"-l","red"
         ] 10
```
should work.  I don't exactly know if `yell` will get parsed as yellow or if you just want to yell at your battery at that point, but try it out I guess :)

[1] https://github.com/jaor/xmobar#default-monitor-arguments

**Comment by apoorv569** [comment]
> You need to separate the monitor-specific flags from the general monitor flags, otherwise `-m` has another meaning. This is documented (though perhaps a little bit hidden) in [1].
> 
> So
> 
> ```
>        , Run Battery
>          ["-t","<leftvbar>"
>          ,"-L","10"
>          ,"-H","75"
>          ,"--"
>          ,"-h","green"
>          ,"-m","yell"
>          ,"-l","red"
>          ] 10
> ```
> 
> should work. I don't exactly know if `yell` will get parsed as yellow or if you just want to yell at your battery at that point, but try it out I guess :)
> 
> [1] https://github.com/jaor/xmobar#default-monitor-arguments

OK, doing separating the flags fixed it, however, I have modified my `xmobar` config from the last time I posted the block for battery. It now looks like this
```
         -- Battery Monitor
         , Run Battery 
                              ["--template"          ,"<acstatus> <left>%"
                              ,"-L"                  ,"10"
                              ,"-H"                  ,"75"
                              ,"--"
                              ,"-h"                  ,"green"
                              ,"-m"                  ,"yell"
                              ,"-l"                  ,"red"
                              ,"-i"                  ,"\xf583"
                              ,"--highs"             ,"\xf581"
                              ,"--mediums"           ,"\xf57f"
                              ,"--lows"              ,"\xf582"
                              ,"--on-icon-pattern"   ,""
                              ,"-A"                  ,"15"
                              ,"-a"                  ,"notify-send -u critical 'Battery running out!!'"
                              ] 10
```
It looks like this when its plugged in and fully charged
![2020-08-12_03-38](https://user-images.githubusercontent.com/53279454/89953836-8169ab80-dc4d-11ea-815e-d59a27ee7779.png)

When fully charged and not plugged in it looks like this
![2020-08-12_03-40](https://user-images.githubusercontent.com/53279454/89953907-a827e200-dc4d-11ea-95ff-921a2ec4b91b.png)

It shows the icon, but also says `off`. Is there a way to only show icon and battery percentage?

**Comment by slotThe** [comment]
On Tue, Aug 11 2020 15:12, apoorv wrote: 
> It shows the icon, but also says `off`. Is there a way to only 
> show icon and battery percentage? 
>

There are different AC settings you can modify, sounds like you want to
set the off-status (-o or --off) to something else.

**Comment by apoorv569** [comment]
> On Tue, Aug 11 2020 15:12, apoorv wrote: It shows the icon, but also says `off`. Is there a way to only show icon and battery percentage?
> There are different AC settings you can modify, sounds like you want to set the off-status (-o or --off) to something else.

According to the documentation here,
```
-i: string for AC "idle" status (default: "On")
```
Which I am using for showing icon for when charged and idle, and the
```
-O: string for AC "on" status (default: "On")
-o: string for AC "off" status (default: "Off")
```
they just show a icon when AC status is on or off, where as
```
--lows: string for AC "off" status and power lower than the -L threshold (default: "")
--mediums: string for AC "off" status and power lower than the -H threshold (default: "")
--highs: string for AC "off" status and power higher than the -H threshold (default: "")
```
Lets me set it up more dynamic sense, so I can have icons for different values, if I'm understanding this correctly, where I have setup the threshold as
```
                              ,"-L"                  ,"10"
                              ,"-H"                  ,"75"
```

**Comment by slotThe** [comment]
On Tue, Aug 11 2020 23:31, apoorv wrote: 
> ``` -O: string for AC "on" status (default: "On") -o: string for 
> AC "off" status (default: "Off") ``` they just show a icon when 
> AC status is on or off, where as ``` --lows: string for AC "off" 
> status and power lower than the -L threshold (default: "") 
> --mediums: string for AC "off" status and power lower than the 
> -H threshold (default: "") --highs: string for AC "off" status 
> and power higher than the -H threshold (default: "") ``` 

Ah, I see where the confusion is now.  The {low,medium,high}s 
options are *additional* strings to display depending on power 
usage.  If we look at the relevant code

    fmtStatus opts Discharging _ battStatus = 
      (case battStatus of 
        BattHigh -> highString BattMedium -> mediumString BattLow 
        -> lowString) opts ++ offString opts

we can see that the offString (which is exactly that you set with 
-o) is appended to whatever the result of the "status" string is.

I suppose there's at least a documentation change in order here, 
explicitly mentioning the additional property of these values.

**Comment by apoorv569** [comment]
> On Tue, Aug 11 2020 23:31, apoorv wrote: ``` -O: string for AC "on" status (default: "On") -o: string for AC "off" status (default: "Off") ``` they just show a icon when AC status is on or off, where as ``` --lows: string for AC "off" status and power lower than the -L threshold (default: "") --mediums: string for AC "off" status and power lower than the -H threshold (default: "") --highs: string for AC "off" status and power higher than the -H threshold (default: "") ```
> Ah, I see where the confusion is now. The {low,medium,high}s options are *additional* strings to display depending on power usage. If we look at the relevant code fmtStatus opts Discharging _ battStatus = (case battStatus of BattHigh -> highString BattMedium -> mediumString BattLow -> lowString) opts ++ offString opts we can see that the offString (which is exactly that you set with -o) is appended to whatever the result of the "status" string is. I suppose there's at least a documentation change in order here, explicitly mentioning the additional property of these values.

So do I need to set
```
                         ,"-O"                   ,""
                         ,"-o"                    ,""
```
To stop displaying `on` and `off` and just show icon?

**Comment by apoorv569** [comment]
> On Tue, Aug 11 2020 23:31, apoorv wrote: ``` -O: string for AC "on" status (default: "On") -o: string for AC "off" status (default: "Off") ``` they just show a icon when AC status is on or off, where as ``` --lows: string for AC "off" status and power lower than the -L threshold (default: "") --mediums: string for AC "off" status and power lower than the -H threshold (default: "") --highs: string for AC "off" status and power higher than the -H threshold (default: "") ```
> Ah, I see where the confusion is now. The {low,medium,high}s options are *additional* strings to display depending on power usage. If we look at the relevant code fmtStatus opts Discharging _ battStatus = (case battStatus of BattHigh -> highString BattMedium -> mediumString BattLow -> lowString) opts ++ offString opts we can see that the offString (which is exactly that you set with -o) is appended to whatever the result of the "status" string is. I suppose there's at least a documentation change in order here, explicitly mentioning the additional property of these values.

OK, setting the `-o` and `-O` option to `""` is showing what I wanted to show, but the icon is not changing as my per my config, I have set `-H` to `75` and as you can see its below `75` and still showing the icon for `--highs` instead of `--mediums`.

**Comment by slotThe** [comment]
On Wed, Aug 12 2020 10:20, apoorv wrote:
> OK, setting the `-o` and `-O` option to `""` is showing what I wanted to show, but the icon is not changing as my per my config, I have set `-H` to `75` and as you can see its below `75` and still showing the icon for `--highs` instead of `--mediums`.

What you have set is the high/low threshold for the colours, what you
want is the high/low threshold for these status strings, i.e. -L and -H
as well but as option to the specific monitor (after the "--").

Thinking about it, perhaps the additional freedom one gains by having
these different options is negligible compared to the annoyance of
having to set these values twice in this case...

**Comment by apoorv569** [comment]
> On Wed, Aug 12 2020 10:20, apoorv wrote: OK, setting the `-o` and `-O` option to `""` is showing what I wanted to show, but the icon is not changing as my per my config, I have set `-H` to `75` and as you can see its below `75` and still showing the icon for `--highs` instead of `--mediums`.
> What you have set is the high/low threshold for the colours, what you want is the high/low threshold for these status strings, i.e. -L and -H as well but as option to the specific monitor (after the "--"). Thinking about it, perhaps the additional freedom one gains by having these different options is negligible compared to the annoyance of having to set these values twice in this case...

I think I know what you are saying, I had the block like this,
```
         -- Battery Monitor
         , Run Battery 
                              ["--template"          ,"<acstatus> <left>%"
                              ,"-L"                  ,"10"
                              ,"-H"                  ,"75"
                              ,"--"
                              ,"-h"                  ,"green"
                              ,"-m"                  ,"yell"
                              ,"-l"                  ,"red"
                              ,"-i"                  ,"\xf583"
                              ,"--highs"             ,"\xf581"
                              ,"--mediums"           ,"\xf57f"
                              ,"--lows"              ,"\xf582"
                              ,"--on-icon-pattern"   ,""
                              ,"-A"                  ,"15"
                              ,"-a"                  ,"notify-send -u critical 'Battery running out!!'"
                              ] 10
```
I changed it this now,
```
         -- Battery Monitor
         , Run Battery 
                              ["--template"          ,"<acstatus> <left>%"
                              ,"--"
                              ,"-L"                  ,"15"
                              ,"-H"                  ,"75"
                              ,"-h"                  ,"green"
                              ,"-m"                  ,"yell"
                              ,"-l"                  ,"red"
                              ,"-i"                  ,"\xf583"
                              ,"-o"                  ,""
                              ,"-O"                  ,"\xf58a"
                              ,"--highs"             ,"\xf581"
                              ,"--mediums"           ,"\xf57d"
                              ,"--lows"              ,"\xf582"
                              ,"--on-icon-pattern"   ,""
                              ,"-A"                  ,"15"
                              ,"-a"                  ,"notify-send -u critical 'Battery running out!!'"
                              ] 10
```
It's now showing icons properly. Thanks! :smile:

**Comment by jaor** [comment]
moved to https://codeberg.org/jao/xmobar/issues/469
