### ISSUE TITLE
Xmobar volume widget unrecognized option.

### ISSUE THREAD

**Issue by apoorv569** [jaor/xmobar#470]
I have my `Xmobar` volume widget like this
```
             -- Volume
          , Run Volume "default" "Master"
            ["-t","\xf028 <volume>%"
            ] 10
```
and in template I have `%default:Master%`, I'm trying to use the `-o` and `-O` option to change the icon accordingly. I added this line 
```
             -- Volume
          , Run Volume "default" "Master"
            ["-t","\xf028 <volume>%"
            , "-o","\xfc5d <status>"
            ] 10
```
and it shows `unrecognized option '-o'`

I'm following this guide - https://archives.haskell.org/projects.haskell.org/xmobar/#volume-mixer-element-args-refreshrate

**Comment by jaor** [comment]
>              -- Volume
>           , Run Volume "default" "Master"
>             ["-t","\xf028 <volume>%"
>             , "-o","\xfc5d <status>"
>             ] 10

you need a "--" separator before you start optional args.  try: `[..., "--", "-o", ...]`

> I'm following this guide -
> https://archives.haskell.org/projects.haskell.org/xmobar/#volume-mixer-element-args-refreshrate

that's obsolete.  i'd suggest you take a look at the readme in this repo
for extensive, up-to-date docs.

**Comment by apoorv569** [comment]
> -- Volume , Run Volume "default" "Master" ["-t","\xf028 <volume>%" , "-o","\xfc5d <status>" ] 10
> you need a "--" separator before you start optional args. try: `[..., "--", "-o", ...]`
> I'm following this guide - https://archives.haskell.org/projects.haskell.org/xmobar/#volume-mixer-element-args-refreshrate
> that's obsolete. i'd suggest you take a look at the readme in this repo for extensive, up-to-date docs.

```
 -- Volume
           , Run Volume "default" "Master"
             ["-t","\xf028 <volume>%"
             , "--"
             , "-o","\xfc5d <status>"
             ] 10
```
I added the line, its not giving error now, but the icon doesn't change when I mute.

**Comment by jaor** [comment]
the values of -O and -o are the strings used in the template (-t) in
place of `<status>`. your template doesn't have `<status>`.  you could
try:

           , Run Volume "default" "Master"
             ["-t","<status> <volume>%"
             , "--"
             , "-O", "\xf028"      
             , "-o","\xfc5d"
             ] 10

**Comment by apoorv569** [comment]
> the values of -O and -o are the strings used in the template (-t) in place of `<status>`. your template doesn't have `<status>`. you could try: , Run Volume "default" "Master" ["-t","<status> <volume>%" , "--" , "-O", "\xf028" , "-o","\xfc5d" ] 10

Yes, its working now. One more thing, I have it like this right now
```
  , Run Volume "default" "Master"
             ["-t","<status> <volume>%"
             , "--"
             , "-O", "\xf028"
             , "-o","\xfc5d"
             ] 10
```
before I had like this
```
  , Run Volume "default" "Master"
             ["-t","<fc=#fb2a5f>\xf028</fc> <volume>%"
             ] 10
```
which gave a red color for the icon. I don't have anything specifying the color now, but it shows red color icon when its muted(status OFF), and regular `fc` color when unmuted(status ON). Where is it getting the color from now?

**Comment by jaor** [comment]
On Mon, Jul 13 2020, apoorv569 wrote:

> which gave a red color for the icon. I don't have anything specifying
> the color now, but it shows red color icon when its muted(status OFF),
> and regular fc color when unmuted(status ON). Where is it getting the
> color from now?

i think some unicode/symbol fonts include color information for some
glyphs, but i'm not sure how that works exactly.

**Comment by apoorv569** [comment]
> On Mon, Jul 13 2020, apoorv569 wrote: which gave a red color for the icon. I don't have anything specifying the color now, but it shows red color icon when its muted(status OFF), and regular fc color when unmuted(status ON). Where is it getting the color from now?
> i think some unicode/symbol fonts include color information for some glyphs, but i'm not sure how that works exactly.

Alright! Thanks for the help.

**Comment by apoorv569** [comment]
> On Mon, Jul 13 2020, apoorv569 wrote: which gave a red color for the icon. I don't have anything specifying the color now, but it shows red color icon when its muted(status OFF), and regular fc color when unmuted(status ON). Where is it getting the color from now?
> i think some unicode/symbol fonts include color information for some glyphs, but i'm not sure how that works exactly.

I check the guide on this repo, according to the guide its related to the status color here,
```
-C color On color

    The color to be used for <status> when the mixer element is on. Defaults to "green".
    Long option: --onc

-c color Off color

    The color to be used for <status> when the mixer element is off. Defaults to "red".
    Long option: --offc
```

**Comment by jaor** [comment]
oh, thanks! i had completely forgotten that option!!

**Comment by apoorv569** [comment]
> oh, thanks! i had completely forgotten that option!!

:+1: No problem.
