### ISSUE TITLE
migrate from wireless-tools to libnl

### ISSUE THREAD

**Issue by nullr0ute** [jaor/xmobar#472]
Upstream wireless-tools and the associated kernel interface is long obsolete and doesn't support most modern wireless interfaces or most of the wifi NICs supported in the kernel so migrate to the newer netlink interface which supports all the newer wireless interfaces and many more things.

**Comment by nullr0ute** [comment]
An example of another project: https://github.com/mate-desktop/mate-applets/commit/bff29f926f56aba490e3f7b6f2d11e6a1aae46c7

**Comment by jaor** [comment]
we're already using the netlink interface by default, see pull request #429 ... what am i missing?

**Comment by nullr0ute** [comment]
It seems nothing, the Fedora package is doing some weird stuff that I missed s it was me that was missing, sorry for the noise
