### ISSUE TITLE
ALSA input

### ISSUE THREAD

**Issue by samhh** [jaor/xmobar#473]
Am I right in thinking that the [ALSA module](https://github.com/jaor/xmobar#alsa-mixer-element-args) only works for playback/output? Would it be possible to get support for capture/input? Cheers :slightly_smiling_face:

**Comment by jaor** [comment]
i am not sure, but the docs don't say it only works for Master... have
you tried with a mixer name other than "Master"?

**Comment by SamHH** [comment]
I have. Example:

```
$ alsactl monitor pcm.usb
[change input volume in alsamixer]
node pcm.usb, #12 (2,0,0,Mic Capture Volume,0) VALUE
node pcm.usb, #12 (2,0,0,Mic Capture Volume,0) VALUE
[change output volume in alsamixer]
node pcm.usb, #4 (2,0,0,Mic Playback Volume,0) VALUE
```

It only works in xmobar if I target `pcm.usb` and, notably, `Mic`. I can't target `Mic Capture` for example which'd allow me to differentiate.

**Comment by wygulmage** [comment]
As far as I can tell, in Volume at least, the current code tries to get playback, capture, and then common depending on what is provided by `FrontLeft` of the mixer (which is the same as mono if it's mono). 

I've been working on an approach that provides xmobar multiple channels when they exist (also cool if you can set left and right volumes separately); my main stumbling block has been coming up with a good data structure to hold the result and a good default way to present it in the UI.

**Comment by samhh** [comment]
So... I don't know if I just missed this before, or if something changed when I started using PulseAudio, but I can now get playback trivially with `%default:Capture%`.

To figure that out I wrote a custom plugin, so if anyone needs a more custom solution this may prove useful as a foundation?:

```hs

data AlsaCaptureStatus = AlsaCaptureStatus
  { capMixer   :: String
  , capControl :: String
  }
  deriving (Read, Show)

instance Exec AlsaCaptureStatus where
  alias (AlsaCaptureStatus m c) = "mic:" <> m <> ":" <> c
  run (AlsaCaptureStatus m c)   = withMixer m $ (`getControlByName` c) >=> \case
    Nothing  -> pure "(fail)"
    (Just z) -> show <$> (activeCapture . switch $ z)

activeCapture :: Either Switch (Maybe Switch, Maybe Switch) -> IO Bool
activeCapture (Left common)                          = getJoined common
activeCapture (Right (Just _playback, Nothing))      = pure False
activeCapture (Right (Nothing, Just capture))        = getJoined capture
activeCapture (Right (Just _playback, Just capture)) = getJoined capture
activeCapture (Right (Nothing, Nothing))             = pure False
```

You'll need the `LambdaCase` GHC extension and `alsa-mixer` listed as an explicit dependency (it's what XMobar already implicitly used internally).

**Comment by jaor** [comment]
thanks for the update and the example, sam.  maybe we could add it
somewhere to the docs as a non-trival, yet short example of how to write
a plugin.
