### ISSUE TITLE
The fonts are not being rendered properly

### ISSUE THREAD

**Issue by shhra** [jaor/xmobar#476]
![image](https://user-images.githubusercontent.com/29188967/88383660-a85d5c00-cdca-11ea-805b-10e14cd12909.png)
As you can see the font awesome isn't being rendered properly, while on the another side it works perfectly fine.
My config to xmonad is as follows:

```
xmobarEscape = concatMap doubleLts
  where
        doubleLts '<' = "<<"
        doubleLts x   = [x]

myWorkspaces = clickable . map xmobarEscape $ ["\xf0a0", "\xf134", "\xf135", "\xf136", "\xf137", "\xf138", "\xf139", "\xf123", "\xf153"]
  where                                                                      
        clickable l = [ "<action=xdotool key super+" ++ show n ++ ">" ++ ws ++ "</action>" |
                      (i,ws) <- zip [1..9] l,                                        
                      let n = i ] 

```
The log hook is as follows:
```
        , logHook            = dynamicLogWithPP $ xmobarPP
                               {
                               -- primary bar
                               ppOutput            = \x -> hPutStrLn xmproc0 x  >> hPutStrLn xmproc1 x
                               , ppCurrent         = xmobarColor "#4c062b" "" . wrap "[-" "-]"  -- Current workspace in xmobar
                               , ppVisible         = xmobarColor "#4c062b" "" . wrap "-{" "}-"  -- Visible but not current workspace
                               , ppHidden          = xmobarColor "#851E1E" "" . wrap "*" "*"   -- Hidden workspaces in xmobar
                               , ppHiddenNoWindows = xmobarColor "#215c1f" ""                  -- Hidden workspaces (no windows)
                               , ppTitle           = xmobarColor "#104293" "" . shorten 10    -- Title of active window in xmobar
                               --, ppSep             = "<fc=#666666> | </fc>"                  -- Separators in xmobar
                               , ppUrgent          = xmobarColor "#C45500" "" . wrap "!" "!"  -- Urgent workspace
                               , ppOrder           = \(ws:l:t:ex) -> [l, ws]
                               }
```
And the font config at xmboar is as follows
```
-- http://projects.haskell.org/xmobar/
-- install xmobar with these flags: --flags="with_alsa" --flags="with_mpd" --flags="with_xft"  OR --flags="all_extensions"
-- you can find weather location codes here: http://weather.noaa.gov/index.html

Config { 
    font = "xft:SF Pro Display:size=12:antialias=true,FontAwesome:size=13"
        , additionalFonts = [ "xft:FontAwesome:size=13"]
        , bgColor = "#e6f0e6"
        , fgColor = "#390420"
        , alpha = 230
        , position = BottomW C 85
    , lowerOnStart = True
        , hideOnStart = False
        , allDesktops = True
        , persistent = True
        , commands = [
        -- Time and date
            Run Date "\xf133 %b %d (%H:%M)" "date" 50

            -- Disk space free
            , Run Alsa "default" "Master" ["-t", "\xf028 <volume>% " ]

            -- Cpu used in percent
            , Run Cpu ["-t", "\xf108 (<total>%)","-H","50","--high","red"] 20

            -- Ram used number and percent
            , Run Memory ["-t", "\xf233 <used>M (<usedratio>%)"] 20

            -- Battery
            , Run Battery [
                "-t", "<acstatus>: <left>% - <timeleft>",
                "--",
                --"-c", "charge_full",
                "-O", "\xf0e7",
                "-o", "\xf240",
                "-h", "\xf240",
                "-l", "\xf244"
                ] 10

            -- Disk space free
            , Run DiskU [("/home", "\xf0a0 <used> ")] [] 60

            -- Runs a standard shell command 'uname -r' to get kernel version
            , Run Com "uname" ["-r"] "ker" 0

            -- Prints out the left side items such as workspaces, layout, etc.
            -- The workspaces are set to be 'clickable' in .xmonad/xmonad.hs
            , Run UnsafeStdinReader
            ]
            , sepChar = "%"
            , alignSep = "}{"
            , template = " %UnsafeStdinReader% }{ <fc=#13010B>%battery%</fc><fc=#666666> | </fc><fc=#132A13>%cpu% </fc><fc=#666666>| </fc><fc=#430F0F>%memory% </fc><fc=#666666>| </fc><fc=#061937>%disku% </fc><fc=#666666>| </fc><fc=#573F0F>%alsa:default:Master%</fc><fc=#666666>| </fc><fc=#193939>%date%</fc> "
}

```
I have no idea why the font is not working for workspaces, while it works for other parts of the config

**Comment by jaor** [comment]
does using `<fn=1>%UnsafeStdinReader%</fn>` in the template help?

**Comment by shhra** [comment]
![image](https://user-images.githubusercontent.com/29188967/88391430-e44bed80-cdd9-11ea-9693-1abeb1cb1cca.png)

Now I am getting boxes only

**Comment by jaor** [comment]
i'm guessing sending non-ascii chars through stdin via xmonad is not
working, but i don't use xmonad myself, so i am not sure why...

**Comment by shhra** [comment]
I also think it has to do with xmonad, but since I am fairly new to xmonad, I can't pinpoint the exact issue. However, I tried sending in the data in someway like this
```
myWorkspaces = clickable . map xmobarEscape
                $ ["f0a0", "f134", "f135", "f136", "f137", "f138", "f139", "f123", "f153"]
              where                                                                      
        clickable l = [ "<fn=0>\\x" ++ ws ++ "</fn>" |
                      (i,ws) <- zip [1..9] l,                                        
                      let n = i ] 
```
On doing so I get something like this!
![image](https://user-images.githubusercontent.com/29188967/88396127-d4d0a280-cde1-11ea-9971-4ab52953c795.png)
On changing ```fn=0``` to ```fn=1```,
![image](https://user-images.githubusercontent.com/29188967/88396477-51638100-cde2-11ea-8a19-02a45976adad.png)


And when I add in the quotes,
```
myWorkspaces = clickable . map xmobarEscape
                $ ["f0a0", "f134", "f135", "f136", "f137", "f138", "f139", "f123", "f153"]
              where                                                                      
              clickable l = [ "<fn=0>\"\\x" ++ ws ++ "\"</fn>" |
                      (i,ws) <- zip [1..9] l,                                        
                      let n = i ] 

```
![image](https://user-images.githubusercontent.com/29188967/88396249-fb8ed900-cde1-11ea-9d8e-f66dc14ab5d2.png)

On changing ```fn=0``` to ```fn=1```,
![image](https://user-images.githubusercontent.com/29188967/88396420-3bee5700-cde2-11ea-92ea-9d733d8c4212.png)

**Comment by Unoqwy** [comment]
> i'm guessing sending non-ascii chars through stdin via xmonad is not working, but i don't use xmonad myself, so i am not sure why...

It works for me. The issue does not come from there (or for specific cases but it's very unlikely).
<details>
<summary>(my config and the output)</summary>

```
myWorkspaces = (map (\(name, index) ->
  "<action=`xdotool key super+" ++ show index ++ "`>  <fn=2>" ++ xmobarEscape name ++ "</fn>  </action>"
  ) (zip ws [1..(length ws)])) ++ map show [(length ws)..9]
  where
    ws = [ "\xf8c9" -- Media
         , "\xf37e" -- Web
         , "\xf7ea" -- Home sweet home
         , "\xf120" -- ^
         , "\xf4b0" -- Chat/social
         , "\xf80a" -- Holiday home
         ]
```
![2020-07-25_10-36](https://user-images.githubusercontent.com/65187632/88453128-b6f85180-ce64-11ea-895c-3968e4ff2f63.png)
</details>

Also, you cannot put the `\x` part elsewhere, it will not render as a character but a string (that's what you got in your previous message).
Could you try reverting back your list to include the `\x` part and set `fn=1`?

**Comment by shhra** [comment]
I just copied your config, and still didn't work out. I have really no idea what is going on...!
<details>
<summary>Updated config and images</summary>

```haskell

 myWorkspaces = (map (\(name, index) ->
  "<action=`xdotool key super+" ++ show index ++ "`>  <fn=1>" ++ xmobarEscape name ++ "</fn>  </action>"
  ) (zip ws [1..(length ws)])) ++ map show [(length ws)..9]
  where
    ws =  ["\xF0A0", "\xf134", "\xf135", "\xf136", "\xf137", "\xf138", "\xf139", "\xf123", "\xf153"]
```
![image](https://user-images.githubusercontent.com/29188967/88453637-80343280-ce88-11ea-8766-2578c0729a25.png)

</details>

**Comment by Unoqwy** [comment]
These weird characters make me think it's a problem with your file encoding. Is your `xmonad.hs` encoded as UTF-8?
If yes then I have no idea either but you could still try to use a unicode emoji supported by your font (not FA) and see what happens.

**Comment by shhra** [comment]
I think it really isn't encoded in UTF-8, any idea on how to do so! I really new to haskell and do not have idea of fixing the encoding. In python it was something like this ```# -*- coding: utf-8 -*-``` which isn't necessary from python3. Would you mind helping here?

**Comment by Unoqwy** [comment]
You shouldn't have to import modules using Haskell to change your file encoding.

You can use the command `file xmonad.hs` to check if your file is encoded as UTF-8 (mine returns `UTF-8 Unicode text`).
To convert it: open your file in vim, run `:set fileencoding=utf-8` then save and quit (`:wq`) and check again.

**Comment by shhra** [comment]
Yeah I did that! The file is encoded as UTF-8. Does it has to do anything with stack? Because I installed xmonad and xmobar using stack. I also used flag ```all_features``` while installing xmobar.

**Comment by Unoqwy** [comment]
If the icons displayed on the right side they can be displayed on the left side as well. Using stack or something else really doesn't matter.
Have you tried using a unicode emoji without Font Awesome (one that works outside the UnsafeStdinReader) to check if it renders properly?

**Comment by shhra** [comment]
I just tried unicode emoji's and they are also not working.

```Haskell
myWorkspaces = clickable . map xmobarEscape
                  $ ["\xF603", " \xF601 ", "\xf135", "\xf136", "\xf137", "\xf138", "\xf139", "\xf123", "\xf153"]
   where
         clickable l = [ "<action=xdotool key super+" ++ show n ++ "><fn=0>" ++ ws ++ "</fn></action>" |
                       (i,ws) <- zip [1..9] l,
                       let n = i ]
```
The first two are normal unicodes!
Still same issue
![image](https://user-images.githubusercontent.com/29188967/88455372-7f090280-ce94-11ea-9bdc-32b2e7185a92.png)

**Comment by gabrielfrtg** [comment]
I'm facing the same problem in Xmobar version 0.35.1. Before formating my computer, Xmobar version 0.33 was working correctly with Font Awesome Unicode glyphs. However, after formatting my computer and reinstalling Xmonad and building Xmobar from source with flag `all_extensions`, Font Awesome glyphs aren't working anymore. I tested with both 0.33 and 0.35.1 versions. The only way in which one or two glyphs were rendered correctly is by setting the font name as follows:
```
additionalFonts = additionalFonts = [ "xft:FontAwesome5Free:pixelsize=13" ]
```

I tried the solutions provided above, and no one worked for me too.

**Comment by slotThe** [comment]
I dug around a bit and this is not actually an issue with xmobar, it lies completely with xmonad.  Specifically, xmonad/xmonad-contrib/pull/346 changes the way that the default `spawnPipe` function behaves (which is, for example, used by the often used `statusBar`).  It now encodes the stuff that gets send down the pipe with your local encoding, thus completely mangling any sort of icon-like characters. 

For now, the solution is to use `spawnPipeWithNoEncoding` instead of `spawnPipe` when communicating with xmobar.  If you use the `statusBar` function you will either have to replicate some of its logic in your xmonad.hs or clone the repo, change how `spawnPipe` is defined and then make that a dependency of your xmonad install.

Long-term I think the original behaviour of `spawnPipe` should be restored and it should default to no encoding at all.  This seems to have bitten enough people to justify that.  @psibi what do you think?

**Comment by psibi** [comment]
@slotThe Thanks for the ping!

> Long-term I think the original behaviour of spawnPipe should be restored and it should default to no encoding at all

I'm not sure that's the right thing to do because the  original behavior of `spawnPipe` can easily lead to a crash. For an example, see here: https://github.com/xmonad/xmonad-contrib/issues/338#issue-615379149

Do you have a minimal xmobar configuration which I can use to test the above bug ? I do use font awesome in my xmobar, but I think my usage isn't hitting them: https://github.com/psibi/dotfiles/blob/180184ff88ee8164c402ceac90eebcc5851c1f75/xmobar/src/Lib.hs#L340

**Comment by slotThe** [comment]
> I'm not sure that's the right thing to do because the original behavior of `spawnPipe` can easily lead to a crash. For an example, see here: [xmonad/xmonad-contrib#338 (comment)](https://github.com/xmonad/xmonad-contrib/issues/338#issue-615379149)
> 

Ah I see, well in that case it might be worth defaulting to locale encoding after all.  Crashes are never good...

> Do you have a minimal xmobar configuration which I can use to test the above bug ? I do use font awesome in my xmobar, but I think my usage isn't hitting them: https://github.com/psibi/dotfiles/blob/180184ff88ee8164c402ceac90eebcc5851c1f75/xmobar/src/Lib.hs#L340

Sure thing, here is a minimal xmonad and xmobar config with which I can reproduce this issue:

```haskell
import XMonad
import XMonad.Hooks.DynamicLog
import XMonad.Util.Run

main :: IO ()
main = do
    h <- spawnPipeWithLocaleEncoding "xmobar ~/.xmobarrc"
    xmonad $ def
        { logHook = dynamicLogWithPP $ def { ppOutput = hPutStrLn h }
        , workspaces = ["<fn=1>\xf120</fn>"]
        }
```

```
Config { template        = "%StdinReader%"
       , additionalFonts = ["xft:FontAwesome-9"]
       }
```

I used git HEAD for both programs and compiled them with ghc-8.8.3.

With those settings I'm getting the following, incorrectly rendered, glyph in xmboar:  ![incorrectly rendered glyph](https://i.imgur.com/BWwq0W1.png).  This also happens if I use `spawnPipeWithUtf8Encoding`.  

If I, however, use `spawnPipeWithNoEncoding` then the glyph gets rendered correctly: ![correctly rendered glyph](https://i.imgur.com/KZiKi0j.png).

**Comment by psibi** [comment]
@slotThe Thanks for finding the root cause of the issue and giving me a very small reproducible test case! Your example made me much easier to track the offending code. I have created a sample MR which should fix it: https://github.com/jaor/xmobar/pull/482

Can you test it and see if it works for you ?

**Comment by shhra** [comment]
This fixes on the left side of the bar but doesn't work on the right side.
![image](https://user-images.githubusercontent.com/29188967/89724116-d7a4d780-da1e-11ea-8462-fb91bade1746.png)
Am I missing something?

**Comment by psibi** [comment]
@shhra Can you produce full reproducible code for your xmobar and xmonad configuration for the above snapshot? (I checked the above thread, but it has been difficult for me to follow)

**Comment by psibi** [comment]
Also a question: Was it working previously on the right side and this patch broke it ?

**Comment by shhra** [comment]
<details>
<summary>xmobar config</summary>

```
Config { 
    font = "xft:FontAwesome-14,Iosevka:size=14:antialias=true:hinting=true"
        , additionalFonts = [ "xft:FontAwesome:size=14"]
        , bgColor = "#e6f0e6"
        , fgColor = "#390420"
        , alpha = 230
        , position = BottomW C 85
    , lowerOnStart = True
        , hideOnStart = False
        , allDesktops = True
        , persistent = True
        , commands = [
        -- Time and date
            Run Date "\xf133 %b %d (%H:%M)" "date" 50

            -- Disk space free
            , Run Alsa "default" "Master" ["-t", "\xf028 <volume>% " ]

            -- Cpu used in percent
            , Run Cpu ["-t", "\xf108 (<total>%)","-H","50","--high","red"] 20

            -- Ram used number and percent
            , Run Memory ["-t", "\xf233 <used>M (<usedratio>%)"] 20

            -- Battery
            , Run Battery [
                "-t", "<acstatus>: <left>% - <timeleft>",
                "--",
                --"-c", "charge_full",
                "-O", "\xf0e7",
                "-o", "\xf240",
                "-h", "\xf240",
                "-l", "\xf244"
                ] 10

            -- Disk space free
            , Run DiskU [("/home", "\xf0a0 <used> ")] [] 60

            -- Runs a standard shell command 'uname -r' to get kernel version
            , Run Com "uname" ["-r"] "ker" 0

            -- Prints out the left side items such as workspaces, layout, etc.
            -- The workspaces are set to be 'clickable' in .xmonad/xmonad.hs
            , Run UnsafeStdinReader
            ]
            , sepChar = "%"
            , alignSep = "}{"
            , template = " %UnsafeStdinReader% }{ <fc=#13010B>%battery%</fc><fc=#666666> | </fc><fc=#132A13>%cpu%</fc><fc=#666666>| </fc><fc=#430F0F>%memory% </fc><fc=#666666>| </fc><fc=#061937>%disku% </fc><fc=#666666>| </fc><fc=#573F0F>%alsa:default:Master%</fc><fc=#666666>| </fc><fc=#193939>%date%</fc> "
}

```
</details>

<details>
<summary>xmonad config</summary>

```Haskell
myWorkspaces = clickable . map xmobarEscape
                -- $ ["1:web", "2:dev1", "3:dev2", "4:term", "5:chat", "6:study", "7:notes", "8:file", "9:music"]
                $ ["\xf6d5", " \xF601 ", "\xf135", "\xf136", "\xf137", "\xf138", "\xf139", "\xf123", "\xf153"]
   where
         clickable l = [ "<action=xdotool key super+" ++ show n ++ "><fn=0>" ++ ws ++ "</fn></action>" |
                       (i,ws) <- zip [1..9] l,
                       let n = i ]

main :: IO ()
main = do
    -- Launch xmobar
    nScreens    <- countScreens
    xmproc0 <- spawnPipe "xmobar -x 0 ~/.config/xmobar/xmobarrc"
    xmproc1 <- (if nScreens > (1::Int) then spawnPipe "xmobar -x 1 ~/.config/xmobar/xmobarrc1" else spawnPipe "dev/null 2>&1")
    -- Launch ewmh desktop
    xmonad $ ewmh def
        { manageHook = ( isFullscreen --> doFullFloat ) <+> myManageHook <+> manageDocks
        , handleEventHook    = serverModeEventHookCmd 
                               <+> serverModeEventHook 
                               <+> serverModeEventHookF "XMONAD_PRINT" (io . putStrLn)
                               <+> docksEventHook
        , modMask            = myModMask
        , terminal           = myTerminal
        , startupHook        = myStartupHook
        , layoutHook         = myLayoutHook 
        , workspaces         = myWorkspaces
        , borderWidth        = myBorderWidth
        , normalBorderColor  = myNormColor
        , focusedBorderColor = myFocusColor
        , logHook            = composeAll [ 
                               dynamicLogWithPP $ xmobarPP
                               {
                               -- primary bar
                               ppOutput            = \x -> hPutStrLn xmproc0 x  >> hPutStrLn xmproc1 x
                               , ppCurrent         = xmobarColor "#4c062b" "" . wrap "[-" "-]"  -- Current workspace in xmobar
                               , ppVisible         = xmobarColor "#4c062b" "" . wrap "-{" "}-"  -- Visible but not current workspace
                               , ppHidden          = xmobarColor "#851E1E" "" . wrap "*" "*"   -- Hidden workspaces in xmobar
                               , ppHiddenNoWindows = xmobarColor "#215c1f" "" . \s -> ""                 -- Hidden workspaces (no windows)
                               , ppTitle           = xmobarColor "#104293" "" . shorten 10    -- Title of active window in xmobar
                               , ppSep             = "<fc=#666666> | </fc>"                  -- Separators in xmobar
                               , ppUrgent          = xmobarColor "#C45500" "" . wrap "!" "!"  -- Urgent workspace
                               , ppOrder           = \(ws:l:t:ex) -> [l, ws]

                               },
                               logHook def >> updatePointer (0.5, 0.5) (0.0, 0.0) ]

        } `additionalKeysP` myKeys 

```
I have attached the code here, I removed all the hooks and attached the main function.

**Comment by psibi** [comment]
@shhra I have updated the PR: https://github.com/jaor/xmobar/pull/482

Can you check again ? Thanks!

**Comment by slotThe** [comment]
On Sat, Aug 08 2020 09:57, Sibi Prabakaran wrote: 
> I have created a sample MR which should fix it: 
> https://github.com/jaor/xmobar/pull/482 
> 
> Can you test it and see if it works for you ?

This does actually work for StdinReader!  

However, I can reproduce @shhra's error with the following config:

```haskell
import XMonad import XMonad.Hooks.DynamicLog import 
XMonad.Util.Run  main :: IO () main = do 
    h <- spawnPipeWithUtf8Encoding "xmobar ~/.xmobarrc" xmonad $ 
    def 
        { logHook = dynamicLogWithPP $ def { ppOutput = hPutStrLn 
        h } , workspaces = ["<fn=1>\xf120</fn>", 
        "<fn=1>\61478</fn>"] } 
```

``` Config { additionalFonts = ["xft:FontAwesome-9"]
       , commands        = [ Run Memory ["-t","<fn=1>\xf120</fn> 
       <fn=1>\61478</fn>"] 10
                           , Run StdinReader
                           ]
       , template        = "%StdinReader% %memory%" }
```

Both glyphs get rendered correctly via StdinReader, but there still
seems to be some problem with the other monitors.

**Comment by psibi** [comment]
@slotThe I have update the MR just now. Can you check and see if that fixes the monitors issue ?

**Comment by shhra** [comment]
@psibi It works! Thank you for your work!

**Comment by slotThe** [comment]
On Sat, Aug 08 2020 23:58, Sibi Prabakaran wrote: 
> @slotThe I have update the MR just now. Can you check and see if 
> that fixes the monitors issue ? 

Yup, seems to work like a charm, thanks!

**Comment by psibi** [comment]
@slotThe / @shhra Thanks for the confirmation!

**Comment by gabrielfrtg** [comment]
In my case, even with this fix, it does not work. I tried to use @slotThe configurations for Xmonad and Xmobar, but then I get the following error:
```
Variable not in scope:
      spawnPipeWithUtf8Encoding :: [Char] -> IO GHC.IO.Handle.Types.Handle
```
It only runs with spawnPipe. However, the glyphs still do not render. I'm using GHC version 8.6.5 in a Fedora 32 system.

**Comment by psibi** [comment]
@gabrielfrtg For trying @slotThe configuration, you need to use the unreleased version of `xmonad-contrib` ie the one available from the master branch of their git repository.

**Comment by psibi** [comment]
@shhra Can this issue be closed ? @gabrielfrtg If you are still reproducing the issue with the latest version of `xmonad-contrib` and `xmobar`, I would recommend you to create a new issue with a small reproducible code [like this](https://github.com/jaor/xmobar/issues/476#issuecomment-671015475).
