### ISSUE TITLE
XMonad freezes when StdinReader is ignored in xmobar configuration

### ISSUE THREAD

**Issue by meissnol** [jaor/xmobar#478]
Hi,

while at least one (of multiple) xmobars is configured to not show its StdIn, the whole WM freezes every 5-15 minutes. Only the mouse cursor is moving, any other input is completely ignored unless you kill the one xmobar, whose stdin is not shown. This freeze can also be triggered by dragging a floating window around. After 2 seconds dragging: the wm is frozen. (Hope that makes sense).

Maybe someone else may find this problem and has a solution?!

**Comment by Unoqwy** [comment]
When you removed StdinReader from the template you probably left it running in the commands section, try removing it from there.
If it still doesn't work, would you mind providing your configuration?

**Comment by meissnol** [comment]
Got it working by loading the bar via startupHook... not the most elegant way to do it, but it works for now...

~/.xmonad/xmobarrc.pri-bottom:
`Config { font    = "xft:Iosevka Nerd Font:style=Regular:antialias=true:hinting=true:pixelsize=14"
       , additionalFonts = [ "xft:Libel Suit:style=Regular:size=13:antialias=false:hinting=false"
                           , "xft:Fontello:pixelsize=12"
                           , "xft:Iosevka Nerd Font:style=Book:antialias=true:hinting=true:pixelsize=13"
                           , "xft:Iosevka Nerd Font:style=Regular:size=14:antialias=false:hinting=false"
                           , "xft:Fontello:pixelsize=20"
                           ]
       , bgColor = "#292d3e"
       , fgColor = "#f07178"
       , position = Bottom
       , commands = [
                    , Run Date " %b %d %Y - %H:%M " "date" 100
                    , Run UnsafeStdinReader
                    ]
       , sepChar = "%"
       , alignSep = "}{"
       , template = "%date%"  --freeze without %UnsafeStdinReader%
       }
`
xmonad.hs
`  xmproc0 <- spawnPipe "xmobar -x 0 ~/.xmonad/xmobarrc.pri-top"
  xmproc1 <- spawnPipe "xmobar -x 1 ~/.xmonad/xmobarrc.sec-top"
  xmproc2 <- spawnPipe "xmobar -x 2 ~/.xmonad/xmobarrc.sec-top"
  xmproc3 <- spawnPipe "xmobar -x 3 ~/.xmonad/xmobarrc.sec-top"
  xmproc4 <- spawnPipe "xmobar -x 0 ~/.xmonad/xmobarrc.pri-bottom" -- this one causes the freeze
  xmonad
    $ withUrgencyHook NoUrgencyHook
    $ ewmh
    $ addDescrKeys' ((myModMask, xK_F1), showKeybindings) myKeys
    $ myConfig {
      logHook = dynamicLogWithPP xmobarPP { 
                          ppOutput = \x -> hPutStrLn xmproc0 x  
                            >> hPutStrLn xmproc1 x
                            >> hPutStrLn xmproc2 x 
                            >> hPutStrLn xmproc3 x
                            >> hPutStrLn xmproc4 x
                        , ppCurrent = xmobarColor "#c3e88d" "" . wrap "[" "]" -- Current workspace in xmobar
                        , ppVisible = xmobarColor "#c3e88d" ""                -- Visible but not current workspace
                        , ppHidden = xmobarColor "#82AAFF" "" . wrap "*" ""   -- Hidden workspaces in xmobar
                        , ppHiddenNoWindows = xmobarColor "#c792ea" ""        -- Hidden workspaces (no windows)
                        , ppTitle = xmobarColor "#b3afc2" "" . shorten 60     -- Title of active window in xmobar
                        , ppSep =  "<fc=#666666><fn=1> | </fn></fc>"          -- Separators in xmobar
                        , ppUrgent = xmobarColor "#C45500" "" . wrap "!" "!"  -- Urgent workspace
                        , ppExtras  = [windowCount]                           -- # of windows current workspace
                        , ppOrder  = \(ws:l:t:ex) -> [ws,l]++ex++[t]
                        , ppSort = getSortByXineramaRule
                        }

    }
`

-- Like I said, its working by loading the pri-bottom-xmobar by startupHook:
`myStartupHook = return() >> do
  spawn "xmobar ~/.xmonad/xmobarrc.pri-bottom &"
  ...
`
This solution has the disadvantage that the bar is never killed or reloaded with xmonad... so, maybe there is a more elegant way to handle 5 bars on 4 monitors...

**Comment by Unoqwy** [comment]
You haven't read my previous comment. You are running `UnsafeStdinReader` in the commands section but never using it in the template, remove it from the commands list. It should fix your problem without having to spawn the bars weirdly.

**Comment by meissnol** [comment]
ehm,... it works when I remove the StdinReader from Commandslist **and** remove the unneccessary spawnPipe in dynamicLog ppOutput... So, really my mistake, I've tried so many things for quite a few hours and haven't seen the obvious... :D

**Comment by Gavlan-Wheel** [comment]
You can still spawn your bar via xmonad, you just need to remove this line
`>> hPutStrLn xmproc4 x`
That makes your xmonad loghook write to a pipe that's not being read, which causes the freeze.

That same exact mistake is referenced in the Archwiki's page by doing a little search:
https://wiki.archlinux.org/index.php/Xmobar
