### ISSUE TITLE
Socket error, even when building from source

### ISSUE THREAD

**Issue by formula-spectre** [jaor/xmobar#483]
Os: Artix Linux, openRC
Error in question:  
`SocketError {socketErrorMessage = "Network.Socket.connect: <socket: 12>: does not exist (No such file or directory)", socketErrorFatal = True, socketErrorAddress = Just (Address "unix:path=/run/user/1000/bus")}  ```
I tried to install both the xmobar, xmobar-git and with stack. But it Always gives out this error. Any idea?

**Comment by slotThe** [comment]
Have you had a look at [1] and does installing these (possibly) missing packages solve your problem?  In either case, we are probably going to need the full error message. 

[1] https://old.reddit.com/r/xmonad/comments/hfiaeo/xmobar_fails_to_build_with_stack/

**Comment by slotThe** [comment]
Have you had a look at [1] and does installing these (possibly) missing packages solve your problem?  In either case, we are probably going to need the full error message. 

[1] https://old.reddit.com/r/xmonad/comments/hfiaeo/xmobar_fails_to_build_with_stack/

**Comment by formula-spectre** [comment]
I'm gonna try. Thank you very much.
