### ISSUE TITLE
How to hide widget space, when the script or widget is being used?

### ISSUE THREAD

**Issue by apoorv569** [jaor/xmobar#484]
I have several custom scripts running on my `xmobar` for showing a icon if my webcam of microphone is in use, or if a external USB drive is connected and for the `locks` widget that shows `caps` or `num` lock state. The problem is when they are not active, the bar just shows so much empty space on the place of that widget, I also have ` | ` to separate the widgets and they keep showing for no reason. It makes the bar look kinda weird and waste a lot of space, especially on my laptop, I have very little space left for showing my current open/focused window title.

Bar when widgets not active.
![2020-08-18_03-41](https://user-images.githubusercontent.com/53279454/90449859-eae23200-e105-11ea-9636-ed3327debe57.png)

Bar when widgets are active.
![2020-08-18_03-44](https://user-images.githubusercontent.com/53279454/90449887-f7ff2100-e105-11ea-89d3-ffe6354a00f4.png)

**Comment by Unoqwy** [comment]
Would you mind sharing your config or instructions to reproduce the issue?

**Comment by apoorv569** [comment]
> Would you mind sharing your config or instructions to reproduce the issue?

Sure. Here is my [Xmobar](https://gitlab.com/apoorv569/dotfiles/-/blob/master/.config/xmobar/xmobarrc-l) and here are the [Scripts](https://gitlab.com/apoorv569/dotfiles/-/tree/master/.local/bin/statusbar). There are 2 `xmobar` configs here, the one with `-l` in the name is for my laptop, which I sent the screenshot and the link for. Though this also happens on the desktop.

**Comment by Unoqwy** [comment]
The spaces actually come your config, a workaround would be to move them into your scripts.
![IMG_20200819_114457.jpg](https://user-images.githubusercontent.com/65187632/90619586-b52a6f80-e211-11ea-8518-1420b70c4720.jpg)

**Comment by apoorv569** [comment]
> The spaces actually come your config, a workaround would be to move them into your scripts.
> ![IMG_20200819_114457.jpg](https://user-images.githubusercontent.com/65187632/90619586-b52a6f80-e211-11ea-8518-1420b70c4720.jpg)

Yes, moving the spaces to the scripts kind of works, but I use those scripts on other WM/Panels also, I would have to change the spaces every time for use with other panels. Is there no way for `xmobar` to just ignore the widget space, if its not active. For example in `polybar` when a certain widget is not in use or active, it ignores its space and format everything else properly. And also I have this ` | ` as a delimiter, it just stays there, when widget not active. It just looks weird, problem is I have so many widgets active at once, on my desktop it looks way better because of bigger screen and resolution than laptop, so I hardly notice it. On my laptop there hardly space left for the window title. :disappointed:

**Comment by Unoqwy** [comment]
A plugin could be written for this but I don't think it's necessary. What I'd do instead is a small script that adds the spaces (and a right (or left?) `|`) for any script if the output is not empty. You'd have to change the path of each `Com` to this script and move the path of the actual script to the list of arguments. To replace the `%webcam% %microphone%` by one `Com`, you can accept multiple scripts as arguments in your "spaces-script" and join them with a space.
<details>
<summary>quick example with piping</summary>

`sh "your-script" | xargs -I "%" echo " % |"` (prints nothing if `your-script` outputs nothing)
</details>
