### ISSUE TITLE
Volume module not recognizing color options

### ISSUE THREAD

**Issue by DMaxter** [jaor/xmobar#485]
When I try to change the color of `on` and `off` it says

`unrecognized option ...`

I tried both the long and short form, but it can't recognize them (-C, --onc, -c, --offc)

**Comment by jaor** [comment]
On Mon, Aug 24 2020, Daniel Matos wrote:

> I tried both the long and short form, but it can't recognize them (-C,
> --onc, -c, --offc)

are you forgetting to start your extra arguments with "--"

**Comment by DMaxter** [comment]
No, here is what I am trying:

```Haskell
Run Volume "default" "Master" [ "-C", "#ffffff", "-c", "#0000ff"] 10
```

**Comment by jaor** [comment]
On Mon, Aug 24 2020, Daniel Matos wrote:

> No, here is what I am trying:
>
> Run Volume "default" "Master" [ "-C", "#ffffff", "-c", "#0000ff"] 10

try:

       Run Volume "default" "Master" ["--", "-C", "#ffffff", "-c", "#0000ff"] 10

All the additional "args", not shared with other monitors, have to come
after "--".

**Comment by DMaxter** [comment]
That was it, thx
