### ISSUE TITLE
xmobar-0.35 does not compile

### ISSUE THREAD

**Issue by Tanjmaxalb** [jaor/xmobar#486]
Hi! I try to install xmobar via: `cabal install xmobar --flags="all_extensions"`. However, I got multiple errors:  

![image](https://user-images.githubusercontent.com/6904627/93502421-e6957880-f940-11ea-923b-0e4dfa6a89b9.png)

I have 8.0.2 version of ghc. Anyone could describe me the cause of this?

**Comment by slotThe** [comment]
On Thu, Sep 17 2020 09:56, Tanjmaxalb wrote:
> Hi! I try to install xmobar via: `cabal install xmobar
> --flags="all_extensions"`. However, I got multiple errors:
> ![image](https://user-images.githubusercontent.com/6904627/93502421-e6957880-f940-11ea-923b-0e4dfa6a89b9.png)
> I have 8.0.2 version of ghc. Anyone could me describe the reason of
> this?

Starting with 0.35.1, we dropped support for very old versions of ghc
and are now expecting at least ghc 8.4.  You can either try to build an
earlier version of xmobar, upgrade your version of ghc, or stick a

    import Data.Monoid ((<>))

at the top of the respective modules (at least I think this is the only
non ghc-8.0/8.2 compatable feature that we are currently using).

**Comment by Tanjmaxalb** [comment]
Thank you for help! It's work 👍
