### ISSUE TITLE
Rendering font

### ISSUE THREAD

**Issue by fuelen** [jaor/xmobar#488]
Hello.

I use Arch Linux and after some update I noticed that letter spacing in xmobar was changed.
On the screen below you can see how font is rendered in guake and in xmobar
![зображення](https://user-images.githubusercontent.com/588762/94410648-44fff980-0180-11eb-91b6-8d39b7b13596.png)
Guake uses `Terminus Medium 12`. xmobar has the following line in config file:
```
font              = "xft:Terminus:pixelsize=14:antialias=false:hinting=false"
```
They look similar but there is a difference in letter spacing.

When I change `pixelsize` to 12 in xmobar:
![зображення](https://user-images.githubusercontent.com/588762/94411106-d96a5c00-0180-11eb-9240-2c6e3fdcc305.png)
Why it works like this?

**Comment by fuelen** [comment]
dunno what happened, but after recent system update everything works as expected

**Comment by jaor** [comment]
many thanks for reporting back! (we haven't changed anything related to
fonts lately, so i'm also at a loss as to what happened :))
