### ISSUE TITLE
How to install xmobar library for pure Haskell configuration is unclear

### ISSUE THREAD

**Issue by mwatts15** [jaor/xmobar#491]
The README describes installing using cabal. I've run
```
cabal install -fwith_xft -fwith_utf8 -fwith_nl80211 -fwith_inotify xmobar
```

Doing so installs xmobar to the ~/.cabal directory. Adding a haskell configuration to `~/.config/xmobar/xmobar.hs` and running `xmobar` gives
```
Xmobar will use ghc to recompile, because "/home/user/.config/xmobar/build" does not exist.
Xmobar recompiling because some files have changed.
Error detected while loading xmobar configuration file: /home/user/.config/xmobar/xmobar.hs

xmobar.hs:1:1: error:
    Could not find module ‘Xmobar’
    Use -v to see a list of the files searched for.
  |
1 | import Xmobar
  | ^^^^^^^^^^^^^

Please check the file for errors.
```

Is running `cabal install xmobar` the correct way to install the library? Is there some additional step to make it available to `xmobar` or `ghc` for compilation?

**Comment by slotThe** [comment]
Try `cabal install xmobar --lib`.

**Comment by mwatts15** [comment]
I think the example command line added in #492 is sufficient to point out what's required, so closing this issue.
