### ISSUE TITLE
DST change not affecting Date plugin

### ISSUE THREAD

**Issue by loop54-christoffer** [jaor/xmobar#494]
My config includes a command

```haskell
Run Date "D: %B %d %A W%V" "date" 10
```

and while my system time has automatically reflected the local DST switch the night before last, my xmobar keeps ticking on with the pre-switch time. Am I doing something wrong or is this an oversight in the implementation?

**Comment by jaor** [comment]
On Mon, Oct 26 2020, Christoffer wrote:

> My config includes a command
>
> Run Date "D: %B %d %A W%V" "date" 10
>
> and while my system time has automatically reflected the local DST
> switch the night before last, my xmobar keeps ticking on with the
> pre-switch time. Am I doing something wrong or is this an oversight in
> the implementation?

I think that the DST info is read only once on startup, so it's not
refreshed unless one restarts xmobar.  If that's really the case,
reading it over an over with every refresh would be perhaps a bit
overkill for an event that happens twice a year.  But i would have to
look closer at the code to confirm that's really what's going on.

**Comment by slotThe** [comment]
On Mon, Oct 26 2020 00:41, jao wrote:
> I think that the DST info is read only once on startup, so it's not
> refreshed unless one restarts xmobar.

This seems to be what's going on.  The startup command for `Date` is
simply

    start (Date f _ r) cb = do
      t <- getCurrentTime
      zone <- getTimeZone t
      go zone
     where
      go zone = doEveryTenthSeconds r $ date zone f >>= cb

so `date` gets the time-zone (which includes things like DST) that was
current when the plugin was started.

**Comment by loop54-christoffer** [comment]
Yeah, that makes sense.

Of course, the details of the affair is complicated, but I think most places that observe DST switch during the first few hours after midnight, so refreshing the time zone nightly should be an improvement over the current situation, though of course still not ideal.

Even the places where the DST switch does not happen just after midnight, the switch is likely to happen during a full hour, so updating the timezone at a minute past the hour would cover almost all remaining cases.

That said, the simplest thing is probably to get the timezone with every refresh, as overkill as it may seem.

**Comment by 0** [comment]
The current DST transition might be the first time most people encounter #456. Restarting xmobar was a reasonable workaround once I realized that it was showing the wrong time, but it's probably undesirable to have a clock that can't be trusted to always be correct.

**Comment by jaor** [comment]
On Sat, Oct 31 2020, Dmitri Iouchtchenko wrote:

> The current DST transition might be the first time most people
> encounter #456. Restarting xmobar was a reasonable workaround once I
> realized that it was showing the wrong time, but it's probably
> undesirable to have a clock that can't be trusted to always be
> correct.

I tend to agree.  Re-reading that thread now, it's not at all clear to
me that we're really saving that huge amount of perf by avoiding an FFI
call.  I am tempted to revert #456, or perhaps make that behaviour an
opt-in: @psibi, what do you think?

**Comment by psibi** [comment]
@jaor Okay, this is an issue. I would prefer making this behaviour an opt-in.

**Comment by loop54-christoffer** [comment]
My unsolicited opinion is that it seems reasonable to first get it right and only then get it fast (without getting it un-right in the process.)

If performance is an issue a more complicated (but still relatively straightforward) solution is, I suppose, to set up a rolling refresh time budget for the Date plugin (so e.g. it starts out with 100 milliseconds, gets another 2 milliseconds for each refresh, and subtracts whatever time it took to do the refreshing). When that budget is exceeded it avoids doing whatever expensive calls it would otherwise do (e.g. to get time zone) until it can work back a surplus of refreshing time budget to afford another expensive call.

That should result in a close to optimal resource usage-correctness tradeoff for all users with no configuration needed.

**Comment by psibi** [comment]
@loop54-christoffer  Note that we did get it right initially. And I made it buggy later. :-)

What I'm proposing is a solution like this:
* Date original behaviour should be restored
* Introduce a new constructor: DateWithInitialTimezone with this behaviour of fixed time zones

That way users can choose it explicitly what they what and most will just stick to using `Date`. I will see if I can patch in a couple of days or by this weekend. But if anybody wants to fix it before that, please free feel to.

**Comment by jaor** [comment]
On Mon, Nov 02 2020, Sibi Prabakaran wrote:

> What I'm proposing is a solution like this:
>
>   • Date original behaviour should be restored
>   • Introduce a new constructor: DateWithInitialTimezone with this
>     behaviour of fixed time zones

Yeah, this sounds good enough to me.

**Comment by jaor** [comment]
On Mon, Nov 02 2020, Christoffer wrote:

> My unsolicited opinion is that it seems reasonable to first get it
> right and only then get it fast (without getting it un-right in the
> process.)

Agreed.

> If performance is an issue a more complicated (but still relatively
> straightforward) solution is, I suppose, to set up a rolling refresh
> time budget for the Date plugin (so e.g. it starts out with 100
> milliseconds, gets another 2 milliseconds for each refresh, and
> subtracts whatever time it took to do the refreshing). When that
> budget is exceeded it avoids doing whatever expensive calls it would
> otherwise do (e.g. to get time zone) until it can work back a surplus
> of refreshing time budget to afford another expensive call.

Honestly, I don't think it's worth the effort implementing it this way,
unless the degradation in performance for that call is really noticeable
for everyone.  Circumstantial evidence seems to indicate that this only
happened to @psibi so far... but maybe i wasn't looking close enough, at
least in my case.

**Comment by liskin** [comment]
This was fixed by #498 and #501.
Do we keep it open for visibility or close this?

The rolling refresh budget solution by @loop54-christoffer sounds interesting (I'm only just reading it now), but it's hard to do this without making it more expensive than the actual timezone refresh itself. So the solution I chose in #503 is to simply refresh once a minute.

**Comment by jaor** [comment]
google will find it anyway, let's close.
