### ISSUE TITLE
Showing percent symbol next to the each of the values obtained from xmobar's MultiCpu <autototal>

### ISSUE THREAD

**Issue by adder46** [jaor/xmobar#495]
I'm searching the web for some documentation, or even ready made config files, as for how to show a percentage symbol next to the each of the values obtained by xmobar's MultiCpu <autototal>.

I'm not sure it's even possible, so I reckoned it's best to ask the author.

Any pointers are appreciated.

**Comment by jaor** [comment]
Does adding to the monitor args `"-s", "Yes"` work?
(see https://github.com/jaor/xmobar#default-monitor-arguments)

**Comment by adder46** [comment]
Yes, that works. Thanks very much.
