### ISSUE TITLE
Conditional and/or auto-updating alpha?

### ISSUE THREAD

**Issue by ghost** [jaor/xmobar#499]
So I'm new to xmobar and I was wondering if there is a way to update the alpha of xmobar at runtime? I know we can specify the `alpha` parameter in the config and that works when then restarting xmobar and reloading the config but is there a way to change the alpha without restarting xmobar? like triggering a redraw somehow?

Additionally, assuming the above is possible, is there a way to change the alpha based on a condition and then triggering the alpha update? I currently have some workspace widgets being "injected" into xmobar using Run UnsafeStdInReader and part of that actually includes the current selected xmonad layout. I'm thinking it would be cool to parse the text coming to identify the current layout, and then update the xmobar bg alpha accordingly e.g. have it be transparent for some layouts and have it show the bgcolour if a full-screen layout is chosen.

Is this possible in any way?

Sorry for the wall of text, great project by the way!

**Comment by jaor** [comment]
> Is this possible in any way?

no, not right now.  alpha affects all monitors and the main window, and
it's read and propagated at startup.  i guess we would need to put it in
a state monad and then maybe capture a special signal to change it or
use the dbus interface.  but there's nothing quick in place i can think
of.

**Comment by linuxhype** [comment]
oh yea maybe a custom SIGNAL would work and then redraw using that signal. Another option is to have the alpha be part of the template somehow e.g. have an <alpha=0> tag or something which gets evaluated on template change and then triggers a redraw

**Comment by linuxhype** [comment]
mhm I wonder if a signal is the right approach though, since there isn't really a standard signal for what we're trying to do and you are already using the two custom signals SIGUSR1 and SIGUSR2. Also, we would probably want to have a way to pass the alpha int value along as well so signals aren't really great.

Maybe we can use the process stdin? ofc we would have to change it to not interfere with what is happening with unsafestdinreader but we would introduce a convention where flags are passed first followed by the things to be injected into template e.g. --alpha=0 --template=<templateinjection>

**Comment by jaor** [comment]
On Wed, Nov 04 2020, linuxhype wrote:

> mhm I wonder if a signal is the right approach though, since there
> isn't really a standard signal for what we're trying to do and you are
> already using the two custom signals SIGUSR1 and SIGUSR2. Also, we
> would probably want to have a way to pass the alpha int value along as
> well so signals aren't really great.

yes, signals aren't going to work.

> Maybe we can use the process stdin? ofc we would have to change it to
> not interfere with what is happening with unsafestdinreader but we
> would introduce a convention where flags are passed first followed by
> the things to be injected into template e.g. --alpha=0 --template=

we have monitors that read pipes and files, no need to interfere with
stdin.  xmobar could react to incoming configuration parameters from a
configurable pipe or file path.

i think a dbus signal would be much cleaner than that, even though it's
less universal.

**Comment by linuxhype** [comment]
> i think a dbus signal would be much cleaner than that, even though it's less universal.

yea, I submitted a PR which exposes it as a dbus signal. See #500
