### ISSUE TITLE
Can't parse config

### ISSUE THREAD

**Issue by aplainzetakind** [jaor/xmobar#507]
The Alsa line in my config is causing a problem. Here's my xmobarrc:

```
Config { -- font = "xft:Misc Tamsyn:pixelsize=14:style=Regular"
       font = "-misc-fixed-*-*-*-*-10-*-*-*-*-*-*-*"
       , additionalFonts = []
       , borderColor = "black"
       , border = TopB
       , bgColor = "black"
       , fgColor = "grey"
       , alpha = 255
       , position = Top
       , textOffset = -1
       , iconOffset = -1
       , lowerOnStart = False
       , pickBroadest = False
       , persistent = True
       , hideOnStart = False
       , iconRoot = "."
       , allDesktops = True
       , overrideRedirect = True
       , sepChar = "%"
       , alignSep = "}{"
       , template = " %cpu% * %coretemp% | %memory% * %swap% | %dynnetwork% }\
                    \{ %battery% | %default:Master% |  %date% "
       , commands = [ Run Weather "EGPF" ["-t","<station>: <tempC>C",
                                          "-L","18","-H","25",
                                          "--normal","green",
                                          "--high","red",
                                          "--low","lightblue"] 36000
                    , Run DynNetwork ["-L","0","-H","32",
                                          "--normal","green","--high","red"] 10
                    , Run Network "wlp3s0" ["-L","0","-H","32",
                                          "--normal","green","--high","red"] 10
                    , Run Cpu ["-L","3","-H","50",
                               "--normal","green","--high","red"] 10
                    , Run Memory ["-t","Mem: <usedratio>%"] 10
                    , Run Swap [] 10
                    , Run Com "uname" ["-s","-r"] "" 36000
                    , Run Date "%a %b %_d %Y %H:%M" "date" 10
                    , Run BatteryP ["BAT0"]
                                   ["-t", "<acstatus>"
                                    , "-L", "10", "-H", "80"
                                    , "-l", "red", "-h", "green"
                                    , "--", "-O", "Charging", "-o", "Battery:\
                                    \ <left>% <timeleft>"
                                   ] 10
                    , Run Alsa "default" "Master" []
                    , Run CoreTemp ["-t", "Temp:<core0>C",
                                    "-L", "40", "-H", "60",
                                    "-l", "lightblue", "-n", "gray90", "-h", "red"] 50
                    ]
       }
```

xmobar tells me this is an invalid configuration file. If I comment out the `Run Alsa` line, it works. I have no idea what's wrong with that line. Since this is a parse error, it shouldn't be relevant, but I tried `start ( read "Run Alsa \"default\" \"Master\" []" :: Runnable ) print` in ghci to see that xmobar can talk to my alsa, which it does. I have no idea what's wrong with that line and I'm stumped.

**Comment by jaor** [comment]
this usually means that your xmobar is not compiled with alsa support.

**Comment by aplainzetakind** [comment]
Indeed it wasn't, I somehow accidentally built from master and not the branch I configured. Thanks.

However, after launch, where I should see the sound status remains stuck at Updating... (I change volume and still no joy).

**Comment by jaor** [comment]
On Wed, Nov 18 2020, aplainzetakind wrote:

> However, after launch, where I should see the sound status remains
> stuck at Updating... (I change volume and still no joy).

it's less efficient and uses polling, but i use `Volume` instead of
`Alsa`... something like

   Volume "default" "Master" ["-t", "<volume>"] 10

IIRC, `Alsa` launches an alsactl process to monitor changes
asynchronously.... maybe that's wreaking havoc in your case
(e.g. because it's not in your path)?

**Comment by aplainzetakind** [comment]
OK, I reverted to `Volume`, which works.
Though alsactl is in my path and as I said I could start the alsa command from ghci and see it updating as I changed the volume, so it's puzzling.

Thanks.

**Comment by slotThe** [comment]
On Wed, Nov 18 2020 12:25, aplainzetakind wrote:
>        , template = " %cpu% * %coretemp% | %memory% * %swap% | %dynnetwork% }\
>                     \{ %battery% | %default:Master% |  %date% "

you have to add an additional `alsa` in front of the volume part of the
template string.  Quoting from the readme:

> - Aliases to `alsa:` followed by the mixer name and element name
>   separated by a colon. Thus, `Alsa "default" "Master" []` can be used
>   as `%alsa:default:Master%`.

**Comment by aplainzetakind** [comment]
> On Wed, Nov 18 2020 12:25, aplainzetakind wrote: , template = " %cpu% * %coretemp% | %memory% * %swap% | %dynnetwork% }\ \{ %battery% | %default:Master% | %date% "
> you have to add an additional `alsa` in front of the volume part of the template string. Quoting from the readme:
> […](#)
> - Aliases to `alsa:` followed by the mixer name and element name separated by a colon. Thus, `Alsa "default" "Master" []` can be used as `%alsa:default:Master%`.

Great. Thanks for spotting it.
