### ISSUE TITLE
Use tripple backticks in readme

### ISSUE THREAD

**Issue by slotThe** [jaor/xmobar#508]
A thing I've noticed while working on a new monitor:

In the `readme.md` file we are using indentation to mark things as code.
Sadly, this doesn't add any syntax highlighting to the examples, but
because the configuration language is essentially a subset of Haskell, I
think it would be a net-win if we (using the tripple backtick syntax)
marked everything as Haskell code.

I would do this myself, but I can see (well, it's more of a guess) that
the readme is generated from `org-mode`, and I can't find a `readme.org`
file anywhere!  It's possible to do this by using e.g. [1] to export the
file to "GitHub flavoured markdown".

[1] https://github.com/larstvei/ox-gfm

**Comment by jaor** [comment]
@slotThe, no, the file is not auto-generated from org, it's written
directly as markdown.  i use an emacs helper to generate the index,
instead of maintaining it by hand, but that's invisible to git commits,
which only see the changes.  so by all means go ahead! :)
