### ISSUE TITLE
Splitting up the readme

### ISSUE THREAD

**Issue by slotThe** [jaor/xmobar#512]
The README has grown quite big, so much so that I think searching in it
is quite difficult at this point.  Someone coming to the repo with no
prior knowledge will probably be completely overwhelmed by the amount of
information and thus might not even know where to start.

What I propose is splitting up the README into several smaller files,
e.g. one "this is the absolute minimum you need to know for installing
xmobar" (which would become the new README), a handbook that details all
of the different monitors (which would contain most of the current
README), some sort of FAQ, a "how to write your own monitor", etc.

This would be quite a big change (and user-facing as well), so I wanted
to gather a bit of feedback before attempting this.

**Comment by jaor** [comment]
this has been in my todo list for a long time, and i'd really appreciate
your help here, yes.  i agree with your diagnosis, and moreover i don't
like at all the trend these days to point users to github repos for
user-level documentation.  that's why i got the xmobar.org domain, and a
little helper (in doc/) to generate, using pandoc, a website there.  but
of course right now that website is bad in the same way as our readme :)

your initial list of split documents sounds also reasonable to me, and
we can always refine it as we go (but would love to hear from other
contributors!).  i am also open to use other formats, if you have a
preference there.  for instance, personally, i'd go for .org over .md (i
inherited the latter but find the former more to my tastes), but
markdown is a good option too, specially if it's what you prefer.



-- 
Nature uses as little as possible of anything.
  -Johannes Kepler, astronomer (1571-1630)

**Comment by slotThe** [comment]
I'm also really interested in what other contributors think!

On Mon, Nov 30 2020 13:31, jao wrote:
> i agree with your diagnosis, and moreover i don't like at all the
> trend these days to point users to github repos for user-level
> documentation.  that's why i got the xmobar.org domain, and a little
> helper (in doc/) to generate, using pandoc, a website there.  but of
> course right now that website is bad in the same way as our readme :)

Oh that's pretty cool actually.  I wonder how far pandoc can go there,
I've never thought of generating a website with it!

> i am also open to use other formats, if you have a preference there.
> for instance, personally, i'd go for .org over .md (i inherited the
> latter but find the former more to my tastes), but markdown is a good
> option too, specially if it's what you prefer.

Well, I'm sort of torn on this one.  I would very much prefer .org, but
I also recognize that not everyone has seen the light of Emacs yet.  I
think .md would be a "safer" choice in the sense that it's more
approachable, especially when it comes down to people looking at (and
improving) documentation on their own machines.

**Comment by jaor** [comment]
On Tue, Dec 01 2020, slotThe wrote:

> On Mon, Nov 30 2020 13:31, jao wrote:
>> i agree with your diagnosis, and moreover i don't like at all the
>> trend these days to point users to github repos for user-level
>> documentation. that's why i got the xmobar.org domain, and a little
>> helper (in doc/) to generate, using pandoc, a website there. but of
>> course right now that website is bad in the same way as our readme :)
>
> Oh that's pretty cool actually. I wonder how far pandoc can go there,
> I've never thought of generating a website with it!

i don't have lots of experience with it, but it seems flexible enough
to, for instance, even do the split for us from a single file.  but it's
better if the sources are already split.

>> i am also open to use other formats, if you have a preference there.
>> for instance, personally, i'd go for .org over .md (i inherited the
>> latter but find the former more to my tastes), but markdown is a good
>> option too, specially if it's what you prefer.
>
> Well, I'm sort of torn on this one. I would very much prefer .org, but
> I also recognize that not everyone has seen the light of Emacs yet.

you know, that's my first reaction too, but then i think it's most
probably less of a problem that we tend to think at first.  

the number of people willing to write decent docs (at the level of those
you wrote for the notmuch plugin) is very small.  so it's no use making
things less convenient to people writing real documentation just to
lower the barrier for those than never write documentation anyway :)

i'm exaggerating, and it's true contributors add to the readme more
regularly than i'm suggesting above, but it's usually in the form of a
few sentences, following a pattern already there, and at that level
there's not much difference between org and md.

and then there's the fact that, for instance, i'd write more docs if
they were in org :)

> I think .md would be a "safer" choice in the sense that it's more
> approachable, especially when it comes down to people looking at (and
> improving) documentation on their own machines.

it just occured to me that one actually needs emacs to edit org files
decently, so perhaps it's a bigger barrier than i'm thinking.

anyway, as you say, it'd be really nice to hear how other contributors
feel about this.  i am very proud of the long list we have, and wouldn't
want to hamper its growth!

**Comment by liskin** [comment]
> it just occured to me that one actually needs emacs to edit org files decently, so perhaps it's a bigger barrier than i'm thinking.
> anyway, as you say, it'd be really nice to hear how other contributors feel about this. i am very proud of the long list we have, and wouldn't want to hamper its growth!

It'd be the only project that I contribute to that would use org, but I don't think I'd be discouraged really. I'd just follow a pattern seen elsewhere and then check if github rendered it correctly when submitting a PR.
It might discourage me from contributing a larger change like this one, which I'm already extremely unlikely to contribute, so making it easier for the folks that actually do the work while not making it too hard for drive-by contributors definitely makes sense.
