### ISSUE TITLE
xmobar fails to install in Gentoo after source is correctly compiled: Filenotfounderror: readme.md

### ISSUE THREAD

**Issue by thunderrd** [jaor/xmobar#518]
I'm getting a 'File not found error' on readme.md, has the location or name of this file been changed?

`Preprocessing executable 'xmobar' for xmobar-0.37..
Building executable 'xmobar' for xmobar-0.37..
[1 of 1] Compiling Main             ( app/Main.hs, dist/build/xmobar/xmobar-tmp/Main.dyn_o )
Linking dist/build/xmobar/xmobar ...
>>> Source compiled.
 * Skipping make test/check due to ebuild restriction.
>>> Test phase [disabled because of RESTRICT=test]: x11-misc/xmobar-9999
​
>>> Install x11-misc/xmobar-9999 into /var/tmp/portage/x11-misc/xmobar-9999/image
./setup copy --destdir=/var/tmp/portage/x11-misc/xmobar-9999/image
Installing library in /var/tmp/portage/x11-misc/xmobar-9999/image/usr/lib64/xmobar-9999/ghc-8.8.4
Installing executable xmobar in /var/tmp/portage/x11-misc/xmobar-9999/image/usr/bin
Warning: The directory /var/tmp/portage/x11-misc/xmobar-9999/image/usr/bin is
not in the system search path.
Reading package info from stdin ... done.
xmobar-0.37: Warning: haddock-interfaces: /usr/share/doc/xmobar-9999/html/xmobar.haddock doesn't exist or isn't a file
xmobar-0.37: Warning: haddock-html: /usr/share/doc/xmobar-9999/html doesn't exist or isn't a directory
xmobar-0.37: dependency "X11-1.9.2-G7NjoEqGFnm6h5xbSReyYC" doesn't exist (ignoring)
xmobar-0.37: dependency "X11-xft-0.3.1-9sdIzMmv3489rAzacqgutg" doesn't exist (ignoring)
xmobar-0.37: dependency "alsa-core-0.5.0.1-K0SXio6EcM1GW9NwssjHIV" doesn't exist (ignoring)
xmobar-0.37: dependency "alsa-mixer-0.3.0-1I5T9An2neOISzuUiVqd6Y" doesn't exist (ignoring)
xmobar-0.37: dependency "async-2.2.2-GZ93PJht51l5SQPrKLdOt0" doesn't exist (ignoring)
xmobar-0.37: dependency "base-4.13.0.0" doesn't exist (ignoring)
xmobar-0.37: dependency "bytestring-0.10.10.1" doesn't exist (ignoring)
xmobar-0.37: dependency "containers-0.6.2.1" doesn't exist (ignoring)
xmobar-0.37: dependency "dbus-1.2.16-3BvoBmvYW6sJoOin46Bwi2" doesn't exist (ignoring)
xmobar-0.37: dependency "directory-1.3.6.0" doesn't exist (ignoring)
xmobar-0.37: dependency "extensible-exceptions-0.1.1.4-4QtxTJe11myLMCZi4yvSzl" doesn't exist (ignoring)
xmobar-0.37: dependency "filepath-1.4.2.1" doesn't exist (ignoring)
xmobar-0.37: dependency "http-client-tls-0.3.5.3-1TAslIvrNZc3yJ7MAFrEV3" doesn't exist (ignoring)
xmobar-0.37: dependency "http-conduit-2.3.7.3-1tPufhyaDqK6w1ag4NEapd" doesn't exist (ignoring)
xmobar-0.37: dependency "http-types-0.12.3-3xrqxrl7cND4UtF6gRr8Fa" doesn't exist (ignoring)
xmobar-0.37: dependency "mtl-2.2.2" doesn't exist (ignoring)
xmobar-0.37: dependency "old-locale-1.0.0.7-KOGgqu8HfWChZyQBUEp1c" doesn't exist (ignoring)
xmobar-0.37: dependency "parsec-3.1.14.0" doesn't exist (ignoring)
xmobar-0.37: dependency "parsec-numbers-0.1.0-B3XL5cjdVe6Dmow8oLPL90" doesn't exist (ignoring)
xmobar-0.37: dependency "process-1.6.9.0" doesn't exist (ignoring)
xmobar-0.37: dependency "regex-compat-0.95.2.0-3qBVvPDU6WdKBimr6jT8qa" doesn't exist (ignoring)
xmobar-0.37: dependency "stm-2.5.0.0" doesn't exist (ignoring)
xmobar-0.37: dependency "time-1.9.3" doesn't exist (ignoring)
xmobar-0.37: dependency "transformers-0.5.6.2" doesn't exist (ignoring)
xmobar-0.37: dependency "unix-2.7.2.2" doesn't exist (ignoring)
xmobar-0.37: dependency "utf8-string-1.0.1.1-K3Cc2i5eeGM49mkpXdBKoc" doesn't exist (ignoring)
xmobar-0.37: cannot find any of ["libHSxmobar-0.37-79dGhQegBHvEJUG8YsY0KP.a","libHSxmobar-0.37-79dGhQegBHvEJUG8YsY0KP_p.a","libHSxmobar-0.37-79dGhQegBHvEJUG8YsY0KP-ghc8.8.4.so","libHSxmobar-0.37-79dGhQegBHvEJUG8YsY0KP-ghc8.8.4.dylib","HSxmobar-0.37-79dGhQegBHvEJUG8YsY0KP-ghc8.8.4.dll"] on library path (ignoring)
Traceback (most recent call last):
  File "/usr/lib/portage/python3.8/doins.py", line 594, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/portage/python3.8/doins.py", line 582, in main
    if _doins(
  File "/usr/lib/portage/python3.8/doins.py", line 434, in _doins
    return install_runner.install_file(source, os.path.dirname(dest))
  File "/usr/lib/portage/python3.8/doins.py", line 370, in install_file
    return self._ins_runner.run(source, dest_dir)
  File "/usr/lib/portage/python3.8/doins.py", line 179, in run
    sstat = os.stat(source)
FileNotFoundError: [Errno 2] No such file or directory: b'readme.md'
 * ERROR: x11-misc/xmobar-9999::haskell failed (install phase):
 *   dodoc failed`

**Comment by jaor** [comment]
oh, yes, we've moved doc files around.  i've pushed a patch that should
solve the problem.

**Comment by jaor** [comment]
closing since no further feedback was provided and a (hopefully
working!) patch provided
