### ISSUE TITLE
Com command are not updated when xmobar receives SIGUSR2

### ISSUE THREAD

**Issue by toniz4** [jaor/xmobar#519]
I have a script that displays the current playing song in cmus, it would be nice to make the bar update when i change songs or click the bar to pause the song. But when changing the song and after executing `kill -12 $(pidof xmobar)` it doesn't update like expected. Am i doing something wrong or it is a bug?

**Comment by jaor** [comment]
SIGUSR2 doesn't trigger any monitor, just repositions the bar in the
screen.

For actions on clicking the bar, you can use

    - <action=`command` button=12345>...</action> will execute given command when
     clicked with specified buttons. If not specified, button is equal to 1
     (left mouse button). Using old syntax (without backticks surrounding
     =command=) will result in =button= attribute being ignored.

(see "The output template" in doc/quick-start.org).  Instead of sending
a signal, your script could write to a named pipe, and the use one of
the Pipe monitors in xmobar (see "Pipe-based logging" in doc/plugins.org).

**Comment by toniz4** [comment]
Sorry for the delay. Thanks, i managed to make it work. Just for documentation sake, this is how i made it work:

I made this script to output a formatted line with the artist and song, it's pretty messy.
```sh
#!/bin/sh

if $(pidof cmus > /dev/null); then

	max=35
	icon=" "

	status="$(cmus-remote -Q)"

	[ "$(echo "$status" | awk '/status/{$1=""; print $0}'| sed 's/ //g')" = "paused" ] && iconplay="" || iconplay=""

	song="$(echo "$status" | awk '/title/{$1=$2=""; print $0}'| sed 's/  //')"
	artist="$(echo "$status" | awk '/ artist /{$1=$2=""; print $0}' | sed 's/  //')"

	[ -n "$artist" ] && [ -n "$song" ] && fullstatus="$artist - $song" || fullstatus=""

	playing="$(echo "$fullstatus" | awk 'NR==1 && !/^volume:/ { printf "%.'$max's", $0
		if (length($0)>'$max') printf "..." }')"

	printf "%s%s%s\n" "$icon" "$playing" "$iconplay"
else
	echo ""
fi
``` 

Then i make another script to write the output of musicstatus to a fifo, and set that as the `status_display_program` in cmus
```sh
#!/bin/sh

fifofile="/tmp/cmus-pipe"

[ -e "$fifofile" ] || mkfifo "$fifofile"

echo "$(musicstatus)" > "$fifofile"
```

And then i run PipeReader in this pipe. The result is this:
![2021-01-19-182310_1366x14_scrot](https://user-images.githubusercontent.com/14265358/105094693-68c6b280-5a83-11eb-9cad-a5bdb03bd36c.png)

When pausing and changing the song the bar is updated, since cmus executes the status_display_program every time there is a event inside cmus.

**Comment by jaor** [comment]
On Tue, Jan 19 2021, toniz4 wrote:

> Sorry for the delay. Thanks, i managed to make it work. Just for
> documentation sake, this is how i made it work:

Thanks a lot for sharing! I didn't know about cmus, it looks
interesting.  I was about to suggest something like
https://github.com/cmus/cmus/wiki/status_display_short_text.sh, but i'm
sure you already know about that, and yours, if a bit messier as you
say, looks more in control of the final format.

**Comment by toniz4** [comment]
Actually i didn't had looked into that, thanks!
