### ISSUE TITLE
Expose all of Xmobar.Plugins.Monitors.Common

### ISSUE THREAD

**Issue by jnbooth** [jaor/xmobar#520]
Currently, only Xmobar.Plugins.Monitors.Common.Run and Xmobar.Plugins.Monitors.Common.Types are exposed. This makes it difficult to write a new monitoring plugin inside an xmobar-config project. In particular, Xmobar.Plugins.Monitors.Common.Parsers.parseTemplate and the functions in Xmobar.Plugins.Monitors.Common.Output for bars and icon patterns are practically necessary.

**Comment by jaor** [comment]
i see, thanks for pointing this out.  maybe we should think of a way
to export them with some qualification (instead of in the plain Xmobar
namespace), but still shorter than their default module (maybe
Xmobar.Parsers, XMobar.Output ... although then that'd maybe call for
renaming some of our current exports too)...

**Comment by jnbooth** [comment]
Xmobar.Plugins.Monitors.Common does re-export all of them, and that's what monitor plugins import, so you could simply expose that and not worry about the submodules.

**Comment by jaor** [comment]
On Sun, Jan 17 2021, Joshua Booth wrote:

> Xmobar.Plugins.Monitors.Common does re-export all of them, and that's
> what monitor plugins import, so you could simply expose that and not
> worry about the submodules.

not really, there's a name conflict for 'template', which is also in Types.

**Comment by jaor** [comment]
ah, please ignore my previous answer.  i've just exposed Common, as you
suggest.

exposing Common.Types and Common.Run is now redundant, but we could
break configurations out there, so i'm not sure if we should remove them.

**Comment by slotThe** [comment]
On Sun, Jan 17 2021 18:08, jao wrote:

> ah, please ignore my previous answer.  i've just exposed Common, as you
> suggest.
>
> exposing Common.Types and Common.Run is now redundant, but we could
> break configurations out there, so i'm not sure if we should remove
> them.

I suppose we would deprecate the modules as a whole, so people who
import them in their configurations get a warning, and then in a few
releases remove that deprecation and not expose the modules anymore

**Comment by jaor** [comment]
On Sun, Jan 17 2021, slotThe wrote:

[...]

> I suppose we would deprecate the modules as a whole, so people who
> import them in their configurations get a warning, and then in a few
> releases remove that deprecation and not expose the modules anymore

that sounds like a good idea... now i'll have to learn how to mark
modules as deprecated :)

**Comment by slotThe** [comment]
On Mon, Jan 18 2021 07:26, jao wrote:

> that sounds like a good idea... now i'll have to learn how to mark
> modules as deprecated :)

This is (thankfully) pretty straightforward; for example (taken from
xmonad-contrib):

    module XMonad.Layout.LayoutBuilderP {-# DEPRECATED "Use XMonad.Layout.LayoutBuilder instead" #-} (
      LayoutP (..),
      layoutP, layoutAll,
      B.relBox, B.absBox,
      -- * Overloading ways to select windows
      -- $selectWin
      Predicate (..), Proxy(..),
      ) where

**Comment by jaor** [comment]
On Mon, Jan 18 2021, slotThe wrote:

> On Mon, Jan 18 2021 07:26, jao wrote:
>
>> that sounds like a good idea... now i'll have to learn how to mark
>> modules as deprecated :)
>
> This is (thankfully) pretty straightforward; for example (taken from
> xmonad-contrib):
>
> module XMonad.Layout.LayoutBuilderP {-# DEPRECATED "Use XMonad.Layout.LayoutBuilder instead" #-} (

i see, thanks.  a complication here is that we want to deprecate these
modules for exported use only, but keep them internally, and i am not
sure if this would introduce spurious noise in our builds...

**Comment by slotThe** [comment]
On Mon, Jan 18 2021 08:07, jao wrote:

> i see, thanks.  a complication here is that we want to deprecate these
> modules for exported use only, but keep them internally, and i am not
> sure if this would introduce spurious noise in our builds...

Ah that's a good point of course...  

I'm not sure if we have any other deprecations, otherwise we could run
the CI with `-Wno-deprecations' (and remember to remove it after this is
done :)

**Comment by jaor** [comment]
On Mon, Jan 18 2021, slotThe wrote:

> I'm not sure if we have any other deprecations, otherwise we could run
> the CI with `-Wno-deprecations' (and remember to remove it after this
> is done :)

cheeky :) another possibility is just removing those two modules from
the exposed list and tell people who complain to use them from the newly
exported Common: i'm expecting anyone writing their configs as Haskell
programs to even figure it out by themselves!
