### ISSUE TITLE
Xmobar recompiles forever

### ISSUE THREAD

**Issue by e3pax** [jaor/xmobar#523]
Xmobar is not recompiling. If I do xmobar --recompile there is no output at all. I am on arch linux.
if I use -v option it outputs:

Fields missing from config defaulted: wmClass,wmName,border,borderColor,textOffset,textOffsets,iconOffset,overrideRedirect,pickBroadest,alpha,verbose

(all one line)

Configs:
http://ix.io/2OdN (xmonad)

http://ix.io/2OdO (xmobar)
(They are both almost copies of distrotube's config)

Xmonad works and recompiles fine, but I cannot recompile xmobar

**Comment by jaor** [comment]
you can only recompile xmobar is you write its config as a haskell
program.  if you're using a configuration file like the one you show,
you don't need to recompile it; just change the configuration and
restart it (that configuration is not compiled in any way).

see doc/writing-your-own-plugin.org and examples/xmobar.hs.

**Comment by e3pax** [comment]
Jaor has provided an explanation for my issue, this will be closed
