### ISSUE TITLE
Received exception <stdin>: hGetLine invalid argument (invalid byte sequence)

### ISSUE THREAD

**Issue by toniz4** [jaor/xmobar#524]
I'm having this error when displaying random web pages titles, like [this](https://github.com/neovimhaskell/haskell-vim/issues/109) one.
![2021-02-05-095324_1366x14_scrot](https://user-images.githubusercontent.com/14265358/107036984-3a421a80-6799-11eb-9b57-997404bba333.png)
My xmonad and xmobar config is in this repo: https://github.com/toniz4/xmonad-config

**Comment by oogeek** [comment]
Have you check your locale? Since I fixed it with setting LANG=en_US.UTF-8

**Comment by Linusero** [comment]
I have the same problem, but I think I have set my locale correctly. Could it be a problem with the font?

**Comment by liskin** [comment]
@Linusero No, if you're getting "invalid byte sequence", this is definitely not a font issue. Either the input isn't UTF-8, or the locale isn't UTF-8, or they're both wrong in different ways.

**Comment by Linusero** [comment]
I have set `LANG=es_ES.UTF-8` in `/etc/locale.conf` so I think the locale is set correctly to handle UTF. However, I get that error when accessing [this page](https://unicode-table.com/en/#combining-diacritical-marks), for example. Any idea of what I am doing wrong?

**Comment by liskin** [comment]
What does

    for pid in $(pgrep xmobar); do grep -z ^LANG /proc/"$pid"/environ; done | xargs -0 -n1

say?

Does it work if you `{ echo ěščř; sleep 5; } | xmobar` manually in a terminal?

If the first one looks okay and the second one works, then you're sending the wrong input into xmobar (probably a misconfigured xmonad or something?). If the first one is wrong, then your `locale.conf` isn't in effect when launching xmobar.

**Comment by Linusero** [comment]
First one returns
```
LANG=es_ES.UTF-8
LANG=es_ES.UTF-8
```
and the second command works without problem, so I guess it has to do with how I handle the input to xmobar in the xmonad.hs. Thanks, at least now I know where to look to fix it.

**Comment by liskin** [comment]
This might of interest then: https://github.com/xmonad/xmonad-contrib/pull/471

**Comment by Linusero** [comment]
I think I know what was causing the problem, I was cutting long titles, so they fit better in less space. I think that the reason some titles crash xmobar is that I cut Unicode characters in half. It was a very dull mistake, but I wanted you to know in case someone encounters the same problem. Thank you very much for all the aid.

**Comment by jaor** [comment]
@Rxaon did @liskin's suggestion help? can we close this issue? thanks

**Comment by Rxaon** [comment]
I managed to make it work. I don't remember now what was the problem in my configuration, but it has not given me any error since then. So yes, you can close the issue. Thanks.

**Comment by jaor** [comment]
thanks for the quick reply!
