### ISSUE TITLE
MPD issues

### ISSUE THREAD

**Issue by UnspankableGoose** [jaor/xmobar#525]
Maybe this is an error with my config, but for some reason mpd just refuses to work. 
It's constantly giving me this error: 
![image](https://user-images.githubusercontent.com/41350325/107157580-69e45480-694a-11eb-9f31-d943bf8985fb.png)
Here is my config:
Config { 

   -- appearance
     font =         "xft:Hack:size=11:Bold:antialias=true,Hack Nerd Font:size=12:Bold:antialias=true"
   , bgColor =      "#282a36"
   , fgColor =      "#f8f8f2"
   , alpha  =       255
   , position =     Static { xpos = 10 , ypos = 4, width = 1900, height = 20}
   , border =       NoBorder
   , borderColor =  "#373b41"

   -- layout
   , sepChar =  "%"   -- delineator between plugin names and straight text
   , alignSep = "}{"  -- separator between left-right alignment
   , template = "<action=~/.config/xmenu/xmenu.sh><fc=#57c7ff>  </fc></action> %StdinReader%}{<fc=#ff8c00>%mpd%</fc> | <fc=#ff6ac1>%cpu%</fc> | <fc=#f1fa8c>%memory%</fc> | <fc=#57c7ff>%internet%</fc> | <fc=#fc3424>%volume%</fc> | <fc=#57c7ff>%clock% </fc>" 
   --   | <fc=#57c7ff>%internet%</fc> | <fc=#fc3424> %volume%</fc> |             <fc=#57c7ff>%clock% </fc>

   -- general behavior
   , lowerOnStart =     False    -- send to bottom of window stack on start
   , hideOnStart =      False   -- start with window unmapped (hidden)
   , allDesktops =      True    -- show on all desktops
   , overrideRedirect = False    -- set the Override Redirect flag (Xlib)
   , pickBroadest =     False   -- choose widest display (multi-monitor)
   , persistent =       True    -- enable/disable hiding (True = disabled),
   , iconRoot = ".config/xmobar/xpm-status-icons/icons/"

   -- plugins
   , commands = [
       --cpu 
       Run Com "/home/goose/.config/xmobar/scripts/cpu" [] "cpu" 10,

       --memory
       Run Com "/home/goose/.config/xmobar/scripts/memory" [] "memory" 10,

       --internet
       Run Com "/home/goose/.config/xmobar/scripts/internet" [] "internet" 10,

       --volume
       Run Com "/home/goose/.config/xmobar/scripts/volume" [] "volume" 1,

       --clock
       Run Com "/home/goose/.config/xmobar/scripts/clock" [] "clock" 10,

       --mpd
       --Run MPD ["-t", "<state>: <artist>  <track> <elapsed>/<length>"] "mpd" 10,

       --stdinreader
       Run StdinReader
        	]
   }

**Comment by jaor** [comment]
as show in the doc/plugins.org, the correct invocation of mpd does not
include any alias name.  try:

  Run MPD ["-t", "<state>: <artist>  <track> <lapsed>/<length>"] 10,

(without leading --, of course).  please do cheh the name of the
variables too, i think it's lapsed, not elapsed.

**Comment by UnspankableGoose** [comment]
I've removed the alias name, but it still doesn't work.

**Comment by UnspankableGoose** [comment]
I've also temporarily removed the lapsed/length

**Comment by UnspankableGoose** [comment]
Oops, I did a dumb and forgot to uncomment the line. Now, it's stuck on <Waiting...>
![image](https://user-images.githubusercontent.com/41350325/107165553-e0984680-6978-11eb-979f-50d45b3029c7.png)

**Comment by UnspankableGoose** [comment]
I can confirm a track is playing.

**Comment by UnspankableGoose** [comment]
Run MPD ["-t", "<state>: <artist> - <track> <lapsed>/<length>"] 10
Here is the line.

**Comment by jaor** [comment]
On Sun, Feb 07 2021, Goose wrote:

> Run MPD ["-t", ": - /"] 10
> Here is the line.
you have no variable to show.

**Comment by UnspankableGoose** [comment]
Github is being weird

**Comment by UnspankableGoose** [comment]
Run MPD ["-t", "<state>: <artist> - <track>", "-p", "no port for u", "-h", "no host for u"] 10

**Comment by UnspankableGoose** [comment]
yeah github is really being weird

**Comment by UnspankableGoose** [comment]
Run MPD ["-t", "state: artist - track", "-p", "t", "-h", "t"] 10

**Comment by UnspankableGoose** [comment]
I have put \<\> around state, artist and track

**Comment by UnspankableGoose** [comment]
Oh, and also, when I upgrade to the git version
I'm apparently missing the libHSlibmpd-0.9.3.0-I4wAXtbhNaKLuEA31xaLJ-ghc8.10.3.so lib, even though I have haskell-libmpd installed from the aur.

**Comment by UnspankableGoose** [comment]
I've sort of fixed it by writing a python script.

**Comment by Infinisil** [comment]
I had the same problem with the `<Waiting...>` appearing. I just figured out the problem: libmpd was only trying to connect to the IPv6 localhost address `::1`, which isn't configured on my machine:

```
$ mpc --host=::1
MPD error: Connection refused
```

To fix it, I had to explicitly specify the IPv4 localhost address, `127.0.0.1` instead in the arguments. Here's my xmobar command now:
```
Run MPD
  [ "-t", "<artist> — <title> <statei>", "--"
  , "-P", ">>", "-Z", "||"
  , "--host", "127.0.0.1"
  ] 10
```

**Comment by jaor** [comment]
closing, since a fix was found. thanks!
