### ISSUE TITLE
compiled binary file in dataDir instead of configDir.

### ISSUE THREAD

**Issue by lycuid** [jaor/xmobar#526]
https://github.com/jaor/xmobar/blob/407866c433735e510b6bde2d06e2a18cff22c470/src/Xmobar/App/Compile.hs#L136

Can the above line of code be updated (without causing inconvenience to users) to place the compiled binary in data directory by default.
It doesn't make much sense to place it alongside the configurations.

**Comment by slotThe** [comment]
On Mon, Feb 08 2021 06:38, Abhishek Kadam wrote:
> https://github.com/jaor/xmobar/blob/407866c433735e510b6bde2d06e2a18cff22c470/src/Xmobar/App/Compile.hs#L136
>
> Can the above line of code be updated (without causing inconvenience
> to users) to place the compiled binary in data directory by default.
> It doesn't make much sense to place it alongside the configurations.

The `recompile' function seems to be a lightweight version of the one
xmonad uses [1], which does indeed put the binary into the data
directory; not sure why this was changed for xmobar.

Personally, I don't see a reason not to put it into that directory;
@jaor what do you think?

[1] https://github.com/xmonad/xmonad/blob/master/src/XMonad/Core.hs#L565

**Comment by jaor** [comment]
On Mon, Feb 08 2021, Abhishek Kadam wrote:

> https://github.com/jaor/xmobar/blob/407866c433735e510b6bde2d06e2a18cff22c470/src/Xmobar/App/Compile.hs#L136
>
> Can the above line of code be updated (without causing inconvenience
> to users) to place the compiled binary in data directory by default.

hmmm, no, probably not.  moving the binary is going to put it ouside
people's path and break their workflow.  also, the data path is
optional, it does not need to be present.

> It doesn't make much sense to place it alongside the configurations.

it doesn't make sense either in a data directory :) we're following here
xmonad's convention, so i think it's fine.  moreover, when you write a
xmobar program, it's not a "configuration", it's a program, so putting
the executable in the same directory as the source is quite natural.

**Comment by liskin** [comment]
> it doesn't make sense either in a data directory

I said it in context of xmonad and I'll repeat it here as well: indeed, putting it in the data directory is something we do for backward compatibility. If would probably make sense to put it in xdg cache dir, as it can be recreated from the source, but neither data nor config make much sense.

**Comment by jaor** [comment]
On Mon, Feb 08 2021, slotThe wrote:

> On Mon, Feb 08 2021 06:38, Abhishek Kadam wrote:
>> https://github.com/jaor/xmobar/blob/407866c433735e510b6bde2d06e2a18cff22c470/src/Xmobar/App/Compile.hs#L136
>>
>> Can the above line of code be updated (without causing inconvenience
>> to users) to place the compiled binary in data directory by default.
>> It doesn't make much sense to place it alongside the configurations.
>
> The `recompile' function seems to be a lightweight version of the one
> xmonad uses [1], which does indeed put the binary into the data
> directory; not sure why this was changed for xmobar.
>
> Personally, I don't see a reason not to put it into that directory;
> @jaor what do you think?
>
> [1] https://github.com/xmonad/xmonad/blob/master/src/XMonad/Core.hs#L565

i don't understand why it should go in the data directory, i thought it
was the other way around?  isn't data optional?

**Comment by lycuid** [comment]
I guess it's not a big deal, I, personally, am using the `build` script to manipulate the binary file path (which feels kinda hack-y).
I think this can be closed for now, as there is this workaround with this build script.
but it would be nice to have the binary, out of the configs directory by default, as it normally would be under version control.
Or have some way to manipulate the binary file path.

**Comment by jaor** [comment]
On Thu, Feb 11 2021, Abhishek Kadam wrote:

> Or have some way to manipulate the binary file path.

it's not as convenient, but what i usually do is manage my xmobar(s)
using a cabal project and the use cabal install, which puts things in
reasonable places (same thing works for stack), and i can then also
easily use a master branch checkout.

https://gitlab.com/jaor/xmobar-config

(but then, again, it's faster to just tweak xmobar.hs and re-launch the
thing, as if it were in fact a config).
