### ISSUE TITLE
Doc example link broken

### ISSUE THREAD

**Issue by AtifChy** [jaor/xmobar#527]
https://github.com/jaor/xmobar/blob/master/doc/examples/padding-icon.sh

**Comment by slotThe** [comment]
On Wed, Feb 24 2021 20:35, Haise wrote:

> https://github.com/jaor/xmobar/blob/master/doc/examples/padding-icon.sh

Nicely spotted, it should point to 

    https://github.com/jaor/xmobar/blob/master/examples/padding-icon.sh

instead.  Pr's welcome!

**Comment by jaor** [comment]
i'll fix it...
