### ISSUE TITLE
Bengali font not rendering properly 

### ISSUE THREAD

**Issue by AtifChy** [jaor/xmobar#529]
this is how it looks:
![16-03-2021_12-37](https://user-images.githubusercontent.com/42291930/111266153-523c7200-8654-11eb-8bda-13eacf2e162d.png)
this is how it supposed to look:
![16-03-2021_12-31](https://user-images.githubusercontent.com/42291930/111266200-62ece800-8654-11eb-8e66-01160be06e49.png)

font name: Noto Sans Bengali

**Comment by tlonic** [comment]
see https://github.com/jaor/xmobar/issues/389

**Comment by jaor** [comment]
moved to https://codeberg.org/jao/xmobar/issues/529
