### ISSUE TITLE
Full width next to vertical display

### ISSUE THREAD

**Issue by capitanu** [jaor/xmobar#530]
Take the example of a two monitor setup: left is horizontal and right is vertical.

If the xmobar on the left has full monitor width (1920 px), the vertical display on the right will only show all the applications in the lower half of the display. If I set the width of the left xmobar to 1919, everything works as expected.

**Comment by liskin** [comment]
That looks like a bug in your window manager rather than xmobar. I vaguely remember fiddling with something related in xmonad around 2009/2010, but I've never had a problem since. What WM are you using?

**Comment by capitanu** [comment]
Sorry for the late reply! I did not notice your reply.

I am using xmonad! Do you remember what fixed it for you? It's not a huge problem, but would be nice to fix!

**Comment by liskin** [comment]
Yeah, I do remember: https://github.com/xmonad/xmonad-contrib/commit/82a0d30f31135dfd884fff6afa5f7ca989352382, but it's almost certainly just "vaguely related", there's no way this will help you.

Your problem sounds more like an issue with a border or something. Can you perhaps show what `xrandr --verbose` shows and what `xwininfo` shows when you point it at xmobar?

**Comment by liskin** [comment]
Were you by any chance using `xmobar` with Static positioning instead of `-x`? Does https://github.com/jaor/xmobar/pull/538 fix your issue?
