### ISSUE TITLE
Xmobar - Ram module shows higher usage than it is.

### ISSUE THREAD

**Issue by apoorv569** [jaor/xmobar#532]
Here is a screenshot of `htop` and the `xmobar` ram module at the same time,
![2021-03-19_16-58](https://user-images.githubusercontent.com/53279454/111773968-d7ce5500-88d4-11eb-8634-f76f621246eb.png)

`xmobar` always shows higher ram usage than `htop`.

**Comment by jaor** [comment]
xmobar reads memory usage statistics from /proc/meminfo: can you check
with `cat /proc/meminfo` and confirm that it is in fact not reporting
what you see there?  there are many ways of putting together those
numbers, and perhaps htop is simply counting differently.

**Comment by apoorv569** [comment]
> xmobar reads memory usage statistics from /proc/meminfo: can you check with `cat /proc/meminfo` and confirm that it is in fact not reporting what you see there? there are many ways of putting together those numbers, and perhaps htop is simply counting differently.

Here is the screenshot for `htop` reporting `1.95G`, `cat /proc/meminfo` and the bar reporting `2376Mb`.
![2021-03-20_22-38](https://user-images.githubusercontent.com/53279454/111878222-4ee71480-89cd-11eb-9e55-954b49beca48.png)

**Comment by jaor** [comment]
what would your xmobar config be? if we are consistent with /proc/meminfo, this is an htop problem...

**Comment by apoorv569** [comment]
> what would your xmobar config be? if we are consistent with /proc/meminfo, this is an htop problem...

Here is a screenshot from my PC, showing `htop`, `free -h` and `cat /proc/meminfo`.
![2021-03-20_23-14](https://user-images.githubusercontent.com/53279454/111880567-4218ef80-89d2-11eb-9a16-100c12588a8d.png)

I don't which is the right value and which is wrong, but `xmobar`'s value does not matches any of it.

**Comment by slotThe** [comment]
On Sat, Mar 20 2021 10:47, apoorv569 wrote:
> I don't which is the right value and which is wrong, but `xmobar`'s
> value does not matches any of it.

Xmobar's value sounds relatively close to `/proc/meminfo'; could be that
it has simply changed since the bar was last updated?

**Comment by AtifChy** [comment]
@apoorv569 xmobar is correct. you can check it by using a GUI system monitor app.

**Comment by apoorv569** [comment]
> @apoorv569 xmobar is correct. you can check it by using a GUI system monitor app.

I see, I have `KDE` installed so I opened its system monitor application to verify,
![2021-03-21_01-22](https://user-images.githubusercontent.com/53279454/111883885-025b0380-89e4-11eb-9404-be1e8503e269.png)

There is a `100Mb` difference, but I think `xmobar` is showing correct. Thank you for mentioning this.
