### ISSUE TITLE
Date plugin does not catch changes due to daylight saving

### ISSUE THREAD

**Issue by felixSchl** [jaor/xmobar#534]
Daylight saving ended here in NZ on Sunday, 4th of April but the time displayed by xmobar did not reflect this change until I restarted it. It's a very low impact bug and probably hard to recreate, but I figured it's probably a good idea to track it in a Github issue anyway.

This is the relevant part of my .xmobarrc:

```
      , Run Date "%a %b %_d %Y %H:%M:%S" "date" 10
```

**Comment by liskin** [comment]
What version of xmobar do you have? I think we fixed this issue in https://github.com/jaor/xmobar/releases/tag/0.37

**Comment by felixSchl** [comment]
Oh right! I am still on 0.36. I must have missed that release. I was looking for the bug on the master branch and thought it looked right :)
