### ISSUE TITLE
Volume template is inaccurate

### ISSUE THREAD

**Issue by Mirocif** [jaor/xmobar#536]
Like another report I have seen for the volume, the template for the ram scores 200M or more than what is actually used.

![ada](https://user-images.githubusercontent.com/48184639/114925772-cfaff980-9e2f-11eb-863f-12ba551a9742.png)

**Comment by jaor** [comment]
we've been through this in #532 ... this is either a problem in htop, or a normal delay induced by the frequency of the polling.  please feel free to comment further in that thread, thanks!
