### ISSUE TITLE
Error Using Custom Com: Could not execute command

### ISSUE THREAD

**Issue by harsh-a1** [jaor/xmobar#542]
I am trying to run a script to show some output in the bar. The script runs fine in the shell but not when xmobar runs it . I am not able to figure out why. What gets displayed on xmobar is "Could not execute command /xyz/test.sh"

This is the script basically : 
```
curl -s URL > file1 ;
diff -q file1 file2
```
What am I doing wrong? Any help is appreciated.

Thanks

**Comment by jaor** [comment]
From the looks of the error, you might be using a wrong path for the script in
your Com... is you test.sh really in the root directory /xyz? is it
executable? also probably you want a #!/bin/bash as its first line (i
forgot if that's necessary, and cannot check right now).

**Comment by harsh-a1** [comment]
Yes it was a problem with my script. Thnx
