### ISSUE TITLE
xmobar Hidden pp indicator

### ISSUE THREAD

**Issue by dhaval9911** [jaor/xmobar#546]
i dont know how to achieve this but i want to change the indicator for workspaces that have windows but not focused.....i want to have underline on that workspace names ....can i do it somehow?

**Comment by AtifChy** [comment]
u can use ``xmobarBorder`` for that. [example](https://github.com/xmonad/xmonad/blob/master/TUTORIAL.md#changing-what-xmonad-sends-to-xmobar) 
[module](https://github.com/xmonad/xmonad-contrib/blob/master/XMonad/Hooks/StatusBar/PP.hs)

**Comment by jaor** [comment]
closing, since a solution was provided.  please feel free to comment/reopen if needed.
