### ISSUE TITLE
Can't get NotmuchMail Runnable to parse in xmobarrc

### ISSUE THREAD

**Issue by mbwgh** [jaor/xmobar#547]
I am trying to set up the new `NotmuchMail` plugin, however I must either be including a syntax error or something else is amiss.

My xmobarrc looks like this:
```
Config { 

   -- appearance
     font =         "xft:Bitstream Vera Sans Mono:size=7:bold:antialias=true"
   , bgColor =      "black"
   , fgColor =      "#646464"
   , position =     Static { xpos = 0, ypos = 16, width = 1920, height = 16 }
   , border =       BottomB
   , borderColor =  "#646464"

   -- layout
   , sepChar =  "%"   -- delineator between plugin names and straight text
   , alignSep = "}{"  -- separator between left-right alignment
   , template = "}{ %battery% | %memory% | %multicpu%"

   -- general behavior
   , lowerOnStart =     True    -- send to bottom of window stack on start
   , hideOnStart =      False   -- start with window unmapped (hidden)
   , allDesktops =      True    -- show on all desktops
   , overrideRedirect = True    -- set the Override Redirect flag (Xlib)
   , pickBroadest =     False   -- choose widest display (multi-monitor)
   , persistent =       True    -- enable/disable hiding (True = disabled)

   -- plugins
   --   Numbers can be automatically colored according to their value. xmobar
   --   decides color based on a three-tier/two-cutoff system, controlled by
   --   command options:
   --     --Low sets the low cutoff
   --     --High sets the high cutoff
   --
   --     --low sets the color below --Low cutoff
   --     --normal sets the color between --Low and --High cutoffs
   --     --High sets the color above --High cutoff
   --
   --   The --template option controls how the plugin is displayed. Text
   --   color can be set by enclosing in <fc></fc> tags. For more details
   --   see http://projects.haskell.org/xmobar/#system-monitor-plugins.
   , commands = 

        -- network activity monitor (dynamic interface resolution)
        [ Run DynNetwork     [ "--template" , "<dev>: <tx>kB/s|<rx>kB/s"
                             , "--Low"      , "1000"       -- units: B/s
                             , "--High"     , "5000"       -- units: B/s
                             , "--low"      , "darkgreen"
                             , "--normal"   , "darkorange"
                             , "--high"     , "darkred"
                             ] 10

        -- cpu activity monitor
        , Run MultiCpu       [ "--template" , "Cpu: <autototal>%"
                             , "--Low"      , "50"         -- units: %
                             , "--High"     , "85"         -- units: %
                             , "--low"      , "darkgreen"
                             , "--normal"   , "darkorange"
                             , "--high"     , "darkred"
                             , "--ppad"     , "2"
                             ] 10

        -- memory usage monitor
        , Run Memory         [ "--template" ,"Mem: <usedratio>%"
                             , "--Low"      , "20"        -- units: %
                             , "--High"     , "90"        -- units: %
                             , "--low"      , "darkgreen"
                             , "--normal"   , "darkorange"
                             , "--high"     , "darkred"
                             ] 10

        -- battery monitor
        , Run Battery        [ "--template" , "Batt: <acstatus>"
                             , "--Low"      , "10"        -- units: %
                             , "--High"     , "80"        -- units: %
                             , "--low"      , "darkred"
                             , "--normal"   , "darkorange"
                             , "--high"     , "darkgreen"

                             , "--" -- battery specific options
                                       -- discharging status
                                       , "-o"	, "<left>% (<timeleft>)"
                                       -- AC "on" status
                                       , "-O"	, "Charging (<left>%)"
                                       -- charged status
                                       , "-i"	, "Charged"
                             ] 50

        , Run NotmuchMail "mail" [MailItem "unread" "" ""] 3000

        ]
   }

```

However this fails with
```
Invalid configuration file: "Config" (line 88, column 5):
error reading the commands: this usually means that a command could not
be parsed.
The error could be located at the begining of the command
which follows the offending one. field: [ Run DynNetwork     [ "--template" , "<dev>: <tx>kB/s|<rx>kB/s"
[... the rest of the rcfile]
```
where line 88 is the closing `}`.

The `NotmuchMail` plugin should be available even without the `all_extensions` flag, at least according to the cabal file.

One thing I noticed however, is that the type constructor is not in [this list](https://github.com/jaor/xmobar/blob/82461417abbcd2e03e4329d68df4a15866885dd2/src/Xmobar/Run/Types.hs#L55), could that have something to do with it?

**Comment by slotThe** [comment]
Whoops, you are totally right.  I use a Haskell-based configuration and hence didn't really test the plugin for a non-Haskell based one (I figured that deriving `Read` and `Show` was enough).

I opened #548, which should fix this.  @mbwgh would you care to test?

**Comment by mbwgh** [comment]
> Whoops, you are totally right. I use a Haskell-based configuration and hence didn't really test the plugin for a non-Haskell based one (I figured that deriving `Read` and `Show` was enough).
> 
> I opened #548, which should fix this. @mbwgh would you care to test?

Argh! I actually more or less converged on the same changeset as you did, like 5 minutes ago.

I'll gladly give your version a spin however :D

**Comment by mbwgh** [comment]
Okay, I have tried it out and it appears to work now. Personally, I think you can just omit the manual `Read` instance since you only use the record accessors inside the module where you define them, so you could just as well define
```haskell
data NotmuchMail = NotmuchMail String [MailItem] Int deriving (Read, Show)
```

and so on, and *maybe* expose manually defined accessor functions with the previous name for compatibility. But I'm just saying that because I find readPrec and manually specifying precedences scary :)

**Comment by slotThe** [comment]
On Mon, May 24 2021 06:12, Maximilian Winkler wrote:
> Personally, I think you can just omit the manual `Read` instance since
> you only use the record accessors inside the module where you define
> them, so you could just as well define
> ```haskell
> data NotmuchMail = NotmuchMail String [MailItem] Int deriving (Read, Show)
> ```
>
> and so on, and *maybe* expose manually defined accessor functions with
> the previous name for compatibility. But I'm just saying that because
> I find readPrec and manually specifying precedences scary :)

I have to say I quite evalue the clarity that the record accessors
bring.  The precedences are just copied from the respective derived
instances, so they are _probably_ correct :)

**Comment by mbwgh** [comment]
> I have to say I quite evalue the clarity that the record accessors bring. The precedences are just copied from the respective derived instances, so they are _probably_ correct :)

I think you are right, and if it works that's the important thing anyway. Thanks!
