### ISSUE TITLE
.xmobarrc: hGetContents: invalid argument (invalid byte sequence) [with ° symbol]

### ISSUE THREAD

**Issue by jrgiacone** [jaor/xmobar#549]
Good Afternoon,

I am currently experimenting with the git versions of xmobar, xmonad, and xmonad-contrib through stack. I am using static-stack from the aur to compile xmobar, xmonad, and xmonad-contrib. It appears there was a bug with alsa and gcc 11.1 so I am using every flag except for alsa in the stack.yml file. This is also while trying to run through virtualbox, I'm not sure if that is maybe causing the issue.

Onto the issue. When trying to display the degrees ° unicode character I get the error noted in the title. I have checked my local.conf and it reads LANG=en_US.UTF-8 and running localectl list-locales confirms this. 

The error pops up when I am trying to run xmobar from the terminal. It does not launch with xmonad either.
![2021-05-27-180414_1987x510_scrot](https://user-images.githubusercontent.com/71910145/119914814-f9237100-bf15-11eb-9893-7493a53b44f6.png)

Any ideas?

**Comment by jaor** [comment]
perhaps try "\x0b" (i think that's the unicode code) in the config file?

**Comment by jrgiacone** [comment]
> perhaps try "\x0b" (i think that's the unicode code) in the config file?

It launches, but shows a box although I have the font installed... hm...

**Comment by jaor** [comment]
On Thu, May 27 2021, jrgiacone wrote:

>     perhaps try "\x0b" (i think that's the unicode code) in the config file?
>
> It launches, but shows a box although I have the font installed... hm...

sorry, i think it's \xb0

**Comment by jrgiacone** [comment]
> On Thu, May 27 2021, jrgiacone wrote: perhaps try "\x0b" (i think that's the unicode code) in the config file? It launches, but shows a box although I have the font installed... hm...
> sorry, i think it's \xb0

That works perfectly thank you, I wonder what is causing the problem with the normal symbol! I really appreciate it!

**Comment by liskin** [comment]
> I have checked my local.conf and it reads LANG=en_US.UTF-8 and running localectl list-locales confirms this.

What's in local.conf doesn't really matter. What matters is what's in your current environment. Can you tell us what `env | grep -e LANG -e LC_` shows?

Can you also try the following commands?

```
$ LC_ALL=en_US.UTF-8 ghc -e 'print "°C"'
$ LC_ALL=C.UTF-8 ghc -e 'print "°C"'
$ LC_ALL=C ghc -e 'print "°C"'
$ ghc -e 'print "°C"'
```

(I know your problem is solved but I'd really like to understand what's going on because inevitably someone else will encounter this later.)

**Comment by liskin** [comment]
Just a note for anyone interested in how this ends:

@jrgiacone found another issue related to xmobar/xmonad and I thought it'd be easier to just send me the virtual machine so that I can look right into both issues. Turns out the trouble was that `local.conf` should've been `locale.conf` and the X session did run with `LANG=C`. :-)

**Comment by jaor** [comment]
On Fri, May 28 2021, Tomáš Janoušek wrote:

> Just a note for anyone interested in how this ends:
>
> @jrgiacone found another issue related to xmobar/xmonad and I thought
> it'd be easier to just send me the virtual machine so that I can look
> right into both issues. Turns out the trouble was that local.conf
> should've been locale.conf and the X session did run with LANG=C. :-)

ah! :) that's good to know, thanks for following up.
