### ISSUE TITLE
Xmobar Command isn't working

### ISSUE THREAD

**Issue by d4hines** [jaor/xmobar#563]
I have a script I run with `Run Com ...` as in the documentation.  It just displayed "Updating...". It stopped working since I updated from 0.38 to 0.39. Here's my config on the exact line that isn't working: https://github.com/d4hines/beth/blob/master/flake.nix#L279

The script calls a web API and processes the output - it needs to update fairly close to real time.

Any ideas or workarounds?

**Comment by manojuppala** [comment]
i am having the same issue.

**Comment by jaor** [comment]
hi, and sorry for the late reply.  i can see nothing in 0.39 that could affect Com.  unfortunately, i don't speak nix and i don't really understand what exactly is the command being executed in that link @d4hines gives.  is this something reproducible with a vanilla xmobar configuration? thanks!

**Comment by d4hines** [comment]
Hi @jaor. Sorry, I should have given you an immutable link. Here's my config: https://github.com/d4hines/beth/blob/e52859021439b88d141e1e42b25ff81dfefc364d/modules/home/xmobar.nix#L6-L24

For convenience, I'll post it here as a vanilla config:
```
  Config {
    font = "xft:${font}:size=14:antialias=true:hinting=true:bold,Noto Color Emoji:size=14:antialias=true:hinting=true",
    bgColor = "#21252B",
    fgColor = "#abb2bf",
    position = BottomSize C 100 24,
    sepChar = "%", -- delineator between plugin names and straight text
    alignSep = "}{", -- separator between left-right alignment
    template = " %cpu% | %memory% } %complice% { %date% | %time_norfolk% Norfolk | %time_paris% Paris | %time_india% Calcutta",
    commands =
       [ Run Date "%a, %d %b %Y" "date" 10
        ,Run Cpu ["-L", "3", "-H", "50", "--normal", "green", "--high", "red"] 10
        ,Run Memory ["-t", "Mem: <usedratio>%"] 10
        ,Run Com "curl" ["http://localhost:7000/status"] "complice" 10
        ,Run DateZone "%I:%M %p" "en_US.UTF-8" "America/New_York" "time_norfolk" 10
        ,Run DateZone "%I:%M %p" "en_US.UTF-8" "Europe/Paris" "time_paris" 10
        ,Run DateZone "%I:%M %p" "en_US.UTF-8" "Asia/Calcutta" "time_india" 10
      ]
  }
  ```
  
  I'm not sure how reproducible the issue is.

**Comment by d4hines** [comment]
Actually, I just checked and it appears I'm running version 0.40 now, and I'm not having any issues. :man_shrugging: You can close this issue as far as I'm concerned.

**Comment by jaor** [comment]
excellent.  thanks for checking!
