### ISSUE TITLE
Alsa plugin fails to update when switching default sink

### ISSUE THREAD

**Issue by caseyavila** [jaor/xmobar#566]
I really like the event-based refreshing for the `Alsa` plugin, but it unfortunately stops receiving updates when the default sink changes. If the default audio device is changed, the plugin still reports the volume of the "default" sink when xmobar was started.

It's not really the fault of xmobar itself, `alsactl monitor default` simply stops reporting volume changes when the default audio device is changed, e.g., when a bluetooth headset connects and PulseAudio (or PipeWire) switches to that device for playback. It also happens when you manually control defaults in a program like pavucontrol.

The traditional `Volume` plugin supports when the default audio device is changed, but obviously doesn't support event-based refreshing.

Would it be possible to get it where the Alsa plugin is always receiving events (even if the default device changes?). I am aware of `pactl subscribe`, and it seems to not suffer from the same issue as `alactl monitor default`, but I suppose that would require PulseAudio on top of Alsa. Perhaps a separate plugin?

**Comment by caseyavila** [comment]
Messed about in the source code, and looks like using `pactl subscribe` solves the issue :)

**Comment by jsoo1** [comment]
@caseyavila Do you happen to have a patch that can be used to try this out?

**Comment by caseyavila** [comment]
This is super weird, but I stopped having the issue after noticing it for more than a year... I did switch to PipeWire so maybe 0.3.37 fixed it. Regardless, I still think this is a bug. Here's the hack that seemed to do the trick for me. It will obviously need some work before it's ready to be merged.

[pactl-subscribe.diff.txt](https://github.com/jaor/xmobar/files/7249599/pactl-subscribe.diff.txt)

**Comment by jsoo1** [comment]
i can confirm this fixes my problem, also. not sure what the bug is either...

**Comment by caseyavila** [comment]
Well the bug is that `alsactl monitor default` only monitors the default sink when the command was first launched and doesn't report events if the default sink is changed (though this might be unavoidable/intentional by Alsa developers). `pactl subscribe` still reports volume changes however.

**Comment by yusi1** [comment]
BTW after applying this patch on my setup I get really high CPU usage from XMobar (around 20%, before it was below 2% CPU usage)..

**Comment by yusi1** [comment]
Before XMobar was using refresh based monitoring, but after this patch it's more like a volume daemon which takes up CPU usage passively.. (which is what `pactl subscribe` does) Maybe there could be a way to only use CPU usage when the default volume device has changed?

**Comment by yusi1** [comment]
A temp hack would be to setup a keybind to restart XMobar whenever you change the default audio device to something else..

**Comment by yusi1** [comment]
Maybe the Alsa devs are the ones that have to fix this

**Comment by jaor** [comment]
i've had several issues with this monitor, like zombie processes left around for instance, and returned to using the polling one a long time ago, so i'm not really sure what'd be the right thing to do here.  causing spikes of 20% CPU usage sounds like a no-go to me: @caseyavila are you also experiencing it? an option would be to make the alsactl/pactl alternative a configuration parameter... or just use polling :)

**Comment by caseyavila** [comment]
Yes, I am experiencing the zombie processes. Should I submit a pull request for the pactl monitor? Polling is fine, but I like how an event-based system changes instantly on the bar.

**Comment by jaor** [comment]
On Tue, Mar 01 2022, Casey Avila wrote:

> Yes, I am experiencing the zombie processes. Should I submit a pull
> request for the pactl monitor?

yes, by all means, thanks!

**Comment by jaor** [comment]
moved to https://codeberg.org/jao/xmobar/issues/566
