### ISSUE TITLE
HandleReader only ever says `Updating...`

### ISSUE THREAD

**Issue by guygastineau** [jaor/xmobar#567]
https://github.com/jaor/xmobar/blob/3a5004e39e6dc42f2691012b4513a210202311b2/src/Xmobar/Plugins/HandleReader.hs#L43

**Comment by liskin** [comment]
Possibly a locale/encoding issue? HandleReader lacks exception handling, so I'm not sure if it'd print the exception anywhere, but probably worth checking the stderr anyway.

**Comment by guygastineau** [comment]
I will post some of my config below.  Is anyone else using this?  I am trying to move toward completely embedding xmobar in my xmonad builds.  This is the last obstacle.

I initially tried it exactly as shown in the haddock example, but I couldn't get the posix processes to terminate, so I switched to `forkIO`.  The behavior of the `HandleReader` is the same both ways (but `forkIO` seems the safer way to do it).

Here is what I export from my `Top.hs` config file for a top bar.

``` haskell
runTop :: IO (ThreadId, Handle)
runTop = do
  (r, w) <- createPipe
  bar <- forkIO $ xmobar conf
    { commands = Run (HandleReader r "XMonadLog") : commands conf }
  return (bar, w)
```

I use it from my xmonad config like this:

``` haskell

main :: IO ()
main = do
  (_, logHandle) <- runTop
  run $ conf logHandle
  where
    run :: (LayoutClass l Window, Read (l Window)) => XConfig l -> IO ()
    run = xmonad . ewmh . myAdditionalKeys

    conf topBar = def
      { modMask  = mod4Mask
      , terminal = myTerminal

      -- style and color
      , borderWidth        = myBorderWidth
      , normalBorderColor  = myNormalBorderColor
      , focusedBorderColor = myFocusedBorderColor

      -- hooks
      , logHook         = myLogHook topBar
      , manageHook      = manageDocks <+> manageHook def
      , layoutHook      = avoidStruts myLayoutHook
      , handleEventHook = myHandleEventHook
      -- startup
      , startupHook     = setWMName "LG3D"
      }
```

The `myLogHook` just wraps the default and uses the pretty printing logger.

**Comment by guygastineau** [comment]
@liskin Thank you for the suggestion.  I thought this could be an issue.  I didn't get anything in `~/.xmonad/xmonad.errors`  I will check my TTY too.

**Comment by jsoo1** [comment]
Funny enough, I just found the same thing.

**Comment by liskin** [comment]
Hm, there might be other issues when running it like this. One is that you'll need to use the threaded RTS for this to work, as xmonad uses blocking calls to Xlib. Another is that you better call [initThreads](https://xmonad.github.io/xmonad-docs/X11-1.10.1/Graphics-X11-Xlib-Misc.html#v:initThreads) as the first thing in case xmonad's thread runs before xmobar's. Not sure if any of these two might result in there being `Updating...`, though. Anyway, the pipe from `createPipe` doesn't have any text encoding, so printing anything besides 7bit ascii will likely fail.

**Comment by liskin** [comment]
(Oh and just to clarify, I've never run it like this. I run xmobars via https://xmonad.github.io/xmonad-docs/xmonad-contrib-0.16.999/XMonad-Hooks-StatusBar.html and use X props to pass data to them.)

**Comment by jsoo1** [comment]
hm. i don't think i am printing anything outside of ascii range, but i will try rts and initThreads

**Comment by guygastineau** [comment]
Interesting.  I am definitely printing out of ascii range, but not at the beginning.  I am using the threaded RTS.  I turned it off temporarily when using `System.Posix.Process.forkProcess` as the `unix` package docs recommend this.  I turned the multiprocessor threaded runtime back on for `forkIO` though, and I am not experiencing any blocking running `xmobar` inside `xmonad` like this.

I will try out `initThreads`, I was thinking if xmonad tries writing to the pipe first it will probably fail, so this is exactly the kind of thing I hoped to learn here.  Really, I would prefer a socket reader, maybe I need to write a plugin.

**Comment by liskin** [comment]
Well if you're running both in the same process, a socket reader is not really going to be that much of an improvement over pipes. A plugin that uses https://hackage.haskell.org/package/stm-2.5.0.1/docs/Control-Concurrent-STM-TVar.html for communication would be a much more sensible choice here. That is, if you want to play with this and learn something.

If you just want something that works, use https://github.com/jaor/xmobar/blob/master/src/Xmobar/Plugins/XMonadLog.hs and https://xmonad.github.io/xmonad-docs/xmonad-contrib-0.16.999/XMonad-Hooks-StatusBar.html#v:xmonadPropLog-39-

**Comment by guygastineau** [comment]
Hmm, well `initThreads` is in `xmobar` which I call in IO before running `xmonad`, so I don't think that is the issue.

**Comment by guygastineau** [comment]
Cool.  Well, I just meant that sockets have a better API surface and behavior/synchronization.  I was looking at `Control.Concurrent` earlier, and I wondered if I should just mess with shared memory.  Thanks for the suggestion!

Last week I wanted to add `Dhall` as a config language option for `xmobar`, but then I discovered that I could just write the configs in Haskell, so I don't know if dhall is worth it anymore (exception its string interpolation is very ergonomic).  Anyway, before worrying about dhall I will work on a new plugin using STM.TVar.  Reall, thank you for the suggestion!

**Comment by liskin** [comment]
Yeah, `initThreads` is 100% not going to fix this. And yeah, it's the first thing `xmobar` does, but you don't run `xmobar` **before** `xmonad`, you run them both **in parallel**. ;-)

**Comment by guygastineau** [comment]
Oh, good point.

**Comment by guygastineau** [comment]
I made a QueueReader plugin using `TQueue a` from `Control.Concurrent.STM`.  for some reason I am having trouble with my don't icons there even though xpm are still working (and don't icons are working elsewhere).

Anyway, I will make a PR later today.  Should I make a safe default (using `stripActions`) and an unsafe queue reader?

**Comment by guygastineau** [comment]
@jsoo1 It looks like you are following the conversation in my PR.  I think once the CI finishes it will be merged.  If you are still having problems with `HandleReader` I think `QueueReader a` will suit you much better.  Cheers!

**Comment by guygastineau** [comment]
#568 didn't handle whatever issue I encountered here, but I don't need to fix my problem here anymore.  Should we just chalk it up to user error on my part and close this issue, or is there actually something to investigate (knowing that I have neither the time nor will to investigate it)?

**Comment by jaor** [comment]
closing...
