### ISSUE TITLE
Pipewire and Pulseaudio monitors?

### ISSUE THREAD

**Issue by jsoo1** [jaor/xmobar#569]
Should there be pulseaudio and pipewire volume monitors? #535 and #566 make it seem like there are too many incompatibilities between pulse/alsa/pipewire.

**Comment by jaor** [comment]
i think it'd be nice, yes.

**Comment by jsoo1** [comment]
There exists a package for pulseaudio: https://hackage.haskell.org/package/pulseaudio
It looks like it could handle subscriptions, but I have not yet tried it out.

Would flags or commands for with_{alsa,pulse,pipewire} be mutually exclusive? Could be a tricky bit of CPP...

**Comment by yusi1** [comment]
There's a fix in Pipewire for this now, look at the bottom of this thread:
https://github.com/jaor/xmobar/issues/535#issuecomment-1027267745

**Comment by jaor** [comment]
moved to https://codeberg.org/jao/xmobar/issues/569
