### ISSUE TITLE
Mpris2 plugin does not seem to be working

### ISSUE THREAD

**Issue by Shaac** [jaor/xmobar#582]
Hello,

I’ve been using xmobar for many years but I never managed to get the Mpris2 plugin working. I feel like it is bugged, but maybe the issue comes from my side (although I tried with different setups).

Even the simpliest use of Mpris2 does not work. I added `Run Mpris2 "clementine" [] 10,` in my `commands` (adding parameters inside `[]` does not change anything`. The bar then shows "Updating..." but it is never updated.

I used to use the Mpris1 plugin which worked fine, [but clementine dropped its support some time ago](https://github.com/clementine-player/Clementine/issues/5884).

I don't think the problem comes from clementine itself, as I can manually request informations with the command `qdbus org.mpris.MediaPlayer2.clementine /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get org.mpris.MediaPlayer2.Player Metadata`. But maybe the plugin uses a different command, and that is the problem?

**Comment by jaor** [comment]
hi... sorry for the late reply, i missed this one.

mpris2 works just fine for me with several players, so i'm not sure
what might be happening in your case.  are you compiling with dbus
support? have you tried with any other mpris2 player? and specifying
an explicit template instead of defaulting
(i.e., something like `Run Mpris2 "clementine" ["-t",
"<title>"]`... you already mention you've tried putting arguments
there, just double-checking because i'm out of ideas :)).

**Comment by Shaac** [comment]
Hello, thanks for the reply.

Sorry I forgot to add info on my setup, I’m using Archlinux that packages xmobar with those flags: https://github.com/archlinux/svntogit-community/blob/packages/xmobar/trunk/PKGBUILD (and dbus is here).

I also checked that the flag `with_mpris` is here. Your documentation says the haskell modules `dbus` and `text` must be installed. I’m not entirely sure how to exactly check that but I believe they are installed on my system. This is probably not the best way to check this but I used on `gchi` the commands `:t DBus.Client.connectSession` and `:t Data.Text.empty` and they both worked.

I installed an other mpris2 player (called tauon). Same as with clementine: it shows when I call `dbus` on the command line, but xmobar stay stucked with the `Updating...` text.

I tried an explicit template but it is not working either. Note that everything was working fine with mpris1 (until clementine dropped the support).

I’m ready to debug and find out what is happening, but my main issue there is I don't know how to log things. What haskell command should I use for that and where can I see the output of those prints?

**Comment by jaor** [comment]
you're using mpris2 rather than mpris in your template, right?

**Comment by Shaac** [comment]
oh no…

Well, I completely forgot about the template line…

Sorry for this stupid mistake and for wasting your time. Thank you for helping me fix it!

**Comment by jaor** [comment]
> Sorry for this stupid mistake and for wasting your time. Thank you for
> helping me fix it!

no worries :)

cheers,
jao
-- 
Adding manpower to a late software project makes it later.
 -Fred Brooks
