### ISSUE TITLE
Trouble Testing the config parser

### ISSUE THREAD

**Issue by guygastineau** [jaor/xmobar#585]
I extracted this from the discussion in #574, because it was unnecessary noise.  I still think testing the config parser for regressions would be nice :)

> I am trying to make tests for config parsing, but when I add the new test module to the cabal file (in the other-modules of Xmobar.Test stack test and cabal test both complain:

```
[40 of 65] Compiling Xmobar.Run.Runnable[boot]
[41 of 65] Compiling Xmobar.Plugins.Monitors.Disk
            
/home/guy/repos/haskell/xmobar/src/Xmobar/Plugins/Monitors/Disk.hs:18:1: error:
    Could not load module ‘Xmobar.System.StatFS’
    it is a hidden module in the package ‘xmobar-0.40’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |        
18 | import Xmobar.System.StatFS
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

> when I remove literally just this line Xmobar.Config.Spec from the other modules sectipon of the test config it builds again and runs no problem. 

> EDIT: I don't know what it is building the Disk plugin anyway, and I definitely can't figure out why a module in xmobar can't use a hidden module and only when a module is added to XmobarTest! I am going insane! I will take a break.

**Comment by jaor** [comment]
i'm not sure i understand fully, but what prevents us adding to XmobarTest's other-modules stanza all the needed modules so that it compiles? (i think your guess is right, and it's the runnable trick pulling everything with it...)

**Comment by guygastineau** [comment]
Good idea.  I understand this usage of cabal better now.  I forgot about this when I stopped working on the dhall config extension.  I think I want to build it though, so I'll work this issue out.

**Comment by guygastineau** [comment]
I'll see if I can find my local branch with these problems and get it working.

**Comment by jaor** [comment]
moved to https://codeberg.org/jao/xmobar/issues/585
