### ISSUE TITLE
Formalize template grammar?

### ISSUE THREAD

**Issue by jsoo1** [jaor/xmobar#588]
I did something rash on my quest to use xmobar more as a library than a binary.  My goal after #574 (ipc signals with STM) was to accomplish `action`s with haskell IO actions as well as straight up spawning shells.  I started working on it and realized I would want to have a datatype to parse the template into instead of `String`. This turned out to be a lot of work (though I am quite close to a working version). [contributing.org](https://github.com/jaor/xmobar/blob/master/contributing.org#contributing-changespatches-to-xmobar) says to discuss non-trivial changes with the community before doing anything else. I am sorry I did not raise this earlier.

My question is: Is the community interested in a more formal grammar and datatype for the template to replace the big `String` we have now? I made a `Bar` type and adjusted the template parser. Along with the aforementioned possibility of `IO` `action` segments, other improvements include a test suite for the template parser, better error messages for debugging, a cleaner template parser, and simplified logic in the event loop.  At some point, the new datatype can also be documented as a grammar for the template.

**Comment by jaor** [comment]
moved to https://codeberg.org/jao/xmobar/issues/588
