### ISSUE TITLE
xmobar missing modules and missing frame at the end of screen

### ISSUE THREAD

**Issue by cakarmustactalone** [jaor/xmobar#589]
Hi guyz,

I have problem with my xmobar. Could not find exact solution or description for my problem but that  happens everytime. 

When I boot pc , every 1 of 3 times I face with that problem:

![discorda](https://user-images.githubusercontent.com/74772622/142859571-c3c9974e-e3b5-4905-a41d-b28bc73692bb.png)

I have played with my polybar config and according to things I have experienced, it is not about polybar.

I want my xmobar with the default one like :

![githuba](https://user-images.githubusercontent.com/74772622/142859709-516e4fbd-8703-4ba2-84df-187e50da7ec3.png)

I could not found the exact solution for that. Actually exact problem description. That is so annoying. Help please.

Thanks for all!

**Comment by jaor** [comment]
closing for now, since no further information was provided.  please by all means reopen if you need, thanks!
