### ISSUE TITLE
Newlines in window titles from XMonadLog need handled

### ISSUE THREAD

**Issue by mathstuf** [jaor/xmobar#590]
There's a parser error when a window has a newline in its title. The `sanitize` function also should replace it with some replacement. Maybe ` — ` or ` / ` (there are spaces around these) even if the rendering isn't great?

**Comment by jaor** [comment]
@mathstuf i've pushed a little patch (https://github.com/jaor/xmobar/commit/2d8b01a88efd2e5f8e976c07bde9a0b71c19f4b7) that uses the dash to replace newlines: does it look good to you? thanks, and sorry for the delay!

**Comment by mathstuf** [comment]
Thanks! The diff looks good at least. I tried finding where this happened and just kept running in circles :) .

**Comment by jaor** [comment]
perfect, thanks for checking! i'm closing the bug then...
