### ISSUE TITLE
Arch: Lexical Error when trying to install xmobar from source using stack

### ISSUE THREAD

**Issue by CamnJB** [jaor/xmobar#591]
`alsa-mixer> configure
alsa-mixer> Configuring alsa=mixer-0.3.0...
alsa-mixer> build
alsa-mixer> Preprocessing library for alsa-mixer-0.3.0..
alsa-mixer> c2hs: C header contains errors:
alsa-mixer>
alsa-mixer> .stack-work/dist/x86_64-linux-tinfo6.Cabal-3.0.1.0/build/Sound/ALSA/Mixer/Internal.i:1: (column 1) [ERROR] >>> Lexical error !
alsa-mixer> The character '#' does not fit here.
alsa-mixer>
Progress 1/2

-- While building package alsa=mixer-0.3.0 (scroll up to its section to see the error) using:
/home/cameron/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.3 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0 build --ghc-options " -fdiagnostics-color=always"
Process exited with code: ExitFailure 1

**Comment by CamnJB** [comment]
If I set all_extensions to false in stack.yaml xmobar installs no problems but I'm lacking all the bells and whistles

**Comment by CamnJB** [comment]
xmobar installs with stack if I remove with_alsa and with_iwlib extensions the problem with with_iwlib is "iwlib must match >0.1.0 && <0.2, but the stack configuration has no specified version (latest matching version is 0.1.0)
needed since xmobar is a build target.

**Comment by jaor** [comment]
actually, with_iwlib is deprecated for recent linux kernels, and
with_nl80211 should work instead.  perhaps it's time to make the latter
the default, and leave with_iwlib as an opt-in...

**Comment by CamnJB** [comment]
Do you know what's causing the problem with alsa? It seems to not want to build it at all

**Comment by jaor** [comment]
On Thu, Dec 16 2021, CamnJB wrote:

> Do you know what's causing the problem with alsa? It seems to not want
> to build it at all

hmm, no, i don't.  i seldom use stack... i remember there were some libs
that were outside the platform and had to be included by hand... maybe a
different/newer resolver is needed?
