### ISSUE TITLE
'alpha' option does not work

### ISSUE THREAD

**Issue by sebasijan** [jaor/xmobar#595]
setting this in xmobarrc2

            bgColor = "#333333", 
            fgColor = "#333333", 
            alpha = 0,

simply sets the entire bar to solid black as seen here (transparent bit comes from stalonetray transparent option)

![image](https://user-images.githubusercontent.com/13226838/147875846-dfe80cba-62de-44ea-80a2-432318215c00.png)

I also tried running it with `xmobar -A 0` from inside xmonad.hs

Remove bgColor and fgColor does not help

**Comment by slotThe** [comment]
I would imagine that you need a compositor like compton or picom for
transparency to work.

**Comment by sebasijan** [comment]
@slotThe  I have compton running and transparency is working fine everywhere except for xmobar

Please let me know if I can provide any helpful details

**Comment by jaor** [comment]
@sebasijan what happens if you set alpha to, say, 100? do you configure compton in any particular way? any chance you could try picom instead (it's a drop-in replacement)?

**Comment by sebasijan** [comment]
@jaor Setting it to 100 causes it to be completely opaque

Since opening this question I have switch to picom, and its working well

**Comment by jaor** [comment]
On Tue, Feb 22 2022, sebasijan wrote:

> @jaor Setting it to 100 causes it to be completely opaque
>
> Since opening this question I have switch to picom, and its working well

thanks for the update!  closing the bug then, since it seems to be a
problem related to an specific (unmaintained, i think) compositor.
