### ISSUE TITLE
BufferedPipeReader not changing after piping into status file

### ISSUE THREAD

**Issue by sebasijan** [jaor/xmobar#597]
Apologies if I have misunderstood this, but I am trying to display the volume only after changing it

Steps

 1. empty `/tmp/xmobar_status_jrk`
 2. recompile xmonad
 3. execute [status.sh](https://raw.githubusercontent.com/jaor/xmobar/master/examples/status.sh)

**expected**
since status.sh pipes data into xmobar_status_jrk, it should appear for `15` units of time, before changing back to whatever is inside xmobar_window

**actual**
contents of xmobar_status_jrk do appear after recompiling, but not after running status.sh

my xmobarrc2:

        Config { 
                font = "xft:Anonymice Nerd Font Mono:size=5"
                bgColor = "#333333", 
                fgColor = "#FFFFFF", 
                position = TopP 0 0, 
                commands = [ 
                        Run Date "%a %d%m %H:%M" "date" 10,
                        Run StdinReader,
                        Run Com "bash" ["/home/bassie/scripts/get-volume.sh"] "myvolume" 1,
                        Run Com "bash" ["/home/bassie/scripts/get-battery-info.sh"] "mybattery" 1,
                        Run BufferedPipeReader "bpr" [
                                (  0, False, "/tmp/xmobar_window"  ),
                                ( 15, False, "/tmp/xmobar_status_jrk" )
                        ]
                ], 
                sepChar = "%", 
                alignSep = "}{", 
                template = " %StdinReader% %bpr% }%date% %mybattery%{ %myvolume% "
        }

**Comment by jaor** [comment]
hi @sebasijan ... sorry for the late reply.  is `/tmp/xmobar_status_jrk`
a unix pipe? (that is, have you created it with mkfifo?)

**Comment by jaor** [comment]
closing for now, since a solution was provided.  please reopen if it doesn't work for you, thanks!
