### ISSUE TITLE
Output to terminal

### ISSUE THREAD

**Issue by pavel-the-best** [jaor/xmobar#601]
Is it possible to output statusline to stdout using escape color sequences?
That would allow using xmobar inside wayland.

**Comment by jaor** [comment]
On Thu, Jan 27 2022, Pavel Kalugin wrote:

> Is it possible to output statusline to stdout using escape color sequences?
> That would allow using xmobar inside wayland.

not currently, but that's an interesting idea.  what do you have in mind
for wayland? would one use waybar or perhaps sway's built-in bar?

i don't think it'd be too complicated to implement (famous last words)...

**Comment by pavel-the-best** [comment]
I was thinking about status_command in waybar, just like i3status, but not quite i3status :)

**Comment by jaor** [comment]
i've created a new branch named text and implemented there basic text
output to stdout.  it doesn't support colours yet, but the basics are
there.  it also simply concatenates the left, center and right
segments; with a textOutputWidth configuration parameter it shouldn't
be difficult to add some aligment too, but not sure how useful that is
in this case.  to make xmobar output to stdout, one just either passes
the flag -T to its invocation, or sets textOutput=True in the
configuration file.

**Comment by pavel-the-best** [comment]
I've checked out your branch. In general, it works, but sway fails to update the status line, I'm trying to debug this issue. It seems like it has some trouble reading from xmobar.
Please read https://manpages.debian.org/testing/sway/swaybar-protocol.7.en.html. This is a JSON-based protocol for status bar, used initially for i3bar and now, with some changes listed in the man page, for swaybar.  
I still think that terminal output is useful, but Sway does not render escape sequences. Swaybar-protocol also allows some features like clicking support.

**Comment by pavel-the-best** [comment]
Looks like swaybar is chunking data in 8192-byte blocks and then processing it all. I will continue debugging this issue.

**Comment by jaor** [comment]
how about using waybar and their "Custom" plugin?  i think one can use a
text based-protocol, by emitting `<contents>\n<tooltip>\n<class>`,
instead of json
(https://github.com/Alexays/Waybar/wiki/Module:-Custom#module-custom-config-return-type)... this
can be done via xmobar's template: just add the trailing info, something
like:

       "-t", ".....
this is the tooltip
xmobar-class"

does that work for you? also, according to their wiki, setting "escape"
to true in the custom module should, well, enable escapes, and also
on-click support.

another possibility is just using a shell scripts that pipes xmobar's
output and emits the json expected by swaybar.

finally, adding an option for json output is not difficult, when we
merge this branch. patches welcome :) but i wonder if it's really
needed...

**Comment by pavel-the-best** [comment]
I know that's not the real fix, but replacing `xmobar -T` with `unbuffer xmobar -T` makes the problem disappear.

**Comment by pavel-the-best** [comment]
@jaor no, that does not work: "escape" in waybar escapes only pango markup, not ANSI escape symbols.

**Comment by pavel-the-best** [comment]
The buffering problem still persists and I even managed to create simple reproducible test for it:
`echo "" | xmobar -T | cat` buffers in batches of 8192 bytes.

**Comment by pavel-the-best** [comment]
I've found a fix to buffering: just set line-buffering in startTextLoop.
[buffering-fix.patch.txt](https://github.com/jaor/xmobar/files/7963313/buffering-fix.patch.txt)

**Comment by jaor** [comment]
On Sat, Jan 29 2022, Pavel Kalugin wrote:

> I've found a fix to buffering: just set line-buffering in
> startTextLoop.
> [buffering-fix.patch.txt](https://github.com/jaor/xmobar/files/7963313/buffering-fix.patch.txt)

excellent: applied, thanks!

**Comment by jaor** [comment]
On Sat, Jan 29 2022, Pavel Kalugin wrote:

> @jaor no, that does not work: "escape" in waybar escapes only pango
> markup, not ANSI escape symbols.

oh, that's unfortunate :(

**Comment by pavel-the-best** [comment]
> On Sat, Jan 29 2022, Pavel Kalugin wrote: @jaor no, that does not work: "escape" in waybar escapes only pango markup, not ANSI escape symbols.
> oh, that's unfortunate :(

I've implemented pango markup in [my fork](https://github.com/pavel-the-best/xmobar) (branch text).
Feel free to merge and run autoformatter.

**Comment by jaor** [comment]
On Mon, Jan 31 2022, Pavel Kalugin wrote:

> I've implemented pango markup in [my
> fork](https://github.com/pavel-the-best/xmobar) (branch text).  Feel
> free to merge and run autoformatter.

excellent!  i've just commented on a little nit, which i can address
later if you don't beat at it (i also just saw i forgot to push the
linebuffering patch, sorry about that... but it's good it comes from
you, the real author, anyway).
