### ISSUE TITLE
DiskIO plugin randomly stopped working

### ISSUE THREAD

**Issue by KungFuJesus** [jaor/xmobar#613]
I couldn't say which revision, I'm using a -9999 build in gentoo so it's follow HEAD of git, but this is my config:
```
, Run DiskIO [("nvme0n1", "[/] R:<read> W:<write>"), ("sda", "[steam] R:<read> W:<write>"), ("sdb", "[F] R:<read> W:<write>")] [] 5
```

This is my template:
```
, template = "%coretemp%|%bond0%|%eth4%|<fc=#08FFE2>[Disk IO] </fc>%diskio%}{g:%gov%|%cpufreq%"
```

And this is what I'm seeing:
![dio](https://user-images.githubusercontent.com/3620277/156596129-35e4eb19-d73d-41f6-b601-c20688f4be2d.png)

**Comment by jaor** [comment]
does changing the "[...]" names in the definition ([/], etc.) change
anything?  maybe the parser gets confused by the slash...

**Comment by KungFuJesus** [comment]
Nope.  Full config:
```
Config { hideOnStart = False
       , bgColor = "black"
       , fgColor = "grey"
       , position = Bottom
       , lowerOnStart = True
       , commands = [ Run Network "bond0" ["-t", "<fc=#08FFE2>[Net IO]</fc> tx: <tx>|rx: <rx>","-L","0","-H","78643200","--normal","green","--high","red", "-S", "Yes"] 5
            , Run Network "eth4" ["-t", "<fc=#08FFE2>[IB IO]</fc> tx: <tx>|rx: <rx>","-L","0","-H","805306368","--normal","green","--high","red", "-S", "Yes"] 5
		    , Run CoreTemp ["-t", "Temp:<core0>|<core1>|<core2>|<core3>|<core4>|<core5>|<core6>|<core7>|<core8>|<core9>|<core10>|<core11>|<core12>|<core13>C","-L", "40", "-H", "60","-l", "lightblue", "-n", "gray90", "-h", "red"] 50
		    , Run DiskIO [("nvme0n1", "[root] R:<read> W:<write>"), ("sda", "[steam] R:<read> W:<write>"), ("sdb", "[F] R:<read> W:<write>")] [] 5
            , Run CpuFreq ["-t", "<cpu0>|<cpu1>|<cpu2>|<cpu3>|<cpu4>|<cpu5>|<cpu6>|<cpu7>|<cpu8>|<cpu9>|<cpu10>|<cpu11>|<cpu12>|<cpu13>", "-L", "2", "-H", "3", "-l", "lightblue", "-n", "white", "-h", "red", "-d", "2"] 50
		    , Run Com "/home/adam/bin/getcpugov.sh" [""] "gov" 30
		    --, Run Com "/home/adam/bin/getcpufreq.sh" [""] "freq" 20
            --, Run PipeReader "/tmp/xenxp.pipe" "xenxppipe"
            --, Run PipeReader "/tmp/xenloc.pipe""xenlocpipe"
       ]
       , sepChar = "%"
       , alignSep = "}{"
       , template = "%coretemp%|%bond0%|%eth4%|<fc=#08FFE2>[Disk IO] </fc>%diskio%}{g:%gov%|%cpufreq%"
```

This is the config for a secondary xmobar spawned on the bottom.  I wish I had a decent avenue to bisect but it was working for sure a while back.

**Comment by jaor** [comment]
tricky to say anything, it's working just fine for me and we haven't
changed anything around there recently.  i guess you can reproduce the
problem with a simpler config only running the diskio monitor, right?
and a single monitored disk, no matter which one?

**Comment by KungFuJesus** [comment]
```
Config { hideOnStart = False
       , bgColor = "black"
       , fgColor = "grey"
       , position = Bottom
       , lowerOnStart = True
       , commands = [
		     Run DiskIO [("sda", "[root] R:<read> W:<write>")] [] 5
       ]
       , sepChar = "%"
       , alignSep = "}{"
       , template = "<fc=#08FFE2>[Disk IO] </fc>%diskio%"
```

Still gives me nothing.  Is there something parsed on proc or sysfs maybe that my kernel configuration lacks for whatever reason?  Though, I'm pretty sure I've not changed anything on that end.

**Comment by jaor** [comment]
On Thu, Mar 03 2022, Adam Stylinski wrote:

> Still gives me nothing. Is there something parsed on proc or sysfs
> maybe that my kernel configuration lacks for whatever reason?  Though,
> I'm pretty sure I've not changed anything on that end.

in principle, the monitor uses the information in /proc/diskstats
combined with that in /etc/mtab to relate devices in the former with
mount points used in the configuration... do their contents look
reasonable in your system?

**Comment by KungFuJesus** [comment]
### /proc/diskstats
```
   1       0 ram0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1       1 ram1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1       2 ram2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1       3 ram3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1       4 ram4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1       5 ram5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1       6 ram6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1       7 ram7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1       8 ram8 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1       9 ram9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1      10 ram10 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1      11 ram11 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1      12 ram12 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1      13 ram13 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1      14 ram14 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1      15 ram15 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       0 nvme0n1 3896254 458303 64975994 199317 5766724 2499921 616448683 27256748 0 1434753 27470279 130550 746601 652308008 14213 0 0
 259       1 nvme0n1p1 814 3258 6128 97 1 0 1 0 0 14 97 0 0 0 0 0 0
 259       2 nvme0n1p2 232665 56942 2319184 2920 24416 618519 6064056 50622 0 24781 53616 1124 0 71679992 73 0 0
 259       3 nvme0n1p3 102 99 2420 7 1 0 2 0 0 13 7 0 0 0 0 0 0
 259       4 nvme0n1p4 3662626 398004 62647006 196289 5742306 1881402 610384624 27206126 0 1413943 27416555 129426 746601 580628016 14140 0 0
  11       0 sr0 53 7 242 179 0 0 0 0 0 190 179 0 0 0 0 0 0
   8       0 sda 814242 2426989 105582932 521679 618319 5190 111059344 4128805 0 521604 4726459 0 0 0 0 94842 75973
   8       1 sda1 808829 2426989 105577456 517881 618319 5190 111059344 4128805 0 516313 4646686 0 0 0 0 0 0
   8      16 sdb 79157 47360 1501851 98076 3326 331 1353512 46599 0 13141 145418 559 0 1238400 524 268 218
   8      17 sdb1 73753 47360 1497343 93460 3326 331 1353512 46599 0 6949 140584 559 0 1238400 524 0 0
   8      32 sdc 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   8      48 sdd 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   8      64 sde 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   8      80 sdf 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

The mtab shows /dev/root instead of the nvme path for /, but the sda and sdb bits otherwise look the same.

**Comment by jaor** [comment]
things look more or less normal, and it's working here, so i am not sure
what else to check.  looks as if the mount points in mtab weren't found
in diskstats... disku accesses the same data: does it work for you for
the same mount points that fail for io?  maybe it's something to do with
ghc, although i don't see how (mine is 8.8.x), or the compilation
options...

**Comment by KungFuJesus** [comment]
```
adam@eggsbenedict ~ $ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.0.2
```

**Comment by jaor** [comment]
> Any disk configuration with disku just perpetually says "Updating".

so it seems that for some reason xmobar is not finding a mapping between
names in /etc/mtab and devices in /proc/diskstats.  just to be sure:
those two files are readable by the user running the xmobar process,
right?

**Comment by KungFuJesus** [comment]
```adam@eggsbenedict ~ $ ls -lah /proc/diskstats 
-r--r--r-- 1 root root 0 Feb 21 09:00 /proc/diskstats
adam@eggsbenedict ~ $ ls -alh /etc/mtab
lrwxrwxrwx 1 root root 17 Feb 21 08:57 /etc/mtab -> /proc/self/mounts
```

**Comment by jaor** [comment]
On Fri, Mar 04 2022, Adam Stylinski wrote:

> ***@***.*** ~ $ ls -lah /proc/diskstats 
> -r--r--r-- 1 root root 0 Feb 21 09:00 /proc/diskstats
> ***@***.*** ~ $ ls -alh /etc/mtab
> lrwxrwxrwx 1 root root 17 Feb 21 08:57 /etc/mtab -> /proc/self/mounts

and what are the permissions for /proc/self/mounts?

**Comment by KungFuJesus** [comment]
I'm pretty sure it was following the symlink with that:
```
adam@eggsbenedict ~ $ ls -alh /proc/mounts 
lrwxrwxrwx 1 root root 11 Mar  4 11:03 /proc/mounts -> self/mounts
```
Given how procfs is all pseudo-fs anyway, it'd be strange for these to be anything but what's expected.

**Comment by KungFuJesus** [comment]
Of course, "self" relegates itself to the running process (my shell session that is open there).  But yeah, I wouldn't suspect this would be materially different than any other Linux system.

**Comment by jaor** [comment]
also, does using other names like, say, "nvme0n1p1" give you back any
results (i'm guessing not).  any chance you could compile a git checkout
of the code independently of gentoo?

**Comment by KungFuJesus** [comment]
> also, does using other names like, say, "nvme0n1p1" give you back any results (i'm guessing not). any chance you could compile a git checkout of the code independently of gentoo?

Hmm, specifying the partition appears to have worked for at least sda.  I can apply localized patches via /etc/portage/patches if need be.  My rootfs in /proc/self/mounts is specified as /dev/root it would seem, perhaps that's the crux of the issue?

**Comment by KungFuJesus** [comment]
Weird, looks as though everything is back when specifying partition indices, even on the rootfs.  Was there a recent range in regard to this?

It just seems like it would make more sense to refer to the actual block devices since that's actually the metric that's being measured via the counters in the kernel.

**Comment by KungFuJesus** [comment]
Even weirder, with this:
```, Run DiskIO [("nvme0n1p4", "[/] R:<read> W:<write>"), ("sda1", "[steam] R:<read> W:<write>"), ("sdb1", "[F] R:<read> W:<write>")] [] 5```
The steam volume is being reported twice, now:
![xmobar](https://user-images.githubusercontent.com/3620277/156843629-6d39132e-588d-4b2d-9197-d8a1823288d6.png)

**Comment by KungFuJesus** [comment]
Actual IO on the system, as reported by iostat:
```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           4.83    0.00    0.25    0.04    0.00   94.88

Device             tps    kB_read/s    kB_wrtn/s    kB_dscd/s    kB_read    kB_wrtn    kB_dscd
nvme0n1           1.00         0.00         4.00         0.00          0          4          0
sda              65.00       384.00      4672.00         0.00        384       4672          0
sdb               0.00         0.00         0.00         0.00          0          0          0
sr0               0.00         0.00         0.00         0.00          0          0          0


avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           4.29    0.00    0.25    0.00    0.00   95.46

Device             tps    kB_read/s    kB_wrtn/s    kB_dscd/s    kB_read    kB_wrtn    kB_dscd
nvme0n1           0.00         0.00         0.00         0.00          0          0          0
sda               4.00       584.00         0.00         0.00        584          0          0
sdb               0.00         0.00         0.00         0.00          0          0          0
sr0               0.00         0.00         0.00         0.00          0          0          0


avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           4.76    0.00    0.21    0.00    0.00   95.03

Device             tps    kB_read/s    kB_wrtn/s    kB_dscd/s    kB_read    kB_wrtn    kB_dscd
nvme0n1           3.00         0.00       252.00         0.00          0        252          0
sda               0.00         0.00         0.00         0.00          0          0          0
sdb               0.00         0.00         0.00         0.00          0          0          0
sr0               0.00         0.00         0.00         0.00          0          0          0

```

To be honest, I don't think this IO monitor has really worked correctly for a while.  I seem to recall things being reported to the wrong devices a while back.

**Comment by KungFuJesus** [comment]
It _appears_ that specifying the mounting path gets us there, though, that seems less than ideal.  I guess this isn't a bug at this point, though.  Thanks for the help.

**Comment by jaor** [comment]
On Fri, Mar 04 2022, Adam Stylinski wrote:

> Hmm, specifying the partition appears to have worked for at least
> sda. I can apply localized patches via /etc/portage/patches if need
> be. My rootfs in /proc/self/mounts is specified as /dev/root it would
> seem, perhaps that's the crux of the issue?

could be.  that's different in my case, where it's simply /
