### ISSUE TITLE
MultiCoreTemp plugin fails when hwmon directory is numbered higher than 9

### ISSUE THREAD

**Issue by robwhitaker** [jaor/xmobar#616]
If the CPU temperatures are located in a hwmon folder numbered higher than 9 (e.g. `/sys/bus/platform/devices/coretemp.0/hwmon/hwmon10`), xmobar will fail to find any CPU temperature files and return an empty list from the `hwmonPaths` function. This propagates through until it throws `Prelude.maximum: empty list`, which is displayed on the bar.

From a bit of digging, this happens because the list `[0..9]` is hardcoded [here](https://github.com/jaor/xmobar/blob/master/src/Xmobar/Plugins/Monitors/MultiCoreTemp.hs#L92-L93=).

This could probably be solved by just listing the directory and taking the matching directories within instead of iterating over a hard-coded list, e.g. 

```haskell
filter ("hwmon" `isPrefixOf`) <$> listDirectory "/sys/bus/platform/devices/coretemp.0/hwmon"
```

However, perhaps there was some sort of performance reason for the hardcoded list I'm unaware of. If not and the above solution seems satisfactory, I'll happily open a pull request.

This hardcoded `[0..9]` list is also present in the `coretempPath` and `corePaths` functions as well, which might also be an issue.

**Comment by jaor** [comment]
On Sat, Mar 26 2022, Robert Whitaker wrote:

> filter ("hwmon" `isPrefixOf`) <$> listDirectory "/sys/bus/platform/devices/coretemp.0/hwmon"
>
> However, perhaps there was some sort of performance reason for the
> hardcoded list I'm unaware of.

I cannot remember any such issues...

> If not and the above solution seems satisfactory, I'll happily open a
> pull request.

It looks reasonable to me, many thanks in advance for that.  With that
in place we can directly see if it's a performance problem (which i
really doubt)... in the worst case scenario, i guess we could always
provide an extended argument to specify the concrete folder, and skip
the listing in that case.

> This hardcoded [0..9] list is also present in the coretempPath and
> corePaths functions as well, which might also be an issue.

Agreed.
