### ISSUE TITLE
Volume plugin not working when using pipewire

### ISSUE THREAD

**Issue by spcbfr** [jaor/xmobar#619]
I recently switched to pipewire, when I reloaded my config, the xmobar plugin that prints the current volume stopped working, I am not sure why (as I heard that pipewire was supposed to be a drop in replacement)
here is my configuration for the plugin:
```
 Run Volume "default" "alsa_output.pci-0000_00_1b.0.analog-stereo" [
 "-t", "<fn=2>\xf027</fn> <volume>%"] 10
```

**Comment by neosimsim** [comment]
I realized that after switching to pipewire, `alsactl` was missing from my system. Installing it manually (`alsaUtils` in nixpkgs) fixed the Alsa plugin for me.

**Comment by jaor** [comment]
thanks for the feedback. @spcbfr i'm closing the issue, but please feel free to re-open it if you still have problems.
