### ISSUE TITLE
Unable to toggle visibility of xmobar by dbus after xmonad --recompile; xmonad --restart

### ISSUE THREAD

**Issue by hereGittyGitty** [jaor/xmobar#632]
Hi,

since `xmobar v0.42`, I am unable to toggle the visibility of `xmobar` after `xmonad --recompile; xmonad --restart` when using

```
dbus-send --session --dest=org.Xmobar.Control --type=method_call '/org/Xmobar/Control' org.Xmobar.Control.SendSignal "string:Toggle 0"
```

It works before restarting `xmonad`.

It works fine with `xmobar v0.41` before and after restarting `xmonad`.

Thanks and have a nice day :)

**Comment by jaor** [comment]
moved to https://codeberg.org/jao/xmobar/issues/632
