### ISSUE TITLE
Volume (and Alsa) plugin fails to recognize some options

### ISSUE THREAD

**Issue by eppolito** [jaor/xmobar#633]
The following options (everything related to configuring the appearance of `<status>`) are unrecognized by both the `Volume` and `Alsa` plugins for me.

1. `--on` and `-O` for the "on" string
2. `--off` and `-o` for the "off" string
3. `--onc` and `-C` for coloring the "on" string
4. `--offc` for coloring the "off" string

Here is a minimal config which exhibits this behaviour.

```
Config {
  commands = [
      Run Alsa "default" "Master" [
          "--template", "Vol <volume> <status>"
          , "--off", "yellow"
          , "--offc", "yellow"
          , "--on", "yellow"
          , "--onc", "yellow"
          , "-o", "yellow"
          , "-c", "yellow"
          , "-O", "yellow"
          , "-C", "yellow"
          ]
      ]
  , sepChar = "%"
  , alignSep = "}{"
  , template = "}%alsa:default:Master%{"
  }
```

I suspect the issue may live in `src/Xmobar/Plugins/Monitors/Volume.hs`.  Note that the `"-c"` option does not throw an `unrecognized option` because `"-c"` is one of the default options.  Could this be part of the problem?  I haven't looked at the definition of `parseOptsWith`, but I wonder if it stops parsing once it sees a duplicated option.

Thanks for taking the time to read this, and for writing such a great piece of software!  I love `xmobar` :)

**Comment by jaor** [comment]
you are missing a "--" separator to introduce the extra arguments.

try:

Config {
   commands = [
       Run Alsa "default" "Master" [
           "--template"
           , "Vol <volume> <status>"
           , "--"
           , "--off", "yellow"
           , "--offc", "yellow"
           , "--on", "yellow"
           , "--onc", "yellow"
           ]

**Comment by eppolito** [comment]
Interesting, I completely misunderstood how `"--"` is handled here.  I thought options after this would be passed directly to the command run by the monitor on the system...  Seems this was a 10t error on my part.

Thanks so much for your help!
