### ISSUE TITLE
chrome mpris

### ISSUE THREAD

**Issue by zedgamer9128** [jaor/xmobar#637]
can chrome work with mpris2 i am using chromium parameter in mpris2 command but it is not working

**Comment by jaor** [comment]
On Fri, Jul 01 2022, Zedgamer9128 wrote:

> can chrome work with mpris2 i am using chromium parameter in mpris2
> command but it is not working

i think the name of the dbus interface for chromium is not exactly that,
but an "instance name" that adds an id, and is therefore not recognised
by the monitor.  i work around those problems by installing playerctl
and running playerctld, and then the mpris2 name is always playerctl, no
matter where it comes from...

**Comment by zedgamer9128** [comment]
`Run Mpris2 "playerctl" ["-t", "<artist> - [<composer>] <title>"] 10`
Not working showing N/A

**Comment by jaor** [comment]
the name of the dbus interface is "playerctld", not playerctl...
