### ISSUE TITLE
Too many wakeups (using ghc-7.4.1)

### ISSUE THREAD

**Issue by nidico** [jaor/xmobar#89]
I just upgraded to fedora 18 and thus from ghc-7.0.4 to ghc-7.4.1. Afterwards xmonad and xmobar wake up the cpu too often.

It turned out that the xmonad issue is a [ghc issue](http://hackage.haskell.org/trac/ghc/ticket/5991), which is fixed in ghc-7.6.2 (or 7.4.2, not quite sure). The workaround to compile xmonad using `ghc -threaded xmonad.hs` fixes the high number of events for me (from 100 to almost none).

However installing xmobar with `cabal install xmobar --ghc-options=-threaded` doesn't make a difference - xmobar still produces around 75 wakups/s. 

My xmobar config is the following:

``` haskell
Config { font = "-misc-fixed-*-*-*-*-10-*-*-*-*-*-*-*"
       , bgColor = "black"
       , fgColor = "grey"
       , position = TopW L 100
       , lowerOnStart = True
       , commands = [ Run Weather "EDDB" ["-t","<tempC>°C","-L","12","-H","30","--normal","green","--high","red","--low","lightblue"] 36000
                    , Run Battery ["-t", "<left> bat"] 50
                    , Run Cpu ["-t", "<total> cpu", "-L","50","-H","75","--normal","orange","--high","red"] 10
                    , Run Memory ["-t","<usedratio>% mem"] 10
                    , Run Date "%a %-d.%m %k:%M" "date" 50
                    , Run StdinReader
                    ]
       , alignSep = "}{"
       , template = "%StdinReader% }{ %cpu% | %battery% | %memory% | %EDDB% | <fc=#ee9a00>%date%</fc>                    "
      }
```

Any ideas?

Update: This is also reported in the ArchLinux tracker: https://bugs.archlinux.org/task/33277

**Comment by liskin** [comment]
I've been using `-with-rtsopts=-V0` to make xmobar/xmonad less watt-hungry for a few years. I'm not sure how safe this and I'd be hesitant to just put it into `xmobar.cabal`, but I've had it there for years and it hasn't caused problems. But it's kind of sad that this is still a problem with GHC 8. :-/

**Comment by jaor** [comment]
that's very interesting. perhaps we could put this rtsopts setting under
a compilation flag?

**Comment by liskin** [comment]
Perhaps. But then haven't been any reports of too many wakeups for the last 2 years (mostly because intel realized software developers are idiots and managed to fix this in the hardware) so maybe not worth the trouble. :-)

**Comment by edmund-huber** [comment]
I'm using xmobar 0.24.3 compiled using ghc 8.0.2. I set the threaded flag to default True, cabal installed, (checked that `sha1sum $(which xmobar)` changed), still lots of wakeups (~100/s). Nothing unusual in xmobarrc..

**Comment by jaor** [comment]
i've checked with `health-check`, and, for me, compiling with the
--with-rtsopts=-V0 flag reduces wakeups from ~60/s to ~3/s.  i'd call
that a net win, and i've observed no downside running xmobar compiled
with that flag during the last month.  so i've just pushed a patch that
adds that compilation option, controlled by a new flag with is set to
True by default.

please, let me know whether it also improves things for you.  thanks!

**Comment by jaor** [comment]
this change is in 0.24.4 and it works for me, so i'm closing the bug.  feel free to reopen as needed.
